### ISSUE TITLE
Code generated from proto files breaks unit tests

### ISSUE THREAD

**Issue by rolinh** [cilium/cilium#12772]
PR #12611 updated some dependencies that affect files that are generated from `proto` definitions, namely:
- `github.com/golang/protobuf`: `v1.3.2`  => `v1.4.2`
- `google.golang.org/genproto`: `v0.0.0-20190819201941-24fa4b261c55` =>  `v0.0.0-20200526211855-cb27e3aa2013`
- `google.golang.org/grpc`: `v1.26.0` => `v1.27.0`

PR #12677 re-generated these files. This was done due to a backward compatible API change done as part of #12655 that required the files to be re-generated.

All seemed fine until an attempt to update the Cilium dependency of the Hubble CLI repo which [revealed](https://github.com/cilium/hubble/pull/328#issuecomment-664986343) a problem with the Hubble CLI unit tests. Indeed, our unit tests are affected by [this `testify` library bug](https://github.com/stretchr/testify/issues/930). The TLDR is that `go-spew`, which is a dependency of `testify`, fails to detect cycles and enters into an infinite recursion as explained in [this bug report](https://github.com/davecgh/go-spew/issues/66) ([and](https://github.com/davecgh/go-spew/issues/108) [many](https://github.com/davecgh/go-spew/issues/81) [other](https://github.com/davecgh/go-spew/issues/76) [reports](https://github.com/davecgh/go-spew/issues/53)).

It is unclear if/when `testify` will be fixed as the bug was reported over 3 months ago and nothing seemed to have moved so far. Worse, the `go-spew` bug was reported over 3 _years_ ago and is still open. Actually, `go-spew` did not receive any update in almost 2 years so it is unclear if it is still maintained.

This issue leads to the following problems:
- The Cilium dependency of the Hubble CLI cannot be upgraded as it breaks unit tests.
- New unit tests for Hubble Relay can't be implemented as the bug manifests there as well.

We need a solution soon as this is blocking further work. As a short term solution, these 4 options should be considered:
1. As part of implementing https://github.com/cilium/hubble/issues/333, revert the dependencies to a version combination that is known to work and re-generate the code.
2. Write a `testify` compatible shim, for instance by using [`go-cmp`](https://github.com/google/go-cmp)for the `testify` assert/require functions that we use in the tests and replace the import directives.
3. Fork and patch `testify`.
4. **Fix tests that fail by replacing `testify` with `testing` or other.**

I started working on option 2 but it appears difficult to implement a compatible shim, at least with `go-cmp`, as unexported fields are not compared by default and require to use specific options. It may be possible to make a shim that is very close to `testify` API-wise but I don't think we can make it a 100% drop-in replacement.

@gandro experimented with `go-spew` [configuration options](https://godoc.org/github.com/davecgh/go-spew/spew#hdr-Configuration_Options) to no avail (notably  he tried setting `MaxDepth` which should allow setting the maximum number of levels to descend into nested data structures but it seems that it generates a huge diff that breaks equality tests).

Note that I have also opened #12767 to try and update protobuf/grpc related dependencies, which do generate new code, but I haven't yet tested if the problem still manifests.

cc @glibsm @nathanjsweet

**Comment by michi-covalent** [comment]
tempting to go with the option 1 at least for the short term to unblock.

there is already a function to test the equality of proto messages, so maybe another option is to use that to assert with testify?

https://godoc.org/github.com/golang/protobuf/proto#Equal
 https://godoc.org/github.com/stretchr/testify/assert#ComparisonAssertionFunc

just out of curiosity how many assertions are failing in the hubble repo?

**Comment by Rolinh** [comment]
> just out of curiosity how many assertions are failing in the hubble repo?

That's a good point, I did not check. Supposedly, all tests that do equal comparison on proto generated struct.
I don't think we have too many though so I added option 4 to the list: Fix tests that fail by replacing testify with testing or other.
This could be another way to unblock the situation.

**Comment by Rolinh** [comment]
I fixed failing tests in Hubble CLI (see https://github.com/cilium/hubble/pull/335) and managed to implement unit tests for Hubble Relay using `go-cmp` instead (see #12786). Therefore, we can remove the priority "high" label as this is not a blocker anymore.

However, we should probably define our strategy for the long run (eg: systematically use `go-cmp` when comparing proto generated structs in unit tests).

**Comment by glibsm** [comment]
There is also `proto.Equal` https://godoc.org/github.com/golang/protobuf/proto#Equal

```
Equal reports whether two messages are equal. If two messages marshal to the same bytes under deterministic serialization, then Equal is guaranteed to report true.

Two messages are equal if they are the same protobuf message type, have the same set of populated known and extension field values, and the same set of unknown fields values.

Scalar values are compared with the equivalent of the == operator in Go, except bytes values which are compared using bytes.Equal and floating point values which specially treat NaNs as equal. Message values are compared by recursively calling Equal. Lists are equal if each element value is also equal. Maps are equal if they have the same set of keys, where the pair of values for each key is also equal. 
```

`assert.True(t, proto.Equal(foo, bar))` seems like it could work. However, it's not clear how a slide of messages could be compared using this method

**Comment by michi-covalent** [comment]
@glibsm yeah i think the nice thing about what @Rolinh did in https://github.com/cilium/hubble/pull/335 is that it formats the diff between expected and actual nicely.

**Comment by glibsm** [comment]
@Rolinh this issue has been resolved, correct?

**Comment by Rolinh** [comment]
@glibsm Not really resolved, more like worked around by not using `testfity` but `go-cmp` for the tests that fail. I'm OK to close the issue if we consider this solution good enough.
