### ISSUE TITLE
Socket-lb: Handling of active connections to stale backends

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#12859]
When kube-proxy replacement (and socket-lb) is enabled, client pods can continue to connect to service backends that were deleted. This is because of the way backend selection happens in case of socket-lb in the socket `connect` calls.
Connected UDP clients are particularly susceptible to such issues.

Fix:
[ ] (New kernels) We are adding a capability in BPF to destroy sockets to force such client pods to re-connect. For more background, here is the link to the Linux plumbers conference talk that discusses the issue and proposed solution - https://lpc.events/event/16/contributions/1358/. The kernel changes are ~currently in review~ merged upstream.
[ ] (Old kernels) https://github.com/cilium/cilium/pull/25169

Edited the description to reflect the most up-to-date analysis and next steps.

**Comment by errordeveloper** [comment]
@aditighag please add correct labels to this :)

**Comment by brb** [comment]
I think this issue might duplicate https://github.com/cilium/cilium/issues/10217. Also, https://github.com/kubernetes/kubernetes/issues/71514 might be relevant.

**Comment by aditighag** [comment]
#10217 is a related issue as mentioned in the sig-datapath meeting, with a few differences : 1) With #10217, the pod is getting shut down anyway so there is a possibility that the pod application server would send a `RST`. Also, we exactly know how long we need to defer removing the pod entry from backends list from the LB map. 2) In case of LRP, we may have to defer redirecting traffic (with bounded timeout) in case of "active" connections. 3) As mentioned in the description, there would be cases, where clients (especially long-lived connections) would recover with only timeouts when the corresponding server pods are killed (no graceful termination). In such case, we may need to send a `RST` explicitly.

**Comment by aditighag** [comment]
Tracking the fix for this issue in https://github.com/cilium/cilium/issues/14844.

**Comment by aditighag** [comment]
Reopening this issue as it's relevant in the context of long-lived connections for connected UDP (e.g., Envoy proxy), whereby applications are stuck with sticky backends when the backend pods are deleted.

**Comment by aditighag** [comment]
We'll need a new capability in BPF to resolve this issue. For more background, here is the link to the Linux plumbers conference talk that discusses the issue and proposed solution - https://lpc.events/event/16/contributions/1358/.

**Comment by zuzzas** [comment]
There is an ugly hack that [skips](https://github.com/cilium/cilium/blob/7021861ae9b1f85451fe6177190b0bc3f8321e28/bpf/bpf_sock.c#L360) socket xlation in non-host network namespaces. Works on Kernel >=5.7.

```
bpf-lb-sock-hostns-only: true
```

**Comment by jmichalek132** [comment]
Hi @margamanterola sorry for the late reply I was on PTO, unfortunately, I am being told by on my side we can't just disable it without some extra work we are not planning on doing right now. We might do it later tough. In the mean since it seems like we are hitting the other issue and we have found a workaround you can close this as a duplicate. If we eventually try disabling that option and confirm it's indeed the case I will leave a comment.

**Comment by bprashanth** [comment]
A naive question: do we expect minimizing tcp timeouts/retries to help with the problem? or are new connections still going to use the old socket? And is there a way to tune how long the socket takes to expire, similar to how one tunes tcp connections? 

For context I'm seeing this on nfs servers - when the pod servicing the nfs backend is deleted, basic fs operations on the nfs path just hang.

**Comment by aojea** [comment]
I'm not sure about this approach, I think that this is trying to implement is this model where the dataplane is authoritative and decide the traffic based on the API, that is quite different to the one we have implemented in Kubernetes with kube-proxy where the dataplane respect the existing connections and let the applications handle the termination., more on this in https://github.com/cilium/cilium/issues/23761 

If a client does not detect that a backend has left of course it can be sending traffic forever (in UDP), but should not be handled this in the client side?

**Comment by chancez** [comment]
Would it make sense to expose an option to disable socketlb for UDP only as a work around for https://github.com/cilium/cilium/issues/27300?

**Comment by alex-berger** [comment]
Hm, as far as I understand https://github.com/cilium/cilium/pull/25169 only solves half of the problem described in this issue. The problem is [still not solved](https://github.com/cilium/cilium/pull/25169/files#diff-d44ce2cfb3080e97271d04afb131d652a7048a6f2d8aeaf687b3170392c3b185R1626) for pods that are **not** running with `hostNetwork: true`. Therefore, I propose we reopen this issue.

**Comment by aditighag** [comment]
Hey! Here is the follow-up issue for the follow-ups - https://github.com/cilium/cilium/issues/28820. 

If you want to contribute to any of the tasks, please ping me, and I'm happy to provide pointers.
