### ISSUE TITLE
Hop limit exceeded when pinging services via kube-proxy replacement

### ISSUE THREAD

**Issue by gpl** [cilium/cilium#14118]
## Bug report

The expected behavior is that kubeproxyreplacement either responds or forwards icmp to the destination pod.  With kube-proxy, icmp works as expected and we can ping service IPs.

**General Information**

- Cilium version (run `cilium version`)
1.9.0

We're running cilium w/ maglev + dsr.

**How to reproduce the issue**

0. Attempt to ping the service IP and see a hoplimit exceeded error from ICMP
1. Run a traceroute to the service IP
2. Observe ICMP packets loop between routers and workers running kubeproxyreplacement

**Comment by aanm** [comment]
@gpl can you provide a pcap for the ICMP's working with kube-proxy captured in the host with `tcpdump -i any icmp -w icmp.pcap`? Thank you

**Comment by brb** [comment]
@aanm The loop is happening, because the bpf_host attached to the native device cannot find a (externalIP) service, and then the ICMP echo request is being sent back by the node's routing layer (probably via default route). I assume that user's network nodes have the route for the externalIP pointing to the same node, so the packet is sent back to the same node with TTL--. Thus, we have loop until TTL becomes 0.

**Comment by brb** [comment]
> With kube-proxy, icmp works as expected and we can ping service IPs.

@gpl With kube-proxy, do you have the externalIP set to any of the devices? Can you attach two sysdumps - one w/ kube-proxy replacement and one w/ kube-proxy?

**Comment by gpl** [comment]
> > With kube-proxy, icmp works as expected and we can ping service IPs.
> 
> 
> 
> @gpl With kube-proxy, do you have the externalIP set to any of the devices? Can you attach two sysdumps - one w/ kube-proxy replacement and one w/ kube-proxy?

Yes, I'll try to get this to you by the end of day.

I /believe/ kube-proxy attaches serviceIPs to a kube-ipvs0 interface if my memory serves me correctly -- and kube-proxy itself "terminates" the ICMP inseam of forwarding it out.

**Comment by gpl** [comment]
> @gpl can you provide a pcap for the ICMP's working with kube-proxy captured in the host with `tcpdump -i any icmp -w icmp.pcap`? Thank you

https://gist.github.com/gpl/495ca5328ef7462f0876dad6eab4e7ab

Sending the pcap output first because we're having some trouble getting the sysdump to work and need to investigate.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "cilium-sysdump-latest.zip/__main__.py", line 150, in <module>
  File "cilium-sysdump-latest.zip/sysdumpcollector.py", line 534, in collect
  File "cilium-sysdump-latest.zip/sysdumpcollector.py", line 104, in collect_logs
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "cilium-sysdump-latest.zip/sysdumpcollector.py", line 155, in collect_logs_per_pod
KeyError: 'containerStatuses'
```

**Comment by aanm** [comment]
@gpl which IPs correspond to which Pods in that tcpdump capture?

**Comment by brb** [comment]
>  /believe/ kube-proxy attaches serviceIPs to a kube-ipvs0 interface if my memory serves me correctly -- and kube-proxy itself "terminates" the ICMP inseam of forwarding it out.

@gpl Could you try with kube-proxy in the iptables mode?

**Comment by travisghansen** [comment]
@brb what happens to traffic to tcp/udp ports that are not in the service definition? Does that get into a routing loop as well?

I’m a little torn about what the behavior should be here honestly. Even forwarding icmp packets down seems odd unless or until the service definition supports calling out icmp.

**Comment by gpl** [comment]
> @gpl which IPs correspond to which Pods in that tcpdump capture?

  10.204.202.209  is a client outside of kubernetes.  10.3.0.10 is an external service IP.




> > /believe/ kube-proxy attaches serviceIPs to a kube-ipvs0 interface if my memory serves me correctly -- and kube-proxy itself "terminates" the ICMP inseam of forwarding it out.
> 
> @gpl Could you try with kube-proxy in the iptables mode?

ICMP goes into a routing loop w/ iptables mode.

**Comment by travisghansen** [comment]
What are we thinking of doing with this?

**Comment by ArsenyBelorukov** [comment]
Is there any news on this issue? 
Currently, to avoid loop, I add route to nodes, that receive traffic to LB:
`ip r add local 10.120.128.0/19 dev eth0 table local proto 66 scope host`
where 10.120.128.0/19 is LB CIDR range.

**Comment by brb** [comment]
> Is there any news on this issue?

I believe nobody has made any progress on this. I think the proper fix would be to make the LB to answer to the ICMP echo requests instead of forwarding to stack. If you are wiling to work on this, let us know to discuss details (you can also reach us at `#sig-datapath` in the Cilium slack).

**Comment by lx1036** [comment]
i encounter the same case with Cilium 1.11 with kube-proxy replacement free, `kube-proxy-replacement: strict`. 
I get a nginx-demo ClusterIP service ip 200.168.21.227 with two nginx pods `10.216.137.200:80,10.216.137.8:80`.

I can curl service ip 200.168.21.227:80 in NodeA, but can't ping 200.168.21.227, ping pod ip can work. 
I guess the NodeA eth0 eBPF answer the TCP, but not answer ServiceIP ICMP packet?

expect the progress about this case.

**Comment by travisghansen** [comment]
Is metallb strictly necessary? Can’t we just detect it’s a LB ip and base the logic on that?

As for the end result I agree that dropping the packet seems the appropriate thing to do (and would love to see this implemented)!

**Comment by gpl** [comment]
Would dropping the packet also be appropriate for all ports services?

**Comment by brb** [comment]
> Is metallb strictly necessary? Can’t we just detect it’s a LB ip and base the logic on that?

Not necessary. It's enough to to know the LB VIP subnet.

> Would dropping the packet also be appropriate for all ports services?

Did you mean dropping for the LB VIP subnet on any port as above?

**Comment by dylandreimerink** [comment]
> Considering that Cilium when running with the Metal LB is aware of the service CIDR

When MetalLB is used, we announce every service IP that is in use as a /32 to the peers, MetalLB can also be configured with an aggregation length to announce the full service CIDR. But this is just getting the traffic to the nodes, MetalLB is unrelated when in comes to handling traffic once it arrives, so I think it isn't relevant for this discussion.

**Comment by brb** [comment]
> MetalLB is unrelated when in comes to handling traffic once it arrives, so I think it isn't relevant for this discussion.

When Cilium's LB BGP (currently via MetalLB) is enabled, the agent is aware of LB VIP subnets. What we could do is to push those subnets into a BPF map, and then in the datapath we could extend `nodeport_lb4()` to do a lookup in that BPF map if a svc is not found / proto is ICMP. If an entry in the BPF map is found, then drop the request.

**Comment by dylandreimerink** [comment]
> datapath we could extend nodeport_lb4()
Agreed

>  If an entry in the BPF map is found, then drop the request
But don't we want it to work the other way around?

Thinking out loud, when do we want to do with ICMP requests?
* When the destination is one of the IP's assigned to the NIC we receive requests on, we answer or forward it to the stack
* When the destination is a service VIP, answer it (can't NAT it since the ICMP request has no dst port)
* When the destination is a pod IP and traffic is internal(pod-to-pod) just forward the packet to the pod to let it respond.

And in all other cases we drop ICMP. In essence we want to handle ICMP for any IP which also receives some other kind of traffic. 

We already have all of the information since we should not need more info than we need handle TCP/UDP traffic. We have the [HOST_IP](https://github.com/cilium/cilium/blob/master/bpf/node_config.h#L30) via global data, we have service IPs in the [LB4_SERVICES_MAP_V2](https://github.com/cilium/cilium/blob/master/bpf/lib/lb.h#L109)/[LB6_SERVICES_MAP_V2](https://github.com/cilium/cilium/blob/master/bpf/lib/lb.h#L31) maps and pod IPs in the endpoints map.

I think the only hurdle is that the LB maps are indexed by IP+Port, not just IP. So we would have to add an additional entry into the LB maps(IP + port 0) or maintain a separate map.

In any case, it should not be the responsibility of the BGP feature to populate maps with information which is available via the api-server. Feels like a responsibility for the watchers that also populate the LB maps.

**Comment by brb** [comment]
> Thinking out loud, when do we want to do with ICMP requests?

We could support ICMP Echo to LoadBalancer VIP. This could be used by user health checks, i.e. whether a LoadBalancer service has been plumbed yet.

**Comment by brb** [comment]
> In any case, it should not be the responsibility of the BGP feature to populate maps with information which is available via the api-server. Feels like a responsibility for the watchers that also populate the LB maps.

Yeah, makes sense, since the LB VIP will be eventually available to the watcher, and thus the interested parties.

**Comment by travisghansen** [comment]
IMO icmp should be dropped until the service spec supports defining icmp and it’s been explicitly set/enabled on the service.

**Comment by travisghansen** [comment]
Unstale.

**Comment by anthr76** [comment]
Not stale

**Comment by YutaroHayakawa** [comment]
Another duplicated issue https://github.com/cilium/cilium/issues/28458. Let me reopen this since this is still the case.

**Comment by JunPark** [comment]
Yes, even with a fairly recent one of 1.14.3, I hit the same issue of looping ICMP packets with kubeproxyreplacement, which is  causing confusions around services' availability.

**Comment by e3b0c442** [comment]
Confirming this is still the case with 1.15.0, this caused some unnecessarily prolonged troubleshooting of what was ultimately an issue with the Ingress resource.

**Comment by dalcorta** [comment]
V 1.15.1 Also has the same issue

**Comment by zviratko** [comment]
How is this still an issue? Not only should LB respond to ICMP Echo by default (it's just good manners... and RFC), but also having a "default" routing loop makes it an attractive target for denial of service.
I believe the node hosting the LB VIP should simply own the IP, so that whatever doesn't match the Cilium BPF datapath gets handled by the networking stack/firewall, not forward it back.

**Comment by dmitry-sinina** [comment]
There is also other problem related to ICMP processing - ICMP packets with type "fragmentation needed" to service IP not delivered to pods so pmtud mechanism doesn't work.  So looks like droping all ICMP packets to service IP it is bad idea.

**Comment by centromere** [comment]
I am currently experiencing this issue. In addition to echos looping, ICMPv6 packet-too-big messages are also looping, leading to service unavailability for certain users.

**Comment by abctaylor** [comment]
This is a massive time waster for sysadmins/engineers ("hmm do we have a routing loop in our upstream router?" came to mind and took many hours to arrive here). I also agree on the DoS comment that it could cause some sort of ping storm.

**Comment by aep** [comment]
@dmitry-sinina 
> Currently I manually added blackhole route for services external IP range

that seems to also prevent cilium from responding, not sure if this workaround is valid anymore.

> ip r add local 10.120.128.0/19 dev eth0 table local proto 66 scope host

same for this.  this routes the traffic to the linux host, so the cilium service no longer responds.


the only workaround i found is making an nftables ingress rule that specifically filters traffic not intended for the service, 
but thats like ... whats the point of k8s if you need to hand make nftables rules?

**Comment by dmitry-sinina** [comment]
@aep blackhole route prevent routing loop. But path MTU discovery mechanism still broken because cilium not processing correctly ICMP "fragmentation needed" packets to service IP.

**Comment by cunningr-cisco** [comment]
I also see this behaviour for traffic to ports that aren't configured as part of the service.  The packets just loop inside the host until the TTL expires.

**Comment by rivolity** [comment]
We have the same issue in our Cluster, we cant Ping LB provisionned by L2 or BGP.

**Comment by wisla28** [comment]
Same issue here

**Comment by vjeko** [comment]
Five years and still nothing? Wow.

**Comment by nileshp87** [comment]
Wow, just spent literal days debugging this issue, trying to ping. This should at least be obviously documented for people that expect an advertised /32 to respond to ping.

**Comment by JesperBeltman** [comment]
Thanks for the suggestions everyone, the workarounds work. But indeed this should be fixed at the source.

**Comment by pisoj** [comment]
Still a problem on 1.20.1. This should not be happening, it's a huge time waster to debug and never mentioned in the documentation.

For anyone facing the same issue, I created a little Ansible playbook that sets up every Service IP as a loopback. This way the kernel will handle everything not handled by Cilium (including ICMP). I also added two firewall rules to prevent services running on the host (like the Kubernetes API server) from being accessible via these addresses. This makes the routing loop go away.

```yaml
- hosts: kube_nodes
  become: yes
  vars:
    service_cidr_ipv6: fd18:c15c:9c11::/112 # Internal ServiceIP pool
    service_cidr_ipv4: 10.218.0.0/16 # Internal ServiceIP pool
    load_balancer_pool_ipv6: 2a14:c380:c60:1100::/64 # Must match CiliumLoadBalancerIPPool
    load_balancer_pool_ipv4: 44.30.64.160/27 # Must match CiliumLoadBalancerIPPool
  tasks:
    - name: Configure Service IPs as loopbacks so Kernel can handle ICMP
      copy:
        dest: /etc/systemd/network/5-lo.network
        content: |
          [Match]
          Name=lo

          [Network]
          Address={{ service_cidr_ipv6 }}
          Address={{ load_balancer_pool_ipv6 }}
          Address={{ service_cidr_ipv4 }}
          Address={{ load_balancer_pool_ipv4 }}
    - name: Reload systemd-network
      shell:
        cmd: networkctl reload
    - name: Install apt dependencies
      apt:
        name:
          - nftables
    - name: Configure nftables lists of service addresses
      blockinfile:
        path: /etc/nftables.conf
        marker_begin: begin_global_variables
        marker_end: end_global_variables
        prepend_newline: true
        append_newline: true
        insertafter: flush ruleset
        block: |
          define SERVICE_LOOPBACKS_IPV6 = { {{ service_cidr_ipv6 }}, {{ load_balancer_pool_ipv6 }} }
          define SERVICE_LOOPBACKS_IPV4 = { {{ service_cidr_ipv4 }}, {{ load_balancer_pool_ipv4 }} }
    - name: Configure nftables
      blockinfile:
        path: /etc/nftables.conf
        marker_begin: begin_input_rules
        marker_end: end_input_rules
        prepend_newline: true
        append_newline: true
        insertafter: type filter hook input priority filter;
        block: |
          # Cilium does not handle ICMP packets on Service IPs, so the kernel will pick them up
          # However, everything other than ICMP needs to be firewalled off since, otherwise, services running on the host
          # (like the Kubernetes API server) will be accessible via these IPs
          ip daddr $SERVICE_LOOPBACKS_IPV4 ip protocol != icmp reject
          ip6 daddr $SERVICE_LOOPBACKS_IPV6 ip6 nexthdr != icmpv6 reject
    - name: Start and enable nftables
      systemd_service:
        name: nftables.service
        enabled: true
        state: restarted
```

In the end, the systemd-networkd config ends up looking like this:
```ini
$ cat /etc/systemd/network/5-lo.network 

[Match]
Name=lo

[Network]
Address=fd18:c15c:9c11::/112
Address=2a14:c380:c60:1100::/64
Address=10.218.0.0/16
Address=44.30.64.160/27
```

And the nftables ruleset like this:
```ruby
$ cat /etc/nftables.conf 

#!/usr/sbin/nft -f
flush ruleset

define SERVICE_LOOPBACKS_IPV6 = { fd18:c15c:9c11::/112, 2a14:c380:c60:1100::/64 }
define SERVICE_LOOPBACKS_IPV4 = { 10.218.0.0/16, 44.30.64.160/27 }

table inet filter {
        chain input {
                type filter hook input priority filter;

                ip daddr $SERVICE_LOOPBACKS_IPV4 ip protocol != icmp reject
                ip6 daddr $SERVICE_LOOPBACKS_IPV6 ip6 nexthdr != icmpv6 reject
        }
        chain forward {
                type filter hook forward priority filter;
        }
        chain output {
                type filter hook output priority filter;
        }
}
```
