### ISSUE TITLE
Cilium does not recognise identity thus got policy denied

### ISSUE THREAD

**Issue by alex1989hu** [cilium/cilium#14284]
## Bug report

Possible related to https://github.com/cilium/cilium/issues/13240

I don't know what triggers it, but after a while Cilium starts to drop packages with `Policy denied` (see `CNP` later.). Everything goes to green if I remove the `CNP`. Pod deletion or kill also does not help it.

I see in `hubble` that a Pod called `argocd-redis` considered as world/no category from multiple pods within the same namespace. Thus, all packages dropped `Policy denied`. 

>Timestamp
2020-12-04T16:50:17.057Z
Verdict
dropped
Drop reason
Policy denied
Traffic direction
egress
TCP flags
SYN
Source pod
argocd-repo-server-75ff7d8b4c-l5k2v
Source identity
18696
Source labels
name=argocd-repo-server
io.cilium.k8s.policy.cluster=default
io.cilium.k8s.policy.serviceaccount=default
namespace=argocd
Source IP
10.0.4.163
Destination pod
argocd-redis-678b9dd489-xlzw9
Destination identity
52549
Destination IP
10.0.0.237
Destination port
6379

```bash
$ kubectl -n argocd describe pod argocd-redis-678b9dd489-xlzw9
Name:         argocd-redis-678b9dd489-xlzw9
Namespace:    argocd
Priority:     0
Node:         bucaw250-9/10.135.250.9
Start Time:   Fri, 04 Dec 2020 16:39:58 +0000
Labels:       app.kubernetes.io/name=argocd-redis
              pod-template-hash=678b9dd489
Annotations:  kubernetes.io/psp: privileged
Status:       Running
IP:           10.0.0.237
IPs:
  IP:           10.0.0.237
Controlled By:  ReplicaSet/argocd-redis-678b9dd489
...
```

![ciliumv190world](https://user-images.githubusercontent.com/10764100/101199544-53c5c980-3665-11eb-8396-897a763956b7.PNG)

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-application-controller-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-application-controller
    ingress:
    - fromEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-redis
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-redis
      - matchLabels:
          "app.kubernetes.io/name": argocd-repo-server
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
    - toEntities:
      - remote-node
      - world

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-dex-server-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-dex-server
    ingress:
    - fromEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-server
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
    - toEntities:
      - remote-node
      - world

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-repo-server-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-repo-server
    ingress:
    - fromEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-application-controller
      - matchLabels:
          "app.kubernetes.io/name": argocd-server
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-redis
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
    - toEntities:
      - world

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-redis-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-redis
    ingress:
    - fromEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-application-controller
      - matchLabels:
          "app.kubernetes.io/name": argocd-repo-server
      - matchLabels:
          "app.kubernetes.io/name": argocd-server
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-application-controller
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns

---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "argocd-server-policy"
  namespace: argocd
specs:
  - endpointSelector:
      matchLabels:
        "app.kubernetes.io/name": argocd-server
    ingress:
    - fromEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": projectcontour
          app: envoy
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": argocd-image-updater
          "app.kubernetes.io/name": argocd-image-updater
    - fromEntities:
      - remote-node
    egress:
    - toEndpoints:
      - matchLabels:
          "app.kubernetes.io/name": argocd-dex-server
      - matchLabels:
          "app.kubernetes.io/name": argocd-redis
      - matchLabels:
          "app.kubernetes.io/name": argocd-repo-server
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": projectcontour
          app: envoy
    - toEntities:
      - remote-node
      - world
```

**General Information**

- Cilium version (run `cilium version`)
> Client: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
Daemon: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
- Kernel version (run `uname -a`)
> Linux bucaw250-8 5.9.3-talos #1 SMP Fri Nov 13 16:04:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
> Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
N/A
- Generate and upload a system zip:
Attached
[cilium-sysdump-20201204-191108.zip](https://github.com/cilium/cilium/files/5644589/cilium-sysdump-20201204-191108.zip)

**How to reproduce the issue**
Do not know what triggers it.

**Comment by aanm** [comment]
@alex1989hu please upgrade to 1.9.1 as this was fixed by https://github.com/cilium/cilium/pull/14090. Thanks

**Comment by alex1989hu** [comment]
@aanm upgraded to `1.9.1 `, issue is still there, please check the attached sysdump
[cilium-sysdump-20201209-153320.zip](https://github.com/cilium/cilium/files/5666579/cilium-sysdump-20201209-153320.zip)

**Comment by aanm** [comment]
@alex1989hu which identity is it in that sysdump?

**Comment by alex1989hu** [comment]
Based on Slack discussion, reproduced the issue again. The difference is that it became fixed, somehow "automagically" but here is the proof that is I got `deny` verdicts.

> Timestamp
2020-12-10T11:24:36.656Z
Verdict
dropped
Drop reason
Policy denied
Traffic direction
egress
TCP flags
ACK
Source pod
argocd-repo-server-75ff7d8b4c-7jtf5
Source identity
13646
Source labels
name=argocd-repo-server
io.cilium.k8s.namespace.labels.instance=argocd-app
io.cilium.k8s.policy.cluster=default
io.cilium.k8s.policy.serviceaccount=default
namespace=argocd
Source IP
10.0.0.221
Destination pod
argocd-redis-678b9dd489-cgdcg
Destination identity
14267
Destination IP
10.0.4.162
Destination port
6379


> Timestamp
2020-12-10T11:24:35.944Z
Verdict
dropped
Drop reason
Policy denied
Traffic direction
egress
TCP flags
SYN
Source pod
argocd-application-controller-94656465d-8x7hw
Source identity
16570
Source labels
name=argocd-application-controller
io.cilium.k8s.namespace.labels.instance=argocd-app
io.cilium.k8s.policy.cluster=default
io.cilium.k8s.policy.serviceaccount=argocd-application-controller
namespace=argocd
Source IP
10.0.0.155
Destination pod
argocd-redis-678b9dd489-cgdcg
Destination identity
14267
Destination IP
10.0.4.162
Destination port
6379

> Timestamp
2020-12-10T11:24:29.529Z
Verdict
dropped
Drop reason
Policy denied
Traffic direction
ingress
TCP flags
ACK
Source pod
argocd-application-controller-94656465d-8x7hw
Source identity
27019
Source IP
10.0.0.155
Destination pod
argocd-repo-server-75ff7d8b4c-hc5pq
Destination identity
40643
Destination labels
name=argocd-repo-server
io.cilium.k8s.policy.cluster=default
io.cilium.k8s.policy.serviceaccount=default
namespace=argocd
Destination IP
10.0.2.33
Destination port
8081

> Timestamp
2020-12-10T11:24:26.668Z
Verdict
dropped
Drop reason
Policy denied
Traffic direction
ingress
TCP flags
ACK
Source pod
argocd-application-controller-94656465d-8x7hw
Source identity
27019
Source IP
10.0.0.155
Destination pod
argocd-redis-678b9dd489-cgdcg
Destination identity
20496
Destination labels
name=argocd-redis
io.cilium.k8s.policy.cluster=default
io.cilium.k8s.policy.serviceaccount=default
namespace=argocd
Destination IP
10.0.4.162
Destination port
6379

Some Kubernetes Pod Describe:

```bash
$ kubectl -n argocd describe pod argocd-application-controller-94656465d-8x7hw
Name:         argocd-application-controller-94656465d-8x7hw
Namespace:    argocd
Priority:     0
Node:         bucaw250-9/10.135.250.9
Start Time:   Wed, 09 Dec 2020 15:32:52 +0100
Labels:       app.kubernetes.io/name=argocd-application-controller
              pod-template-hash=94656465d
Annotations:  kubernetes.io/psp: privileged
Status:       Running
IP:           10.0.0.155
IPs:
  IP:           10.0.0.155

$ kubectl -n argocd describe pod argocd-redis-678b9dd489-cgdcg
Name:         argocd-redis-678b9dd489-cgdcg
Namespace:    argocd
Priority:     0
Node:         bucaw250-8/10.135.250.8
Start Time:   Wed, 09 Dec 2020 15:32:50 +0100
Labels:       app.kubernetes.io/name=argocd-redis
              pod-template-hash=678b9dd489
Annotations:  kubernetes.io/psp: privileged
Status:       Running
IP:           10.0.4.162
IPs:
  IP:           10.0.4.162

 $ kubectl -n argocd describe pod argocd-repo-server-75ff7d8b4c-7jtf5
Name:         argocd-repo-server-75ff7d8b4c-7jtf5
Namespace:    argocd
Priority:     0
Node:         bucaw250-9/10.135.250.9
Start Time:   Wed, 09 Dec 2020 15:32:59 +0100
Labels:       app.kubernetes.io/name=argocd-repo-server
              pod-template-hash=75ff7d8b4c
Annotations:  kubernetes.io/psp: privileged
Status:       Running
IP:           10.0.0.221
IPs:
  IP:           10.0.0.221
```

Attached screenshot:

![hubble-deny-verdicts-again](https://user-images.githubusercontent.com/10764100/101767465-88fa6d80-3ae4-11eb-87f8-a2a6f976ab07.png)

Attached sysdump:

[cilium-sysdump-20201210-122657.zip](https://github.com/cilium/cilium/files/5672389/cilium-sysdump-20201210-122657.zip)

**Comment by alex1989hu** [comment]
Update, it started to drop again:
> Flow Details
Timestamp
2020-12-10T12:01:10.208Z
Verdict
dropped
Drop reason
Policy denied
Traffic direction
ingress
TCP flags
ACK
Source pod
argocd-application-controller-94656465d-8x7hw
Source identity
27019
Source IP
10.0.0.155
Destination pod
argocd-repo-server-75ff7d8b4c-mstrm
Destination identity
40643
Destination labels
name=argocd-repo-server
io.cilium.k8s.policy.cluster=default
io.cilium.k8s.policy.serviceaccount=default
namespace=argocd
Destination IP
10.0.4.89
Destination port
8081

**Comment by aanm** [comment]
@alex1989hu this happens because the pod labels change and therefore the identity changes as well until this new identity is propagated to all nodes, they will show as "denied".

**Comment by alex1989hu** [comment]
Could you please send me the label changes *(from -> to)*?

**Comment by aanm** [comment]
```
cilium-j52fm-20201210-122706.log:2020-12-10T11:24:26.984892297Z level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=34 desiredPolicyRevision=34 endpointID=241 identity=14267 ipv4= ipv6= k8sPodName=/ subsys=endpoint
cilium-j52fm-20201210-122706.log:2020-12-10T11:24:31.545328939Z level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=34 desiredPolicyRevision=34 endpointID=241 identity=20496 identityLabels="k8s:app.kubernetes.io/name=argocd-redis,k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/instance=argocd-app,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=argocd" ipv4= ipv6= k8sPodName=/ oldIdentity=14267 subsys=endpoint
cilium-operator-5666849b6d-mpwpc-20201210-122707.log:2020-12-09T15:07:36.158793508Z level=info msg="Garbage collected identity" identity=14267 subsys=cilium-operator-generic
```

**Comment by alex1989hu** [comment]
> ```
> cilium-j52fm-20201210-122706.log:2020-12-10T11:24:26.984892297Z level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=34 desiredPolicyRevision=34 endpointID=241 identity=14267 ipv4= ipv6= k8sPodName=/ subsys=endpoint
> cilium-j52fm-20201210-122706.log:2020-12-10T11:24:31.545328939Z level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=34 desiredPolicyRevision=34 endpointID=241 identity=20496 identityLabels="k8s:app.kubernetes.io/name=argocd-redis,k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/instance=argocd-app,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=argocd" ipv4= ipv6= k8sPodName=/ oldIdentity=14267 subsys=endpoint
> cilium-operator-5666849b6d-mpwpc-20201210-122707.log:2020-12-09T15:07:36.158793508Z level=info msg="Garbage collected identity" identity=14267 subsys=cilium-operator-generic
> ```

It can not figure out what changed here *(from->to)*. 

Anyway, the labels you pasted is always the same, it does not contain any version, revision, datetime , number etc. It contains namespace, the label we are filter (see the initial post) and cilium related things like `k8s:io.cilium.k8s.policy.cluster=default`.

I am pretty sure that I do not change namespace,`"app.kubernetes.io/name"` label and options which side-effect is to change any `k8s:io.cilium.*` label.

It looks like something neat is happening here. Thoughts?

**Comment by aanm** [comment]
The namespace `argocd` has added a new label: `app.kubernetes.io/instance=argocd-app`

**Comment by alex1989hu** [comment]
After applying label to `argocd` and a long enduring test I could say this issue can be closed 

Thank you @aanm
