### ISSUE TITLE
Host firewall network policies don't work on L3 interfaces (eg. host WireGuard)

### ISSUE THREAD

**Issue by rpthms** [cilium/cilium#17636]
## Bug report

**General Information**

- Cilium version: 1.10.5
- Kernel version: 5.11.0-37-generic (Ubuntu 20.04)
- Orchestration system version in use: Kubernetes 1.21.5

**How to reproduce the issue**

I have setup a 2 node cluster on Hetzner where both the nodes are connected to each other over a WireGuard tunnel.

The network topology looks like this:

```

   -------------------------------------                                           ------------------------------------
   |                                   |                                           |                                  |
   |      cilium-master                |                                           |      cilium-worker               |
   |                                   |                                           |                                  |
   |   eth0: 49.12.228.255             |        WireGuard tunnel running at        |   eth0: 49.12.220.252            |
   |   wg0: 172.27.200.1               | ------------------------------------------|   wg1: 172.27.201.2              |
   |   wg1: 172.27.201.1               |          port 24224 on each side          |                                  |
   |                                   |                                           |                                  |
   |   Node labels:                    |                                           |   Node labels:                   |         
   |   - k8s-node-type: cloud          |                                           |   - k8s-node-type: cloud         | 
   |   - k8s-hostname: cilium-master   |                                           |   - k8s-hostname: cilium-worker  |
   |                                   |                                           |                                  |
   -------------------------------------                                           ------------------------------------

cilium-worker and cilium-master are connected to each other using the `wg1` interface. `wg0` isn't
connected to any peer right now, but it's IP address is being used as cilium-master's node IP and
the API server's IP.
```
1. Apply a Cilium Clusterwide Network Policy to only allow SSH and WireGuard packets on both the nodes.
WireGuard is running on port 24224 on both sides.
```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-ssh-and-wireguard"
spec:
  description: "Allow SSH and WireGuard"
  nodeSelector:
    matchLabels:
      k8s-node-type: cloud
  ingress:
    - fromEntities:
        - world 
      toPorts:
        - ports:
            - port: "22"
              protocol: TCP
            - port: "24224"
              protocol: UDP
```

2. Run `cilium monitor` on the control plane node.

3. When accessing the kube-apiserver from cilium-worker using the cilium-master's public IP, we get a "Policy denied"
    message as expected.
```
root@cilium-worker:~# curl -v 'https://49.12.228.255:6443'
*   Trying 49.12.228.255:6443...
* TCP_NODELAY set
.
.
.
Eventually times out
```
```
Policy verdict log: flow 0x0 local EP ID 33, remote ID world, proto 6, ingress, action deny, match none, 49.12.220.252:45898 -> 49.12.228.255:6443 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 0, identity world->unknown: 49.12.220.252:45898 -> 49.12.228.255:6443 tcp SYN
```

4. But when accessing the kube-apiserver from cilium-worker using the WireGuard interface's IP, we get a "UnknownEthernetType" message in the monitor logs and the packet gets denied.

```
root@cilium-worker:~# curl -v 'https://172.27.200.1:6443'
*   Trying 172.27.200.1:6443...
* TCP_NODELAY set
.
.
.
Eventually times out
```
```
Policy verdict log: flow 0x0 local EP ID 33, remote ID remote-node, proto 6, ingress, action deny, match none, 40:00:40:06:74:8b -> 45:00:00:3c:dc:f5 UnknownEthernetType
xx drop (Policy denied) flow 0x0 to endpoint 0, identity world->unknown: 40:00:40:06:74:8b -> 45:00:00:3c:dc:f5 UnknownEthernetType
```

5. Lets add a CCNP to allow traffic to the kube-apiserver from the world (Just an example, don't worry :smile:).

```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "kube-apiserver-world"
spec:
  description: "Allow connections to the kube-apiserver from the world"
  nodeSelector:
    matchLabels:
      k8s-hostname: cilium-master
  ingress:
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
```

6. Accessing the kube-apiserver using the cilium-master's public IP from the cilium-worker now works as expected.

```
root@cilium-worker:~# curl -v 'https://49.12.228.255:6443'
*   Trying 49.12.228.255:6443...
* TCP_NODELAY set
* Connected to 49.12.228.255 (49.12.228.255) port 6443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

But accessing the kube-apiserver using the cilium-master's WireGuard interface IP, still fails and I keep getting
the UnknownEthernetType log messages.

```
root@cilium-worker:~# curl -v 'https://172.27.200.1:6443'
*   Trying 172.27.200.1:6443...
* TCP_NODELAY set
.
.
.
Eventually times out
```

```
Policy verdict log: flow 0x0 local EP ID 33, remote ID remote-node, proto 6, ingress, action deny, match none, 40:00:40:06:17:2d -> 45:00:00:3c:3a:54 UnknownEthernetType
xx drop (Policy denied) flow 0x0 to endpoint 0, identity world->unknown: 40:00:40:06:17:2d -> 45:00:00:3c:3a:54 UnknownEthernetType
```

**Additional information**

Because of this issue, after applying any host-firewall policy, the cilium-worker's kubelet eventually stops being able to talk to the kube-apiserver and the worker eventually enters a NotReady state. Everything becomes fine once I delete all host-firewall policies, of course.

```
root@cilium-master:~# kubectl get pods -o wide -A
NAMESPACE      NAME                                      READY   STATUS        RESTARTS   AGE   IP             NODE            NOMINATED NODE   READINESS GATES
cert-manager   cert-manager-848f547974-r5qb8             1/1     Terminating   0          41m   10.172.1.173   cilium-worker   <none>           <none>
cert-manager   cert-manager-848f547974-xrz2b             0/1     Pending       0          19m   <none>         <none>          <none>           <none>
cert-manager   cert-manager-cainjector-54f4cc6b5-6kq28   1/1     Terminating   0          41m   10.172.1.159   cilium-worker   <none>           <none>
cert-manager   cert-manager-cainjector-54f4cc6b5-9j4vm   0/1     Pending       0          19m   <none>         <none>          <none>           <none>
cert-manager   cert-manager-webhook-7c9588c76-dnkpz      0/1     Pending       0          19m   <none>         <none>          <none>           <none>
cert-manager   cert-manager-webhook-7c9588c76-p25xw      1/1     Terminating   0          41m   10.172.1.150   cilium-worker   <none>           <none>
kube-system    cilium-5ps4l                              1/1     Running       0          47h   172.27.201.2   cilium-worker   <none>           <none>
kube-system    cilium-operator-57d45855b-dwqxn           1/1     Running       0          47h   172.27.200.1   cilium-master   <none>           <none>
kube-system    cilium-p7sg2                              1/1     Running       0          47h   172.27.200.1   cilium-master   <none>           <none>
kube-system    coredns-558bd4d5db-cjkll                  1/1     Running       0          47h   10.172.0.168   cilium-master   <none>           <none>
kube-system    coredns-558bd4d5db-s4hw7                  1/1     Running       0          47h   10.172.0.182   cilium-master   <none>           <none>
kube-system    etcd-cilium-master                        1/1     Running       0          47h   172.27.200.1   cilium-master   <none>           <none>
kube-system    hubble-relay-84846948c7-m74kd             0/1     Pending       0          19m   <none>         <none>          <none>           <none>
kube-system    hubble-ui-668698dfc8-fhn7q                0/3     Pending       0          19m   <none>         <none>          <none>           <none>
kube-system    hubble-ui-668698dfc8-qgnfn                3/3     Terminating   0          41m   10.172.1.116   cilium-worker   <none>           <none>
kube-system    kube-apiserver-cilium-master              1/1     Running       0          47h   172.27.200.1   cilium-master   <none>           <none>
kube-system    kube-controller-manager-cilium-master     1/1     Running       0          47h   172.27.200.1   cilium-master   <none>           <none>
kube-system    kube-scheduler-cilium-master              1/1     Running       0          47h   172.27.200.1   cilium-master   <none>           <none>
monitor        prometheus-operator-54c4665c6b-jx8l8      0/1     Pending       0          19m   <none>         <none>          <none>           <none>
monitor        prometheus-operator-54c4665c6b-pc2pz      1/1     Terminating   0          41m   10.172.1.91    cilium-worker   <none>           <none>
```

```
root@cilium-master:~# kubectl get nodes
NAME            STATUS     ROLES                  AGE   VERSION
cilium-master   Ready      control-plane,master   47h   v1.21.5
cilium-worker   NotReady   <none>                 47h   v1.21.5
```

**Comment by brb** [comment]
@rpthms Seems that the datapath is not aware that the wg device is L3, although it should. Could you share `cilium status --verbose` output?

**Comment by rpthms** [comment]
@brb Here's the output of `cilium status --verbose` on the cilium-master

```
root@cilium-master:/home/cilium# cilium status --verbose
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.21 (v1.21.5) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumLocalRedirectPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [lan 192.168.168.192 2a01:4f8:c2c:b750::9472, wan 49.12.228.255 2a01:4f8:c2c:b750::9472, wg-k8s-admin 172.27.255.1 2a01:4f8:c2c:b750::9472, wg-k8s0 172.27.200.1 fd00::90de:200:1 (Direct Routing), wg-k8s1 172.27.201.1 fd00::90de:201:1]
Cilium:                 Ok   1.10.5 (v1.10.5-b0836e8)
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPAM:                   IPv4: 4/254 allocated from 10.172.0.0/24, IPv6: 4/65534 allocated from fd00::ffff:0:0/112
Allocated addresses:
  10.172.0.168 (kube-system/coredns-558bd4d5db-cjkll)
  10.172.0.182 (kube-system/coredns-558bd4d5db-s4hw7)
  10.172.0.247 (router)
  10.172.0.43 (health)
  fd00::ffff:0:444c (health)
  fd00::ffff:0:a903 (kube-system/coredns-558bd4d5db-cjkll)
  fd00::ffff:0:ab99 (router)
  fd00::ffff:0:fb02 (kube-system/coredns-558bd4d5db-s4hw7)
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           BPF (ip-masq-agent)   [lan, wan, wg-k8s-admin, wg-k8s0, wg-k8s1]   172.27.192.0/18 [IPv4: Enabled, IPv6: Enabled]
Clock Source for BPF:   jiffies               [250 Hz]
Controller Status:      27/27 healthy
  Name                                  Last success    Last error   Count   Message
  bpf-map-sync-cilium_lxc               3s ago          never        0       no error   
  cilium-health-ep                      35s ago         never        0       no error   
  dns-garbage-collector-job             45s ago         never        0       no error   
  endpoint-1279-regeneration-recovery   never           never        0       no error   
  endpoint-2839-regeneration-recovery   never           never        0       no error   
  endpoint-3098-regeneration-recovery   never           never        0       no error   
  endpoint-33-regeneration-recovery     never           never        0       no error   
  endpoint-gc                           3m46s ago       never        0       no error   
  k8s-heartbeat                         11s ago         never        0       no error   
  mark-k8s-node-as-available            17h58m37s ago   never        0       no error   
  metricsmap-bpf-prom-sync              6s ago          never        0       no error   
  resolve-identity-1279                 3m36s ago       never        0       no error   
  resolve-identity-2839                 3m36s ago       never        0       no error   
  resolve-identity-3098                 3m36s ago       never        0       no error   
  resolve-identity-33                   3m37s ago       never        0       no error   
  sync-endpoints-and-host-ips           35s ago         never        0       no error   
  sync-lb-maps-with-k8s-services        17h58m37s ago   never        0       no error   
  sync-policymap-1279                   30s ago         never        0       no error   
  sync-policymap-2839                   30s ago         never        0       no error   
  sync-policymap-3098                   30s ago         never        0       no error   
  sync-policymap-33                     30s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (1279)     12s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (2839)     12s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (3098)     12s ago         never        0       no error   
  sync-to-k8s-ciliumendpoint (33)       3s ago          never        0       no error   
  template-dir-watcher                  never           never        0       no error   
  update-k8s-node-annotations           17h58m45s ago   never        0       no error   
Proxy Status:   No managed proxy redirect
Hubble:         Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 12.23   Metrics: Disabled
KubeProxyReplacement Details:
  Status:                Strict
  Socket LB Protocols:   TCP, UDP
  Devices:               lan 192.168.168.192 2a01:4f8:c2c:b750::9472, wan 49.12.228.255 2a01:4f8:c2c:b750::9472, wg-k8s-admin 172.27.255.1 2a01:4f8:c2c:b750::9472, wg-k8s0 172.27.200.1 fd00::90de:200:1 (Direct Routing), wg-k8s1 172.27.201.1 fd00::90de:201:1
  Mode:                  SNAT
  Backend Selection:     Random
  Session Affinity:      Enabled
  XDP Acceleration:      Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767) 
  - LoadBalancer:   Enabled 
  - externalIPs:    Enabled 
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   65536
  TCP connection tracking       131072
  Endpoint policy               65535
  Events                        2
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           131072
  Neighbor table                131072
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        2
  Sockmap                       65535
  Sock reverse NAT              65536
  Tunnel                        65536
Encryption:                   Disabled
Cluster health:               1/2 reachable   (2021-10-19T12:07:33Z)
  Name                        IP              Node          Endpoints
  cilium-master (localhost)   172.27.200.1    reachable     reachable
  cilium-worker               172.27.201.2    unreachable   unreachable
```

**Comment by brb** [comment]
> But accessing the kube-apiserver using the cilium-master's WireGuard interface IP, still fails and I keep getting
the UnknownEthernetType log messages.

Do you get those messages on cilium-worker or cilium-master? Also, could you try setting `nodePort.directRoutingDevice=wg1`?

**Comment by farcaller** [comment]
I'm facing a very similar issue with tailscale (which uses L3 interface as well, a variant of wireguard), getting `UnknownEthernetType` errors when I try to connect to the service-ip over the tailscale network.

**Comment by farcaller** [comment]
Actually never mind, my issue was fixed with `bpf.lbExternalClusterIP=true`

**Comment by erikschul** [comment]
@farcaller Can you provide your configuration details? I'm struggling with this, and unable to get it work for weeks now.
Using `lbExternalClusterIP` doesn't solve it for me. Do you have other settings, like `devices` etc.?
Can you provide your helm values?
Do you run wireguard server natively on the node, or in a pod?

https://github.com/cilium/cilium/issues/27758

**Comment by farcaller** [comment]
@erikschul I don't have the cluster config at hand, but it's a tailscale server running on the node. There are no `devices` settings, if I remember it correctly.

**Comment by erikschul** [comment]
@farcaller Ok, thanks anyway :)

**Comment by julianwiedmann** [comment]
This has been open for a long time, and things have changed a lot since then. I think it's worth a re-test :).

(also adjusting the labels, as it's about L3 vs HostFW interaction)

**Comment by m00nwtchr** [comment]
Still having what appears to be the same issue (also using Tailscale). Though for me the `fromEntities: cluster` ingress policy works fine, but trying to also enable other tailscale devices to access the kube-apiserver fails with the UnknownEthernetType message.
```
spec:
  description: ''
  ingress:
    - fromEntities:
      - cluster
    - fromCIDR:
        - 100.64.0.0/10
        - fd7a:115c:a1e0::/48
      toPorts:
        - ports:
            - port: '6433'
              protocol: TCP
    - toPorts:
        - ports:
            - port: '41641'
              protocol: UDP
            - port: '22'
              protocol: TCP
    - icmps:
        - fields:
            - family: IPv4
              type: EchoRequest
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: 'true'
```

**Comment by smagnani96** [comment]
The `UnknownEthernetType` is potentially due to https://github.com/cilium/cilium/issues/37095, for which a fix should be soon in place.
Then, we plan also to move to dedicated `cil_from_wireguard` with https://github.com/cilium/cilium/issues/33676.
While doing that, I'll try to test this and see what is missing 🤞
