### ISSUE TITLE
Cilium agent drops all DNS requests host is trying to make

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1846]
"I've been having a couple issues and was hoping to get a push in the right direction if possible. I'm attempting to switch one of our beta kubernetes clusters to cilium, in the hopes that we get comfortable enough to use it in production. The problem I am having is that the cilium agent is dropping all dns requests the host is trying to make. This is making it so that the cilium container never reaches a ready state (as api comunication is not working)."
Environment information:
```
OS: CoreOS 1409.7.0
Kubernetes version: 1.6.4
Cilium version: latest stable
Pod CIDR: 10.2.0.0/24
Node CIDR: 10.8.0.0/24
Monitor output:
Error: xx drop (No tunnel/encapsulation endpoint), to endpoint 0, identity 0->0: <host ip>:45040 -> <ip from resolv.conf>:53 udp
```

**Comment by tgraf** [comment]
Leftover work: Node routes need to be added individually to allow for unused CIDR space to be used by external network endpoints

**Comment by enzian** [comment]
Hey @tgraf, just saw, that this was addressed, but I think I've hit a similar issue:

I have kube-dns instances running in my cluster, but all UDP packages to these pods go missing:

    forward (Policy), at To stack, to endpoint 0, identity 267->0: 10.205.85.133:48223 -> 10.204.33.179:53 udp

on the other side, nothing comes in!
Can you give me a hint what could be going wrong in my setup?

**Comment by tgraf** [comment]
> on the other side, nothing comes in!

Are you running any non-standard options? Does the problem go away if you `kubectl delete pod` the kube-dns to force them getting restarted?

The issue addressed in this PR was the use of non-cluster IPs inside of the Kubernetes pod CIDR.

**Comment by enzian** [comment]
> The issue addressed in this PR was the use of non-cluster IPs inside of the Kubernetes pod CIDR.
Ah - mine is not ;-)

> Are you running any non-standard options? 
No - except ETCDs endpoints...

> Does the problem go away if you kubectl delete pod the kube-dns to force them getting restarted?
I forced a restart of all containers involved (kube-dns pods, and busybox) - the problem persists though!

I also do not see anything dropped on the agent that  should receive the package!

**Comment by tgraf** [comment]
> I also do not see anything dropped on the agent that should receive the package!

OK, this indicates that it is not Cilium dropping the packet but something else. This is usually an iptables rule dropping it or a network configuration that causes this.

It is just kube-dns connectivity that doesn't work or is all pod to pod connectivity broken? e.g. can you reach the pod IP directly without resolving it via DNS first?

**Comment by enzian** [comment]
hmm, good point to get started:

> xx drop (Policy denied (L3)), to endpoint 22533, identity 267->263: 10.205.85.133:34336 -> 10.205.94.154:80 tcp SYN
>xx drop (Policy denied (L3)), to endpoint 22533, identity 267->263: 10.205.85.133:34336 -> 10.205.94.154:80 tcp SYN

It appears, that all packages to either the pods or the service's IP's are dropped! This is reported for TCP connections but apparently not for UDP connections?!? This is strange since I do not have any policies in place yet:

> kubectl -n kube-system get cnp
> No resources found.

**Comment by enzian** [comment]
looks like I'm a step closer - the denied messages came from a left over policy in a namespace I probably did not check!

Now if both endpoints are on the same node - all is well - not so on different nodes! These packages go missing! Baffles me because:

```
# kubectl -n kube-system exec cilium-dt5tg -- cilium-health status
Probe time:   2018-01-05T16:37:52Z
Nodes:
  sseubuv02 (localhost):
    Host connectivity to 10.118.32.204:
      ICMP:          OK, RTT=152.603µs
      HTTP via L3:   OK, RTT=561.584µs
  sseubuv03:
    Host connectivity to 10.118.32.205:
      ICMP:          OK, RTT=281.456µs
      HTTP via L3:   OK, RTT=976.897µs
  sseubuv01:
    Host connectivity to 10.118.32.202:
      ICMP:          OK, RTT=257.703µs
      HTTP via L3:   OK, RTT=1.320539ms
```
