### ISSUE TITLE
CI: Error when enabling sysctl parameters (read-only file system)

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#19526]
## CI failure

```
2022-04-22T07:50:59.954776314Z level=info msg=" - !:controller-revision-hash" subsys=labels-filter
2022-04-22T07:50:59.954779914Z level=info msg=" - !:annotation.*" subsys=labels-filter
2022-04-22T07:50:59.954783514Z level=info msg=" - !:etcd_node" subsys=labels-filter
2022-04-22T07:50:59.955810725Z level=info msg="Auto-disabling \"enable-bpf-clock-probe\" feature since KERNEL_HZ cannot be determined" error="Cannot probe CONFIG_HZ" subsys=daemon
2022-04-22T07:50:59.955954726Z level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.3.0.0/16
2022-04-22T07:50:59.955986927Z level=info msg="Initializing daemon" subsys=daemon
2022-04-22T07:50:59.956017527Z level=fatal msg="Error when enabling sysctl parameters" error="could not open the sysctl file /proc/sys/net/ipv4/ip_forward: open /proc/sys/net/ipv4/ip_forward: read-only file system" subsys=daemon
```

Suspected commit right now where Cilium DS might be missing CAPs: https://github.com/cilium/cilium/commit/28bffa6d4b11936f9c2dc94a68dec0ecd4d3f745

Example action with sysdump: https://github.com/cilium/cilium/actions/runs/2206334871

**Comment by borkmann** [comment]
Fixed via https://github.com/cilium/cilium/pull/18898

**Comment by jrajahalme** [comment]
Happened on v1.11 backport on AWS-CNI job: https://github.com/cilium/cilium/actions/runs/2235236781

**Comment by jrajahalme** [comment]
@aanm Also on v1.10 backport for the AWS-CNI job: https://github.com/cilium/cilium/actions/runs/2235281718

**Comment by aanm** [comment]
@jrajahalme it should already be fixed, please run the aws-cni job again

**Comment by dnkanga** [comment]
I am facing this issue with the stable version

**Comment by adamw-linadm** [comment]
Still have this problem in cilium 1.12.1, version 1.11.7 was fine.
