### ISSUE TITLE
CI: ConformanceGKE: Timeout on cilium-test deletion

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#22368]
ConformanceGKE runs are failing on master with a 1h15min timeout on:
```
⌛ Waiting for cilium-test namespace to be terminated...
Error: The operation was canceled.
```

I don't know the root cause, but this can probably be worked around by deleting the pods in the namespace instead of the namespace itself (you can notice in the sysdump that the namespace's pods are already gone) and using a different test namespace for each run of the connectivity tests.

**Comment by aanm** [comment]
https://github.com/cilium/cilium/actions/runs/3538749676/jobs/5939896569

**Comment by tklauser** [comment]
https://github.com/cilium/cilium-cli/pull/1237 should fix/work around this in cilium-cli. Once this is merged and a new cilium-cli version is released, bumping `cilium_cli_version` in the GKE workflows should do the trick.

**Comment by aanm** [comment]
Fixed by https://github.com/cilium/cilium/pull/22441

**Comment by pchaigno** [comment]
Seems https://github.com/cilium/cilium-cli/pull/1237 wasn't enough to fix it. It's still happening. E.g.:
- https://github.com/cilium/cilium/actions/runs/3610019637/jobs/6083565168
- https://github.com/cilium/cilium/actions/runs/3612337046/jobs/6087376867

**Comment by tklauser** [comment]
Looking at a [recent failure on `master`](https://github.com/cilium/cilium/actions/runs/3644652537) ([sysdump](https://github.com/cilium/cilium/suites/9737305924/artifacts/467298338)), we see that all pods in the namespace got deleted:

```
% yq '.items[].metadata.namespace | select(. == "kube-system")' k8s-pods-20221208-033953.yaml
%
```

Looking at the `cilium-test` namespace in `k8s-namespaces-20221208-033953.yaml` we see:

```
% yq '.items[] | select(.metadata.name == "cilium-test") | .status' k8s-namespaces-20221208-033953.yaml
conditions:
  - lastTransitionTime: "2022-12-08T02:50:56Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2022-12-08T02:51:02Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2022-12-08T02:51:02Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2022-12-08T02:51:19Z"
    message: All content successfully removed
    reason: ContentRemoved
    status: "False"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2022-12-08T02:51:02Z"
    message: All content-preserving finalizers finished
    reason: ContentHasNoFinalizers
    status: "False"
    type: NamespaceFinalizersRemaining
phase: Terminating
```

The first condition looks suspicious:

```
  - lastTransitionTime: "2022-12-08T02:50:56Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
```

We seem to have hit this before, e.g. in https://github.com/cilium/cilium-cli/issues/255#issuecomment-1270841571

**Comment by pchaigno** [comment]
This looks oddly similar to the issues you get on EKS when you try to run with tunnel mode enabled. cc @bmcustodio 
In that case, kube-apiserver can't reach the metrics-server pod because that is running in the overlay. I've checked and it looks like this flake always happens after testing Cilium on GKE with tunnel mode.

**Comment by squeed** [comment]
Another instance: https://github.com/cilium/cilium/actions/runs/4200699587/jobs/7286990604

**Comment by pchaigno** [comment]
@tklauser Are you still looking into this?

**Comment by tklauser** [comment]
> @tklauser Are you still looking into this?

Currently lacking cycles and ideas on how to proceed, so I'm not actively looking into this. I'm going to unassign myself for now.
