### ISSUE TITLE
Network policy does not work as expected in native routing mode

### ISSUE THREAD

**Issue by DockToFuture** [cilium/cilium#23376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have two cilium clusters one with an overlay network (vxlan) and one without (native routing mode).
Each cluster has two nodes (10.180.81.61,10.180.25.21).
In the cluster with overlay I see no problems when running the setup described below.
In the one which is running in the native routing mode I see a lot of packets being dropped with cilium monitor because the traffic seems to come from the outside world (identity: world) but it is not.

A small reproduction case includes two pods labeled with `name: net2` running in the default namespace.
A nginx pod labeld with `k8s-app: nginx` which is exposed via service on port 80 in the default namespace.
The nginx pod runs on node 10.180.25.21.
And the following two networkpolicies:

```
# Not Working
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-nginx
  namespace: default
spec:
  podSelector:
    matchLabels:
      k8s-app: nginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          name: net2
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-nginx2
  namespace: default
spec:
  podSelector:
    matchLabels:
      name: net2
  egress:
  - {}
  policyTypes:
  - Egress
```
When I allow all egress from the net2 pods (100.64.0.126,100.64.1.189) and allow only ingress on the nginx from those two pods, curling of the nginx ( pod ip: 100.64.1.34) service fails on one node 10.180.81.61. 
When running cilium monitor type=drop on node 10.180.25.21, I see the reason for that:
```
xx drop (Policy denied) flow 0x1e30736e to endpoint 3359, file bpf_lxc.c line 1918, , identity world->31125: 10.180.81.61:49936 -> 100.64.1.34:80 tcp SYN
xx drop (Policy denied) flow 0x1e30736e to endpoint 3359, file bpf_lxc.c line 1918, , identity world->31125: 10.180.81.61:49936 -> 100.64.1.34:80 tcp SYN
``` 
The traffic comes in with the node IP (10.180.81.61) and is dropped.

```
# Working
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-nginx
  namespace: default
spec:
  podSelector:
    matchLabels:
      k8s-app: nginx
  ingress:
  - {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: to-nginx2
  namespace: default
spec:
  podSelector:
    matchLabels:
      name: net2
  egress:
  - to:
    - podSelector:
        matchLabels:
          k8s-app: nginx
  policyTypes:
  - Egress
```
When I allow all ingress and and allow only egress traffic from pod net2 pod to the nginx pod everything works.

I do not understand, why the traffic is in the first case coming from the node IP and is dropped (SNAT is disabled).
It looks to me like in the first case somehow the identity got lost which is according to `cilium identity list`:
```
7315   k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default
           k8s:io.cilium.k8s.policy.cluster=default
           k8s:io.cilium.k8s.policy.serviceaccount=default
           k8s:io.kubernetes.pod.namespace=default
           k8s:name=net2
```
and instead has now the identity `world`.

Shouldn't the identity here be obtained? Is there a way to somehow tell cilium that the k8s node cidr range should not have the identity `reserved:world`?
```
16777218   cidr:10.180.0.0/16
           reserved:world
```

### Cilium Version

Client: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64

### Kernel Version

Linux ip-10-180-25-21.eu-west-1.compute.internal 5.10.141-garden-cloud-amd64 #1 SMP Debian 5.10.141-0gardenlinux1 (2022-09-07) x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.25.4

### Anything else?

For reproduction:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: net2
spec:
  selector:
    matchLabels:
      name: net2
  template:
    metadata:
      labels:
        name: net2
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
      - name: net2
        image: nicolaka/netshoot
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600;done"]
        ports:
        - containerPort: 80
      tolerations:
      - key: ""
        operator: Exists
```

nginx pod was created with:

```
kubectl run nginx --image=nginx
kubectl expose pod nginx --port 80
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christarazi** [comment]
Do you have `10.180.0.0/16` anywhere in your policies like `toCIDR` or `fromCIDR`?

**Comment by christarazi** [comment]
Can you also provide further repro instructions for initiating the dropped traffic?

**Comment by DockToFuture** [comment]
> Can you also provide further repro instructions for initiating the dropped traffic?
I've curled the service ip and pod ip out of the net2 pods.
```
curl <svc-ip-of-nginx> 
curl <pod-ip-of-nginx>
```

**Comment by DockToFuture** [comment]
> Do you have `10.180.0.0/16` anywhere in your policies like `toCIDR` or `fromCIDR`?

Yes it's also included in the kube-dns network policy:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: kube-system
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector: {}
    - ipBlock:
        cidr: <podCIDR>
    - ipBlock:
        cidr: 10.180.0.0/16
    ports:
    - port: 9153
      protocol: TCP
    - port: 8053
      protocol: TCP
    - port: 8053
      protocol: UDP
  podSelector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values:
      - kube-dns
  policyTypes:
  - Ingress
  - Egress
```

**Comment by christarazi** [comment]
For

```
    - ipBlock:
        cidr: <podCIDR>
```

Cilium doesn't [support](https://docs.cilium.io/en/v1.12/policy/language/#ip-cidr-based) this.

And I assume 

```
    - ipBlock:
        cidr: 10.180.0.0/16
```

is to allow traffic from nodes (or pods with host-network)? I'd advise using CNPs with [entities-based rules](https://docs.cilium.io/en/v1.12/policy/language/#entities-based).

**Comment by DockToFuture** [comment]
Issue is solved.

**Comment by JohannesAtGit** [comment]
I stumbled across the same problem.
But I and the initial poster are using a standard K8s _NetworkPolicy_ not a _CiliumNetworkPolicy_.
I still don't get why it is not working.
