### ISSUE TITLE
some cillium agents cannot pick the correct cilium agent health endpoint IP when clustermesh is active in 1.13.0

### ISSUE THREAD

**Issue by eminaktas** [cilium/cilium#24411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The problem is that some of the cilium agents in a cluster are not getting the correct IP for the health endpoints of the other meshed cluster's cilium agents. This is only tested in v1.13.0, I don't know if this exists in the older versions. 

For example;

I have meshed three clusters in this example.

First, check the status of any cilium agent from the `s-container-p1-1mars` cluster, three of the cilium agent's endpoints are registered as unreachable. But this is just for this agent. These unreachable nodes may change for other agents in the same cluster. However, the problem is not the nodes are not reachable, the other cluster's endpoints for health check in `s-container-p1-1mars` is wrong.

```bash
$ cilium status --verbose
**omitted**
Cluster health:                                                        24/27 reachable   (2023-03-16T10:56:17Z)
  Name                                                                 IP                Node        Endpoints
  s-container-p1-1mars/k8s-s-container-p1-1mars-master-3 (localhost)  **omitted**     reachable   reachable
**omitted**
  s-container-p1-2mars/k8s-s-container-p1-2mars-monitor-1              **omitted**     reachable   unreachable
  s-container-p1-2mars/k8s-s-container-p1-2mars-worker-1               **omitted**     reachable   reachable
  s-container-p1-2mars/k8s-s-container-p1-2mars-worker-2               **omitted**     reachable   unreachable
**omitted**
s-container-p1-3mars/k8s-s-container-p1-3mars-master-3               **omitted**      reachable   unreachable
```

Let's look at the `s-container-p1-3mars/k8s-s-container-p1-3mars-master-3` endpoint IP with `cilium-health status` in the current agent (`s-container-p1-1mars/k8s-s-container-p1-1mars-master-3`). The IP is `10.244.1.50`. But on the other end, the IP is different.

```bash
  s-container-p1-3mars/k8s-s-container-p1-3mars-master-3:
    Host connectivity to **omitted**:
      ICMP to stack:   OK, RTT=1.80853ms
      HTTP to agent:   OK, RTT=663.958µs
    Endpoint connectivity to 10.244.1.50:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get "http://10.244.1.50:4240/hello": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

The actual IP is `10.244.1.31` in its own node (`k8s-s-container-p1-3mars-master-3` node in the `s-container-p1-3mars` cluster)

```bash
$ cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                               IPv6   IPv4          STATUS
           ENFORCEMENT        ENFORCEMENT
**omitted**
2036       Disabled           Disabled          4          reserved:health                                                                  10.244.1.31   ready
```

As an example, let's check random cilium agent if it correctly gets the IP for `s-container-p1-3mars/k8s-s-container-p1-3mars-master-3`. 

An agent in the second cluster (`s-container-p1-2mars`) has the correct IP.

```bash
  s-container-p1-3mars/k8s-s-container-p1-3mars-master-3:
    Host connectivity to **omitted**:
      ICMP to stack:   OK, RTT=1.473478ms
      HTTP to agent:   OK, RTT=590.297µs
    Endpoint connectivity to 10.244.1.31:
      ICMP to stack:   OK, RTT=1.386667ms
      HTTP to agent:   OK, RTT=338.438µs
```

There are no unreachable cilium agents here.

```bash
$ cilium status
**omitted**
Cluster health:          27/27 reachable   (2023-03-16T11:26:07Z)
**omitted**
```

An agent in the first cluster (`s-container-p1-1mars`)  (the problematic cluster but another agent) has the correct IP.

```bash
  s-container-p1-3mars/k8s-s-container-p1-3mars-master-3:
    Host connectivity to **omitted**:
      ICMP to stack:   OK, RTT=1.082464ms
      HTTP to agent:   OK, RTT=309.067µs
    Endpoint connectivity to 10.244.1.31:
      ICMP to stack:   OK, RTT=1.950775ms
      HTTP to agent:   OK, RTT=417.083µs
```

Like the above example, the unreachable endpoints are different here.

```bash
Cluster health:                                                        26/27 reachable   (2023-03-16T12:01:03Z)
  Name                                                                 IP                Node        Endpoints
**omitted**
  s-container-p1-2mars/k8s-s-container-p1-2mars-monitor-1              **omitted**     reachable   unreachable
  s-container-p1-2mars/k8s-s-container-p1-2mars-worker-1               **omitted**     reachable   reachable
  s-container-p1-2mars/k8s-s-container-p1-2mars-worker-2               **omitted**     reachable   reachable
  s-container-p1-2mars/k8s-s-container-p1-2mars-worker-3               **omitted**      reachable   reachable
**omitted**
  s-container-p1-3mars/k8s-s-container-p1-3mars-master-3               **omitted**      reachable   reachable
**omitted**
```

I may need to add this but this happens when cilium agents are restarted. I waited a long time(like a week) to see if it fixes itself. I did for some agents but not all.

### Cilium Version

Client: 1.13.0 c9723a8d 2023-02-15T14:18:31+01:00 go version go1.19.6 linux/amd64
Daemon: 1.13.0 c9723a8d 2023-02-15T14:18:31+01:00 go version go1.19.6 linux/amd64

### Kernel Version

Linux k8s-s-container-p1-3mars-master-3 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.26.2
Server Version: v1.23.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
This is likely fixed by #23532 (and its backport to 1.13)

**Comment by eminaktas** [comment]
I have been testing the fix and the problem still persists.

After upgrading from 1.13.0 to 1.13.1, I validated that only Cluster-1 health status to all meshed clusters was set to reachable for both `Node` and `Endpoints`. However, Cluster-2 and Cluster-3 couldn't get the correct IPs for Cluster-1. I waited to see if it fixes itself without any touch but it did not.

I decided to restart first the `clustermesh-apiserver` pods on Cluster-2 to see if it corrects the Cluster-1 Endpoint IPs. Unfortunately, It did not work. So, I restarted the `cilium-agent` pods on Cluster-2 to see if agents can get the correct Endpoint IPs. No luck. After a while, I restarted again the `clustermesh-apiserver`. This is the time, I could validate all `Endpoints` set to reachable after a little time for only Cluster-2. now, Cluster-1 and Cluster-3 set to Endpoints unreachable for Cluster-2.

I think somehow `cilium-agent` cannot set or get the correct IPs. Because when I restart the `cilium-agent`, it only shows its own nodes. Then, I restart the `clustermesh-apiserver`, and it gets the correct IPs correctly from other clusters. But this time the other cluster loses the correct IPs since the `cilium-agent` gets a new health endpoint.
