### ISSUE TITLE
CI: test-conn-disrupt-client failed due to interrupted traffic during upgrade/downgrade

### ISSUE THREAD

**Issue by jschwinger233** [cilium/cilium#28088]
## CI failure

Failed job: https://github.com/cilium/cilium/actions/runs/6154793242/job/16700697606

```
 [=] Test [no-interrupted-connections]

  [-] Scenario [no-interrupted-connections/no-interrupted-connections]
  🟥 Pod test-conn-disrupt-client-cc557fcf9-8sjnb flow was interrupted (restart count does not match 2 != 3)
```

[cilium-sysdump-2-final.zip](https://github.com/cilium/cilium/files/12583812/cilium-sysdump-2-final.zip)

This issue is different from [Drop due to missed tail call when doing downgrade from main to v1.13.4](https://github.com/cilium/cilium/issues/26739) because there is no `Missed tail call` in cilium-bugtool/cmd/cilium-metrics-list.md.

This issue is not an IPsec related issue because:
1. This failed check didn't enable IPsec, although the job name is `IPsec upgrade`. The job given above was triggered from https://github.com/cilium/cilium/pull/28086 which disabled IPsec.
2. XFRM counters didn't increase.

**Comment by brb** [comment]
The [ci-e2e-upgrade](https://github.com/cilium/cilium/pull/27322) PR is hitting this too (1 out of ~3 times). For example, https://github.com/cilium/cilium/actions/runs/6147703736/job/16679772837.

**Comment by giorio94** [comment]
Another likely occurrence: https://github.com/cilium/cilium/actions/runs/6222284686/job/16885925831
Sysdump: [cilium-sysdump-3-final.zip](https://github.com/cilium/cilium/files/12650080/cilium-sysdump-3-final.zip)

**Comment by giorio94** [comment]
And another one: https://github.com/cilium/cilium/actions/runs/6224209732/job/16891907764
Sysdump: [cilium-sysdump-3-final.zip](https://github.com/cilium/cilium/files/12650124/cilium-sysdump-3-final.zip)

(In both cases 

```
$ grep Error **/*encrypt*                                                                                 17:49:28
cilium-bugtool-cilium-r9f96-20230918-152220/cmd/cilium-encrypt-status.md:Errors: 0                         
cilium-bugtool-cilium-sn7l9-20230918-152220/cmd/cilium-encrypt-status.md:Errors: 0                         
cilium-bugtool-cilium-tz9hq-20230918-152220/cmd/cilium-encrypt-status.md:Errors: 0  
```

**Comment by giorio94** [comment]
More occurrences: https://github.com/cilium/cilium/actions/runs/6232761468

**Comment by margamanterola** [comment]
https://github.com/cilium/cilium/issues/27827 was a duplicate of this issue. Closed to avoid duplicates, but it has a couple more sysdumps, in case that's helpful.

**Comment by brb** [comment]
@giorio94 Mentioned that the drop happens almost at the same time when the related client endpoint gets regenerated. The drop was observed only when both IPv{4,6} and the bpf_lxc per-packet LB were enabled. Anyway, I extend the Marco's reproducer to get more info:

```
cd cilium &&  ./contrib/scripts/kind.sh "" 2 "" "" "iptables" "dual"
cd cilium-cli && git co origin/pr/brb/conn-short && make
./cilium-cli/cilium install --set=debug.enabled=true --set=bpf.masquerade=false --set=bpf.monitorAggregation=none --set=hubble.enabled=false --set=tunnel=vxlan --set=ipv4.enabled=true --set=ipv6.enabled=true

cat > ./cilium-cli/run.sh <<EOF
#!/bin/bash -e

./cilium connectivity test \
  --hubble=false \
  --conn-disrupt-dispatch-interval 0ms \
  --include-conn-disrupt-test --conn-disrupt-test-setup

kubectl -n cilium-test wait pods -l app=test-conn-disrupt-client --for condition=Ready --timeout=90s

CLIENT_POD=$(kubectl -n cilium-test get pods -l app=test-conn-disrupt-client -o wide  | grep kind-worker2 | head -n1 | awk '{print $1}')
CLIENT_IP=$(kubectl -n cilium-test logs $CLIENT_POD | grep -o 'from .*' | awk '{print $2}' | cut -d: -f1)
CLIENT_PORT=$(kubectl -n cilium-test logs $CLIENT_POD | grep -o 'from .*' | awk '{print $2}' | cut -d: -f2)

echo "$CLIENT_POD $CLIENT_IP $CLIENT_PORT"

sudo rm -f /tmp/pwru.ready

sudo pwru --output-tuple \
   --output-file=/tmp/pwru.log \
	--output-meta \
   --ready-file=/tmp/pwru.ready \
	"host $CLIENT_IP or port $CLIENT_PORT" \
    2>/tmp/pwru.status &
PWRU_PID=$!

while [ ! -f /tmp/pwru.ready ]; do sleep 1; done

kubectl rollout restart -n kube-system ds/cilium

# Wait until all agents successfully restarted before scaling the replicas again
kubectl rollout status -n kube-system ds/cilium --timeout=1m

./cilium status --wait

sleep 10

./cilium connectivity test --short

./cilium connectivity test \
  --hubble=false \
  --flow-validation=disabled \
  --test='no-interrupted-connections' \
  --test='no-missed-tail-calls' \
  --include-conn-disrupt-test

sudo kill $PWRU_PID
wait $PWRU_PID

EOF

chmod +x ./cilium-cli/run.sh
cd cilium-cli/
while ./run.sh; do :; done
```

The drop with pwru:
```
0xffff88e04ad5c2e8     19     [tcd-server] __netif_receive_skb_one_core netns=4026533492 mark=0x0 iface=4(cilium_vxlan) proto=8 mtu=1500 len=308 10.244.0.128:8000->10.244.1.186:33086(tcp)
0xffff88e04ad5c2e8     19     [tcd-server]             tcf_classify netns=4026533492 mark=0x0 iface=4(cilium_vxlan) proto=8 mtu=1500 len=308 10.244.0.128:8000->10.244.1.186:33086(tcp)
0xffff88e04ad5c2e8     19     [tcd-server]      skb_ensure_writable netns=4026533492 mark=0x0 iface=4(cilium_vxlan) proto=8 mtu=1500 len=322 10.244.0.128:8000->10.244.1.186:33086(tcp)
0xffff88e04ad5c2e8     19     [tcd-server]      skb_ensure_writable netns=4026533492 mark=0x0 iface=4(cilium_vxlan) proto=8 mtu=1500 len=322 10.244.0.128:8000->10.244.1.186:33086(tcp)
0xffff88e04ad5c2e8     19     [tcd-server]      skb_ensure_writable netns=4026533492 mark=0x0 iface=4(cilium_vxlan) proto=8 mtu=1500 len=322 10.244.0.128:8000->10.244.1.186:33086(tcp)
0xffff88e04ad5c2e8     19     [tcd-server]      skb_ensure_writable netns=4026533492 mark=0x0 iface=4(cilium_vxlan) proto=8 mtu=1500 len=322 10.244.0.128:8000->10.244.1.186:33086(tcp)
0xffff88e04ad5c2e8     19     [tcd-server]      skb_ensure_writable netns=4026533492 mark=0x0 iface=4(cilium_vxlan) proto=8 mtu=1500 len=322 10.244.0.128:8000->10.244.1.186:33086(tcp)
0xffff88e04ad5c2e8     19     [tcd-server]          skb_do_redirect netns=4026533492 mark=0x0 iface=4(cilium_vxlan) proto=8 mtu=1500 len=322 10.244.0.128:8000->10.244.1.186:33086(tcp)
0xffff88e04ad5c2e8     19     [tcd-server]           __bpf_redirect netns=4026533492 mark=0x0 iface=4(cilium_vxlan) proto=8 mtu=1500 len=322 10.244.0.128:8000->10.244.1.186:33086(tcp)
...
0xffff88e04ad5c2e8     19     [tcd-server] kfree_skb_reason(SKB_DROP_REASON_NO_SOCKET) netns=4026534202 mark=0x0 iface=278(eth0) proto=8 mtu=1500 len=288 10.244.0.128:8000->10.244.1.186:33086(tcp)
```

What happened is that the BPF prog attached to `cilium_vxlan` didn't do the rev-DNAT. This is most likely due to a missing CT entry. I'm continuing the investigation.

**Comment by brb** [comment]
Small update. Added bpftrace to the rescue:
```
cat > trace.bt <<EOF
struct key { u32 daddr; u32 saddr; u16 dport; u16 sport }

kretfunc:vmlinux:bpf_map_lookup_elem {
    if (((struct bpf_map *)args->map)->id == $1) {
        printf("%s %s:%d->%s:%d : %x\n",
            strftime("%H:%M:%S:%f", nsecs),
            ntop(((struct key *)((struct bpf_map*)args->key))->saddr),
            bswap(((struct key *)((struct bpf_map*)args->key))->dport),
            ntop(((struct key *)((struct bpf_map*)args->key))->daddr),
            bswap(((struct key *)((struct bpf_map*)args->key))->sport),
            retval
        );
    }
}
EOF

# to get CT map ID:
docker exec -ti kind-worker2 bpftool map show pinned /sys/fs/bpf/tc/globals/cilium_ct4_global

sudo bpftrace trace.bt $MAP_ID
```

The relevant output:
```
13:17:13:584423 10.244.1.102:8000->10.244.1.154:60358 : e8bb5980
...
13:17:13:789869 10.244.1.102:8000->10.244.1.154:60358 : e8c22238 <-- DROP happened ~at this point of time
```

From ^^ I see that the CT map lookup for the reply got a different map value (which probably didn't have any `rev_nat_id` set) than before. To be continued.

**Comment by jschwinger233** [comment]
(If pwru has ability to trace helper functions and parse kv automatically....

**Comment by brb** [comment]
Managed to reproduce again with more map update info:
```
06:45:37:327713 L 10.244.0.197:8000->10.244.1.149:33424 (0) : e8be8038 (88) <- LOOKUP for the reply, returned rev_nat_index=88
06:45:37:327718 U 10.244.0.197:8000->10.244.1.149:33424 (0) => (0) : 0 <-- UPDATE with rev_nat_index=0
06:45:37:533374 L 10.244.0.197:8000->10.244.1.149:33424 (0) : e8c3d2e0 (0) <-- LOOKUP for the reply, rev_nat_index=0, which makes the reply to be dropped
```

**Comment by brb** [comment]
From looking into the `bpf_lxc.c`, the only possible explanation for the lookup and then update above is that `CT_TAIL_CALL_BUFFER4` gets corrupted, which then triggers the CT creation (=update) due to `ret=0` (= `CT_NEW`).

**Comment by brb** [comment]
OK, got to the conclusion. During the upgrade, we don't atomically swap the prog maps used by bpf_lxc instances. Instead, we swap only programs. So what very likely happens in this drop case is that the program which fills the `CT_TAIL_CALL_BUFFER4` does the tail call to the new program which access a different `CT_TAIL_CALL_BUFFER4` map (the map is not pinned, so it's always recreated). 

The fix  for the problem - https://github.com/cilium/cilium/issues/20691.

**Comment by brb** [comment]
For the sake of posterity the latest bpftrace script:
```
> cat trace.bt
struct key { u32 daddr; u32 saddr; u16 dport; u16 sport; u8 nexthdr; u8 flags }
struct val { u64 a; u64 backend_id; u64 b; u64 c; u32 d; u16 e; u16 rev_nat_index  }

kretfunc:vmlinux:bpf_map_lookup_elem {
    if (((struct bpf_map *)args->map)->id == $1 && retval != 0) {
        printf("%s L %s:%d->%s:%d (%d) : %x (%d)\n",
            strftime("%H:%M:%S:%f", nsecs),
            ntop(((struct key *)((struct bpf_map*)args->key))->saddr),
            bswap(((struct key *)((struct bpf_map*)args->key))->dport),
            ntop(((struct key *)((struct bpf_map*)args->key))->daddr),
            bswap(((struct key *)((struct bpf_map*)args->key))->sport),
            ((struct key *)((struct bpf_map*)args->key))->flags,
            retval,
            bswap(((struct val *)retval)->rev_nat_index)
        );
    }
}

kretfunc:vmlinux:bpf_map_delete_elem {
    if (((struct bpf_map *)args->map)->id == $1) {
        printf("%s D %s:%d->%s:%d : %x\n",
            strftime("%H:%M:%S:%f", nsecs),
            ntop(((struct key *)((struct bpf_map*)args->key))->saddr),
            bswap(((struct key *)((struct bpf_map*)args->key))->dport),
            ntop(((struct key *)((struct bpf_map*)args->key))->daddr),
            bswap(((struct key *)((struct bpf_map*)args->key))->sport),
            retval
        );
    }
}

kretfunc:vmlinux:bpf_map_update_elem {
    if (((struct bpf_map *)args->map)->id == $1) {
        printf("%s U %s:%d->%s:%d (%d) => %x (%d) : %x\n",
            strftime("%H:%M:%S:%f", nsecs),
            ntop(((struct key *)((struct bpf_map*)args->key))->saddr),
            bswap(((struct key *)((struct bpf_map*)args->key))->dport),
            ntop(((struct key *)((struct bpf_map*)args->key))->daddr),
            bswap(((struct key *)((struct bpf_map*)args->key))->sport),
            ((struct key *)((struct bpf_map*)args->key))->flags,
            args->value,
            bswap(((struct val *)((struct bpf_map*)args->value))->rev_nat_index),
            retval
        );
    }
}
```

**Comment by aditighag** [comment]
More occurrences - https://github.com/cilium/cilium/actions/runs/6552996132/job/17797492988 and 
https://github.com/cilium/cilium/actions/runs/6552996245/job/17797488405

**Comment by tommyp1ckles** [comment]
Hit this here: https://github.com/cilium/cilium/actions/runs/6555863486/job/17804969292

**Comment by margamanterola** [comment]
There are draft backports for 1.14 and 1.13 already. 1.12 is trickier.

**Comment by tommyp1ckles** [comment]
Was #28740 alone intended to fix this in main? I've been hitting it a lot on a freshly rebased branch: https://github.com/cilium/cilium/actions/runs/6699233827/job/18203033968

**Comment by giorio94** [comment]
My understanding is that the downgrade path also requires https://github.com/cilium/cilium/pull/28830 to be fixed.

**Comment by ti-mo** [comment]
Is this specific issue still relevant? It looks to me like this is a more common type of conn failure unrelated to missed tail calls. Missed tail calls are fortunately becoming more rare after the recent round of fixes. https://github.com/cilium/cilium/pull/29482 is currently up for review, which addresses a race condition during initial datapath bringup that results in missed tail calls when the host firewall is enabled.

The more recent links to failed GHA jobs are all `no-interrupted-connections` failures, without being specifically tied to missed tail calls. Thanks!

**Comment by pchaigno** [comment]
Here is a recent one with a missed tail call: https://github.com/cilium/cilium/actions/runs/7089953274/job/19295849453. It happens on the IPsec workflow so it's not the host firewall one (incompatible with IPsec).

**Comment by brb** [comment]
Some of recent (now - 2days) interrupted connection and missed tail call failures which are unrelated to the previous conversations in the this issue above (although the debugging techniques might be useful to troubleshoot).

### main branch

n/a

### v1.15 branch

* 5.4, missed tail call during downgrade to v1.14 https://github.com/cilium/cilium/actions/runs/7218581265/job/19668197550.

### v1.14 branch

* 6.1, interrupted conn during upgrade https://github.com/cilium/cilium/actions/runs/7221777742/job/19677508485.
* bpf-next, interrupted conn during upgrade https://github.com/cilium/cilium/actions/runs/7216082570/job/19661637898.
* 5.4, missed tail call during downgrade https://github.com/cilium/cilium/actions/runs/7208566949/job/19637803614.

### v1.13 branch

n/a

### v1.12 branch

* 5.10, interrupted conn during upgrade https://github.com/cilium/cilium/actions/runs/7221777322/job/19677487775
* 5.10 interrupted conn during upgrade https://github.com/cilium/cilium/actions/runs/7218580685/job/19668199783.
* 5.10 interrupted conn during upgrade https://github.com/cilium/cilium/actions/runs/7216082031/job/19661620262.

**Comment by qmonnet** [comment]
I've been trying to reproduce locally, on top of v1.14 mostly, with the reproducer above or with my own steps that are closer to the CI workflow commands, but I haven't succeeded so far :disappointed:

**Comment by pippolo84** [comment]
Another potential hit [here](https://github.com/cilium/cilium/actions/runs/7395578181/job/20119008822)

```
[=] Test [no-interrupted-connections]

  [-] Scenario [no-interrupted-connections/no-interrupted-connections]
  🟥 Pod test-conn-disrupt-client-647c46854d-rr9bp flow was interrupted (restart count does not match 0 != 1)
```

[Full logs](https://github.com/cilium/cilium/files/13820112/logs_1987253.zip)
Sysdump too big :(

**Comment by ti-mo** [comment]
Unassignined myself as I mostly sat in for fixing tail call-related issues. With https://github.com/cilium/cilium/pull/30248 merged, the last known source of missed tail calls (that pop up in CI) should be gone.

**Comment by qmonnet** [comment]
I haven't made significant progress to resolve this, but I just managed to reproduce locally.

I've been trying for some time with [Marco's and Martynas' reproducer](https://github.com/cilium/cilium/issues/28088#issuecomment-1744386017), on 1.13 and 1.14, but with no success - I did not observe the flake.

I tried as well to reproduce the `ci-ipsec-upgrade` workflow locally, on 1.13 and 1.14, and did manage to reproduce the failure when working on 1.13, after downgrading back to 1.12.

<details><summary><tt>ci-ipsec-upgrade</tt> steps</summary>

---

Deploy kind, Cilium:

```
./contrib/scripts/kind.sh "" 3 "" "" "iptables" "dual"
kubectl patch node kind-worker3 --type=json -p='[{"op":"add","path":"/metadata/labels/cilium.io~1no-schedule","value":"true"}]'
kubectl create -n kube-system secret generic cilium-ipsec-keys \
    --from-literal=keys="3 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64)) 128"
./cilium-cli install \
    --wait \
    --chart-directory=./cilium-v1.12/install/kubernetes/cilium/ \
    --helm-set=debug.enabled=true \
    --helm-set=debug.verbose=envoy \
    --helm-set=hubble.eventBufferCapacity=65535 \
    --helm-set=bpf.monitorAggregation=none \
    --helm-set=cluster.name=default \
    --nodes-without-cilium=kind-worker3 \
    --helm-set-string=kubeProxyReplacement=disabled \
    --set='bpfClockProbe=false,cni.uninstall=false' \
    --helm-set=image.repository=quay.io/cilium/cilium-ci \
    --helm-set=image.tag=v1.12 \
    --helm-set=image.useDigest=false \
    --helm-set=operator.image.repository=quay.io/cilium/operator \
    --helm-set=operator.image.suffix=-ci \
    --helm-set=operator.image.tag=v1.12 \
    --helm-set=operator.image.useDigest=false \
    --helm-set=hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci \
    --helm-set=hubble.relay.image.tag=v1.12 \
    --helm-set=hubble.relay.image.useDigest=false \
    --helm-set-string=tunnel=disabled \
    --helm-set-string=autoDirectNodeRoutes=true \
    --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 \
    --helm-set-string=tunnel=disabled \
    --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56 \
    --helm-set-string=endpointRoutes.enabled=true \
    --helm-set=encryption.enabled=true \
    --helm-set=encryption.type=ipsec
```

Prepare the conn-disrupt test:

```
./cilium-cli connectivity test --include-conn-disrupt-test --conn-disrupt-test-setup
```

Upgrade to 1.13:

```
./cilium-cli upgrade \
    --wait \
    --chart-directory=./install/kubernetes/cilium \
    --helm-set=debug.enabled=true \
    --helm-set=debug.verbose=envoy \
    --helm-set=hubble.eventBufferCapacity=65535 \
    --helm-set=bpf.monitorAggregation=none \
    --helm-set=cluster.name=default \
    --nodes-without-cilium=kind-worker3 \
    --helm-set-string=kubeProxyReplacement=disabled \
    --set='bpfClockProbe=false,cni.uninstall=false' \
    --helm-set=image.repository=quay.io/cilium/cilium-ci \
    --helm-set=image.tag=b60f41af8bc6782535e636e108d1e97ae5a4f657 \
    --helm-set=image.useDigest=false \
    --helm-set=operator.image.repository=quay.io/cilium/operator \
    --helm-set=operator.image.suffix=-ci \
    --helm-set=operator.image.tag=b60f41af8bc6782535e636e108d1e97ae5a4f657 \
    --helm-set=operator.image.useDigest=false \
    --helm-set=hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci \
    --helm-set=hubble.relay.image.tag=b60f41af8bc6782535e636e108d1e97ae5a4f657 \
    --helm-set=hubble.relay.image.useDigest=false \
    --helm-set-string=tunnel=disabled \
    --helm-set-string=autoDirectNodeRoutes=true \
    --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 \
    --helm-set-string=tunnel=disabled \
    --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56 \
    --helm-set-string=endpointRoutes.enabled=true \
    --helm-set=encryption.enabled=true \
    --helm-set=encryption.type=ipsec
```

Run the conn-disrupt test (contrarily to the CI workflow, we run this test only):

```
./cilium-cli connectivity test --include-conn-disrupt-test \
    --include-unsafe-tests \
    --test no-interrupted-connections \
    --debug \
    --flush-ct
```

Prepare the conn-disrupt test:

```
./cilium-cli connectivity test --include-conn-disrupt-test --conn-disrupt-test-setup
```

Downgrade:

```
./cilium-cli upgrade \
    --wait \
    --chart-directory=./cilium-v1.12/install/kubernetes/cilium/ \
    --helm-set=debug.enabled=true \
    --helm-set=debug.verbose=envoy \
    --helm-set=hubble.eventBufferCapacity=65535 \
    --helm-set=bpf.monitorAggregation=none \
    --helm-set=cluster.name=default \
    --nodes-without-cilium=kind-worker3 \
    --helm-set-string=kubeProxyReplacement=disabled \
    --set='bpfClockProbe=false,cni.uninstall=false' \
    --helm-set=image.repository=quay.io/cilium/cilium-ci \
    --helm-set=image.tag=v1.12 \
    --helm-set=image.useDigest=false \
    --helm-set=operator.image.repository=quay.io/cilium/operator \
    --helm-set=operator.image.suffix=-ci \
    --helm-set=operator.image.tag=v1.12 \
    --helm-set=operator.image.useDigest=false \
    --helm-set=hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci \
    --helm-set=hubble.relay.image.tag=v1.12 \
    --helm-set=hubble.relay.image.useDigest=false \
    --helm-set-string=tunnel=disabled \
    --helm-set-string=autoDirectNodeRoutes=true \
    --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 \
    --helm-set-string=tunnel=disabled \
    --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56 \
    --helm-set-string=endpointRoutes.enabled=true \
    --helm-set=encryption.enabled=true \
    --helm-set=encryption.type=ipsec
```

Run the conn-disrupt-test (contrarily to the CI workflow, we run this test only):

```
./cilium-cli connectivity test --include-conn-disrupt-test \
    --include-unsafe-tests \
    --test no-interrupted-connections \
    --debug \
    --flush-ct
```

---

</details>

Now I'm trying to investigate what's happening to the connection.

**Comment by qmonnet** [comment]
I'm getting the following logs with pwru:

```
               SKB    CPU          PROCESS                     FUNC
[...]
0xffff952e06e96ae8      5 [<empty>(439975)]               __netif_rx netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]        netif_rx_internal netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]       enqueue_to_backlog netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]      __netif_receive_skb netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)] __netif_receive_skb_one_core netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]                   ip_rcv netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]              ip_rcv_core netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]       tcp_v4_early_demux netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]     ip_route_input_noref netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]      ip_route_input_slow netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]      fib_validate_source netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]    __fib_validate_source netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]         ip_local_deliver netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]  ip_local_deliver_finish netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=308 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]  ip_protocol_deliver_rcu netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]        raw_local_deliver netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]             raw_v4_input netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]               tcp_v4_rcv netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]   __inet_lookup_listener netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]       inet_lhash2_lookup netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]       inet_lhash2_lookup netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]           tcp_v4_fill_cb netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]        tcp_v4_send_reset netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]    ip_send_unicast_reply netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]        __ip_options_echo netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)] security_skb_classify_flow netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
[some other SKB processed here]
0xffff952e06e96ae8      5 [<empty>(439975)] kfree_skb_reason(SKB_DROP_REASON_NO_SOCKET) netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]   skb_release_head_state netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]         skb_release_data netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]            skb_free_head netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
0xffff952e06e96ae8      5 [<empty>(439975)]             kfree_skbmem netns=4026538517 mark=0x0 iface=64(eth0) proto=0x0800 mtu=1500 len=288 10.244.2.21:8000->10.244.2.78:60154(tcp)
[...]
```

The process is `tcd-server` - not sure [why it shows as `<empty>`](https://github.com/cilium/pwru/issues/312) - although it's the client, `test-conn-disrupt-client-7897ff8cbf-9dxnt`, that detected an interrupted flow and restarted.

I'm not sure yet what this `SKB_DROP_REASON_NO_SOCKET` means but I'll dig that way.

[Full log](https://github.com/cilium/pwru/files/13979361/pwru.log)

**Comment by jschwinger233** [comment]
@qmonnet `SKB_DROP_REASON_NO_SOCKET` usually means there is no existing socket (to be specific, TCP socket in this case) that matches skb tuple, so no socket can receive this skb although routing decision says this skb belongs to this host.

In my experience, this can happen because of missing or unexpected NAT. 

I went thru the full pwru log, it looks like the original request was `10.244.2.78:60154->10.96.216.90:8000(tcp)` in source pod, and `from_container@lxc291c9046a208` turned that request into `10.244.2.78:60154->10.244.2.21:8000(tcp)`. Obviously, the reply packet should be performed rev-NAT somewhere, but we didn't see that, the dropped packet has tuple `10.244.2.21:8000->10.244.2.78:60154(tcp)`, while the socket in the source pod can only match `10.96.216.90:8000->10.244.2.78:60154(tcp)`. Therefore the direct cause is missing rev-NAT, while the root cause in my opinion might be something deeper, like bpf map migration issue(

**Comment by qmonnet** [comment]
Thanks Gray, this is helpful!

I keep reproducing (not consistently) on downgrades (mostly) and upgrades (seldom), and I'm trying to understand what's going on, especially regarding NAT. I've collected sysdumps before and after a downgrade that caused the test to fail (and similarly for a downgrade that did not break the connection). I don't have much more so far.

One interesting thing though: I also managed to reproduce _with encryption disabled_, so this is unlikely related to IPsec itself.

**Comment by qmonnet** [comment]
### Found it! (I hope)

So thinking more about the missing NAT, I've come to the conclusion that this flake has probably the same root cause as https://github.com/cilium/cilium/issues/29351, and should be fixed in https://github.com/cilium/cilium/commit/3a4deb3f14c59300aa7aa92b81d31b20e5fb38a8 from https://github.com/cilium/cilium/pull/29898.

### What root cause?

See https://github.com/cilium/cilium/commit/3a4deb3f14c59300aa7aa92b81d31b20e5fb38a8 for details. In v1.13 we were sometimes removing entries from the ipset, in the node manager, on node updates. As a consequence, the node IP is not excluded from masquerading, when in fact it should be. As described by Gray, this results in the request to the server being masqueraded, but the reply is not. When receiving the reply, the client doesn't find the expected socket and the connection breaks with `SKB_DROP_REASON_NO_SOCKET`.

### How can you tell?

I collected sysdumps before and after upgrades/downgrades when reproducing the flakes. I can confirm that the relevant ipset entries where not present. Here is a list of the nodes _after_ a downgrade during which the test failed: note that most clients restarted.

```
NAMESPACE            NAME                                         READY   STATUS    RESTARTS      AGE     IP             NODE                 NOMINATED NODE   READINESS GATES
cilium-test          test-conn-disrupt-client-7897ff8cbf-2gq6h    1/1     Running   0             3m48s   10.244.1.51    kind-worker          <none>           <none>
cilium-test          test-conn-disrupt-client-7897ff8cbf-97km6    1/1     Running   1 (46s ago)   3m48s   10.244.2.101   kind-worker2         <none>           <none>
cilium-test          test-conn-disrupt-client-7897ff8cbf-r67k4    1/1     Running   1 (46s ago)   3m48s   10.244.2.81    kind-worker2         <none>           <none>
cilium-test          test-conn-disrupt-client-7897ff8cbf-sxnxb    1/1     Running   1 (63s ago)   3m48s   10.244.0.218   kind-control-plane   <none>           <none>
cilium-test          test-conn-disrupt-client-7897ff8cbf-twsts    1/1     Running   1 (63s ago)   3m48s   10.244.0.16    kind-control-plane   <none>           <none>
cilium-test          test-conn-disrupt-server-7dbd487c47-d7jr6    1/1     Running   0             3m53s   10.244.0.250   kind-control-plane   <none>           <none>
cilium-test          test-conn-disrupt-server-7dbd487c47-dd69l    1/1     Running   0             3m53s   10.244.2.99    kind-worker2         <none>           <none>
cilium-test          test-conn-disrupt-server-7dbd487c47-mt6d5    1/1     Running   0             3m53s   10.244.1.36    kind-worker          <none>           <none>
```

Here is the corresponding IPv4 ipset, _before_ downgrade:

```
Name: cilium_node_set_v4
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 256
References: 1
Number of entries: 1
Members:
172.22.0.5
```

`172.22.0.5` is the IP for node `kind-worker`, which explains that the client on that node didn't break the connection and restart, whereas other nodes miss the ipset entry and failed to maintain the connection (and restarted during the connectivity test as a consequence).

### But you said it was fixed?

It's fixed in the code, but there are a number of things to consider here.

- Only branch v1.13 was ever affected by this bug. See https://github.com/cilium/cilium/commit/cbe30378f752eb0295426a0e6bae34b4c7292e67 (end of commit log) for details. On this branch, it was fixed in https://github.com/cilium/cilium/commit/3a4deb3f14c59300aa7aa92b81d31b20e5fb38a8.
- But the CI workflow we consider is about upgrade/downgrade, which means that the flake can also occur on v1.12 and v1.14 when we upgrade/downgrade to a buggy v1.13.
- What is “a buggy v1.13”? Given that the workflow on v1.12 and v1.14 updates/downgrades to the latest v1.13 release, this is any patch release that does _not_ contain the fix. As of today, we haven't published a release with the fix for v1.13 - we only started to prepare one last week, to be published soon. In the meantime, the workflows on v1.12 and v1.14 kept upgrading/downgrading to a version with the bug, and hitting the flake.
- Given that v1.14 and above have never been affected, we've not observed this flake on the v1.15 or main branches (to my knowledge).

### But why don't we observe `node-to-node-encryption` anymore, if it's the same root cause?

This check has been disabled, until we release a new v1.13 version with the fix.

### But why didn't we observe both the `node-to-node-encryption` and `conn-disrupt-test` flakes at the same time, if the cause is the same?

A failure in `conn-disrupt-test` translates into a client or server being terminated and restarted during the downgrade (or upgrade). The new, fresh instance likely contains the right set of ipset entries, and the `node-to-node-encryption` test succeeds (or would succeed, before we disabled the check, obviously).

### By the way...

Looks like if I failed to reproduce for so long with v1.13, this is because I used a recent commit that included the fix. When [I tidied up my script to write down my commands here last week](https://github.com/cilium/cilium/issues/28088#issuecomment-1898691806), I switched back to an older commit that I used to debug the `node-to-node-encryption` flake, and that did not contain the fix.

### What do we do now?

Nothing for now, I am hopeful that the flake should stop happening after the v1.13 patch release. If it still happens after that, then it's bad news and there's something else going on.

**Comment by julianwiedmann** [comment]
> * What is “a buggy v1.13”? Given that the workflow on v1.12 and v1.14 updates/downgrades to the latest v1.13 release, this is any patch release that does _not_ contain the fix. As of today, we haven't published a release with the fix for v1.13 - we only started to prepare one last week, to be published soon. In the meantime, the workflows on v1.12 and v1.14 kept upgrading/downgrading to a version with the bug, and hitting the flake.

Double-checking - how does this match up with 502bbc7bcc ? Are we still seeing the IPsec upgrade workflow fail with this error, in branches that have 502bbc7bcc?

**Comment by qmonnet** [comment]
> Double-checking - how does this match up with [502bbc7](https://github.com/cilium/cilium/commit/502bbc7bcc19c8a43c7a94a8ad9a16b1fb666e11) ? Are we still seeing the IPsec upgrade workflow fail with this error, in branches that have [502bbc7](https://github.com/cilium/cilium/commit/502bbc7bcc19c8a43c7a94a8ad9a16b1fb666e11)?

Let's see. All branches do both `1.x tip -> 1.y PR head -> 1.x tip` and `1.y release -> 1.y PR head -> 1.y release` since https://github.com/cilium/cilium/commit/ed59edc9f34596c871e45430c9378579eed9a12a and backports.

- On v1.12: Neither v1.11 nor v1.12 should be affected, so we shouldn't observe the flake at all. There were reports in the past though, I hope they were caused by one of the other flakes that we've addressed :grimacing:.
- On v1.13: I suppose we should no longer observe the flake now that the branch contains the fix.
- On v1.14: We would have flakes occurring until the creation of the latest 1.13 patch release, we should no longer observe any after that.

The latest report I've seen, about v1.12, is indeed a concern. The commit that (I think) introduced the issue on v1.13, 454df0c065bd, is not present there, but maybe ipset entries management was problematic before that. I'll do more testing on that branch if we see new reports.

**Comment by qmonnet** [comment]
I've been focusing on the IPsec upgrade/downgrade workflow so far. As far as I know, the issue has been fixed for that workflow on branches v1.13 and newer (but it remains on v1.12, we don't know why at this stage).

https://github.com/cilium/cilium/actions/runs/7698872003/job/20979193377 from Sebastian is unrelated (wrong diagnostic), it's a failure on `no-unexpected-packet-drops` and not `no-interrupted-connections`, this is tracked elsewhere.

Looking at the recent links above, I agree with you, it looks like `no-interrupted-connections` has been occurring on the Cluster Mesh upgrade/downgrade workflow. This makes 4 reports so far (Pabla's workflow had two failures):

- https://github.com/cilium/cilium/actions/runs/7712912167/job/21021566215 (#30528)
    - 2024-01-30
    - job config: `1, disabled, iptables, false`
    - step: post-downgrade to 1.15.0-rc.1

- https://github.com/cilium/cilium/actions/runs/7898508466/job/21556052907 (#30732)
    - 2024-02-14
    - job config: `2, disabled, none, false`
    - step: post-downgrade to 1.15.0

- https://github.com/cilium/cilium/actions/runs/8016451099/job/21898409307 (#30885)
    - 2024-02-23
    - job config: `1, disabled, iptables, false, 255`
    - step: post-downgrade to 1.15.1

I have not investigated these failures for the Cluster Mesh workflow. Given that we assume the issue to be fixed on v1.13+ for the IPsec workflow, I suppose the root cause is a different one.

For clarity, we should track it elsewhere. Given that:

- On IPsec workflows, the issue is considered fixed, save for 1.12 which reaches end-of-life
- The current issue has been used for a variety of flakes over time, and it is becoming difficult to track here which workflow is failing under what conditions
 
**We will not track Cluster Mesh upgrade/downgrade failures here, I will close the current issue and open a new dedicated one**.

**Comment by qmonnet** [comment]
To report any new occurrences on the _Cluster Mesh upgrade_ workflow, please link to https://github.com/cilium/cilium/issues/30964 instead of this issue.

**Comment by giorio94** [comment]
Hit a `no-interrupted-connections` failure affecting the IPsec upgrade/downgrade workflow (on upgrade).

Hit on: https://github.com/cilium/cilium/pull/31550
Link: https://github.com/cilium/cilium/actions/runs/8387397247/job/22969523699
Sysdump: [cilium-sysdump-ipsec-upgrade-2-20240322-082647.zip](https://github.com/cilium/cilium/files/14720621/cilium-sysdump-ipsec-upgrade-2-20240322-082647.zip)

This PR slightly touches the IPSet logic, but changes are effectively a no-op as the filter is not configured at the moment, hence I don't see how it could be the cause. I tried reproducing locally but I never succeeded in triggering a failure on agent restart. I was also mildly suspecting this to be related to https://github.com/cilium/cilium/issues/31537 (based on the IPSet changes), but I never succeeded in reproducing even in this case.

**Comment by learnitall** [comment]
Hit `no-interrupted-connections` failure impacting `ci-e2e-upgrade`.

Hit on: #32231
Links:
  * Kernel 5.10, iptables, no kpr, no tunnel, endpoint routes enabled: https://github.com/cilium/cilium/actions/runs/8910557015/job/24470065819
  * Kernel rhel-8, iptables, no kpr, vxlan, endpoint routes enabled: https://github.com/cilium/cilium/actions/runs/8910557015/job/24470065819
 
Sysdump: https://github.com/cilium/cilium/actions/runs/8910557015/artifacts/1464108506 (too large to upload)

PR touches logic related to the parsing of CNPs.

**Comment by aditighag** [comment]
Hit on - https://github.com/cilium/cilium/actions/runs/8928755350/job/24526895882.

**Comment by giorio94** [comment]
Hit on https://github.com/cilium/cilium/pull/32336 as well
Link: https://github.com/cilium/cilium/actions/runs/8936891031/job/24548106186

**Comment by julianwiedmann** [comment]
:wave: if you arrive here with a disrupted connection on downgrade from `main` to` v1.15` with `bpf-next`, you're potentially affected by https://github.com/cilium/cilium/pull/30103#issuecomment-2092754226.

**Comment by brb** [comment]
@giorio94 @julianwiedmann Can we close this issue, and if https://github.com/cilium/cilium/pull/30103#issuecomment-2092754226 still occurs, we can open another one?

**Comment by giorio94** [comment]
> @giorio94 @julianwiedmann Can we close this issue, and if [#30103 (comment)](https://github.com/cilium/cilium/pull/30103#issuecomment-2092754226) still occurs, we can open another one?

Yup, makes sense to me.
