### ISSUE TITLE
GatewayClass resource never gets Accepted in k0s cluster

### ISSUE THREAD

**Issue by zsparal** [cilium/cilium#30474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In a freshly installed k0s cluster, I tried setting up a minimal example that uses the Gateway API to:

1. Set up a few basic services
2. Set up a Gateway and some HTTPRoutes to make them accessible
3. After everything is deployed, no LoadBalancer is created for the Gateway
   - The `cilium` GatewayClass resource is stuck in `ACCEPTED=Unkown` status
   - The created Gateway is stuck in `PROGRAMMED=Unknown` status

My original setup is a bit more complex, but I tried just following the [HTTP Example] (https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/http/) on a fresh cluster and it resulted in the same thing.

I used the same Cilium setup with Emissary for the ingress (but without the Gateway API) and it worked fine. I also tried deploying Contour using its dynamic Gateway API provisioning, which also worked.

## GatewayClass:
```yaml
kc get gatewayclasses.gateway.networking.k8s.io -o yaml
apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1
  kind: GatewayClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"gateway.networking.k8s.io/v1","kind":"GatewayClass","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"Helm","helm.toolkit.fluxcd.io/name":"cilium","helm.toolkit.fluxcd.io/namespace":"kube-system"},"name":"cilium"},"spec":{"controllerName":"io.cilium/gateway-controller"}}
      meta.helm.sh/release-name: cilium
      meta.helm.sh/release-namespace: kube-system
    creationTimestamp: "2024-01-27T18:12:45Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: cilium
      helm.toolkit.fluxcd.io/namespace: kube-system
    name: cilium
    resourceVersion: "3721"
    uid: 0173bb2b-5ca0-4d28-a1d8-cda7ee66d16f
  spec:
    controllerName: io.cilium/gateway-controller
  status:
    conditions:
    - lastTransitionTime: "1970-01-01T00:00:00Z"
      message: Waiting for controller
      reason: Waiting
      status: Unknown
      type: Accepted
kind: List
metadata:
  resourceVersion: ""
```

### Cilium Version

1.14.6 and 1.15.0-rc.1

### Kernel Version

Linux lenovo 5.15.146.1-microsoft-standard-WSL2+ #1 SMP Fri Jan 26 21:41:48 CET 2024 x86_64 x86_64 x86_64 GNU/Linux

(it is compiled with all the modules listed in Cilium's requirements)

### Kubernetes Version

Client Version: v1.28.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6+k0s

Single node k0s deployment, config:

```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: ripple
spec:
  api:
    address: 172.28.36.212
    sans:
      - 172.28.36.212
      - 172.19.0.1
      - 172.18.0.1
      - 172.17.0.1
      - fe80::215:5dff:fe4f:698
      - fe80::42:43ff:fee9:b321
      - fc00:f853:ccd:e793::1
      - fe80::1
  extensions:
    storage:
      type: openebs_local_storage
  network:
    provider: custom
    kubeProxy:
      disabled: true
  telemetry:
    enabled: false
```

### Sysdump

[cilium-sysdump-20240127-192207.zip](https://github.com/cilium/cilium/files/14073337/cilium-sysdump-20240127-192207.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zsparal** [comment]
Update: It seems like that if I shut down the VM and start it back up again, it works, but never one the first try.

**Comment by sayboras** [comment]
Could it be the case that gateway api is enabled after first installation, and cilium operator is not restarted? 

I have checked the operator log, normally we should see enable-gateway-api flag as true in the config dump part.

**Comment by zsparal** [comment]
I deployed the upgrade via Flux and I thought I set it up correctly to do a rolling restart but it seems like I did not succeed 🤦 Thanks for the help, I managed to fix it!

**Comment by somnathbm** [comment]
@zsparal How did you managed to fix the issue?
I'm still getting the cilium Gateway class being stuck at UNKNOWN forever, despite restarting the cilium controller pods/worker nodes.

My cluster is hosted on EKS without VPC-CNI plugin.
K8s version 1.30
cilium version 1.16.4

PS - Gateway stable + experimental CRDs were before installing cilium via Helm.

How to get this controller working?

**Comment by elJoeyJojo** [comment]
> [@zsparal](https://github.com/zsparal) How did you managed to fix the issue? I'm still getting the cilium Gateway class being stuck at UNKNOWN forever, despite restarting the cilium-operator pods/worker nodes.
> 
> My cluster is hosted on EKS without VPC-CNI plugin. K8s version 1.30 cilium version 1.16.4
> 
> PS - Gateway stable + experimental CRDs were before installing cilium via Helm.
> 
> How to get this controller working?

you figured this out ? is this gateway supposed to provision an AWS Load Balancer or something?

**Comment by ITBeyder** [comment]
why it closed ? did you manage to fix it ?

**Comment by blackdesert575** [comment]
Any updates?
