### ISSUE TITLE
Requests to GatewayAPI and L2 backed service times out

### ISSUE THREAD

**Issue by ekarlso** [cilium/cilium#30510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When doing requests connection is allowed but Envoy times out

After checking for similar issues something like the below might be related.
https://github.com/cilium/cilium/issues/28837

```
curl 172.16.53.202:30433 -vvv --connect-timeout 2
* Rebuilt URL to: 172.16.53.202:30433/
*   Trying 172.16.53.202...
* TCP_NODELAY set
* Connected to 172.16.53.202 (172.16.53.202) port 30433 (#0)
> GET / HTTP/1.1
> Host: 172.16.53.202:30433
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Sun, 28 Jan 2024 14:20:30 GMT
< server: envoy
< 
* Connection #0 to host 172.16.53.202 left intact
upstream connect error or disconnect/reset before headers. reset reason: connection timeout% 
```

```
---
k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: false

bpf:
  masquerade: true

# ipMasqAgent:
#   enabled: true

devices:
  - eth0

ipv4:
  enabled: true
ipv6:
  enabled: false

enableIPv4BIGTCP: false
enableIPv4Masquerade: true

enableIPv6BIGTCP: false
enableIPv6Masquerade: false

localRedirectPolicy: true

installNoConntrackIptablesRules: false

nodeInit:
  enabled: true

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 172.17.16.0/20
    clusterPoolIPv4MaskSize: 26

    clusterPoolIPv6PodCIDRList: []
    clusterPoolIPv6MaskSize: 128
    autoCreateCiliumPodIPPools: {}

labels: k8s:!io.cilium.k8s.namespace.labels.kustomize.*

debug:
  enabled: false
  verbose: policy

hostPort:
  enabled: false

nodePort:
  enabled: true

enableIdentityMark: false
remoteNodeIdentity: true
wellKnownIdentities:
  enabled: true

endpointStatus:
  enabled: true
  status: policy health controllers log state

hostFirewall:
  enabled: true # enable host policies
extraConfig:
  allow-localhost: policy # enable policies for local host

hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true

    enabled:
      - drop
      - tcp
      - flow
      - flows-to-world
      - icmp
      - httpV2
      - port-distribution

  relay:
    enabled: true
    rollOutPods: true

    prometheus:
      enabled: true

    securityContext:
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
  ui:
    enabled: true
    rolloutPods: true

    backend:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65535
        capabilities:
          drop:
            - ALL

    frontend:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65535
        capabilities:
          drop:
            - ALL

prometheus:
  enabled: true

routingMode: native
ipv4NativeRoutingCIDR: "172.17.16.0/20"
autoDirectNodeRoutes: true

kubeProxyReplacement: true
k8sServiceHost: 172.16.53.193
k8sServicePort: 6443

ingressController:
  enabled: false
  default: true

gatewayAPI:
  enabled: true

l2announcements:
  enabled: true

rolloutCiliumPods: true

image:
  repository: quay.io/cilium/cilium-ci
  tag: 5c768a4eddbb71662dc8573c0e63f910a64477df
  useDigest: false

operator:
  replicas: 2
  rolloutPods: true

  prometheus:
    enabled: false

  securityContext:
    seccompProfile:
      type: RuntimeDefault
    allowPrivilegeEscalation: false
    # runAsNonRoot: true
    # runAsUser: 65534
    capabilities:
      drop:
        - ALL
  image:
    repository: quay.io/cilium/operator
    suffix: "-ci"
    tag: 5c768a4eddbb71662dc8573c0e63f910a64477df
    useDigest: false


policyEnforcementMode: default
policyAuditMode: false
# policyCIDRMatchMode: nodes

k8sClientRateLimit:
  qps: 45
  burst: 60

cgroup:
  autoMount:
    enabled: true
  hostRoot: /sys/fs/cgroup

securityContext:
  # -- User to run the pod with
  runAsUser: 0
  # -- Run the pod with elevated privileges
  privileged: false

  capabilities:
    # -- Capabilities for the `mount-cgroup` init container
    mountCgroup:
      # Only used for 'mount' cgroup
      - SYS_ADMIN
      # Used for nsenter
      - SYS_CHROOT
      - SYS_PTRACE
    # -- capabilities for the `apply-sysctl-overwrites` init container
    applySysctlOverwrites:
      # Required in order to access host's /etc/sysctl.d dir
      - SYS_ADMIN
      # Used for nsenter
      - SYS_CHROOT
      - SYS_PTRACE
    # -- Capabilities for the `cilium-agent` container
    ciliumAgent:
      # Use to set socket permission
      - CHOWN
      # Used to terminate envoy child process
      - KILL
      # Used since cilium modifies routing tables, etc...
      - NET_ADMIN
      # Used since cilium creates raw sockets, etc...
      - NET_RAW
      # Used since cilium monitor uses mmap
      - IPC_LOCK
      # We need it for now but might not need it for >= 5.11 specially
      # for the 'SYS_RESOURCE'.
      # In >= 5.8 there's already BPF and PERMON capabilities
      - SYS_ADMIN
      # Could be an alternative for the SYS_ADMIN for the RLIMIT_NPROC
      - SYS_RESOURCE
      # Both PERFMON and BPF requires kernel 5.8, container runtime
      # cri-o >= v1.22.0 or containerd >= v1.5.0.
      # If available, SYS_ADMIN can be removed.
      - PERFMON
      - BPF
      # Allow discretionary access control (e.g. required for package installation)
      - DAC_OVERRIDE
      # Allow to set Access Control Lists (ACLs) on arbitrary files (e.g. required for package installation)
      - FOWNER
      # Allow to execute program that changes GID (e.g. required for package installation)
      - SETGID
      # Allow to execute program that changes UID (e.g. required for package installation)
      - SETUID
    # -- Capabilities for the `clean-cilium-state` init container
    cleanCiliumState:
      # Most of the capabilities here are the same ones used in the
      # cilium-agent's container because this container can be used to
      # uninstall all Cilium resources, and therefore it is likely that
      # will need the same capabilities.
      # Used since cilium modifies routing tables, etc...
      - NET_ADMIN
      # We need it for now but might not need it for >= 5.11 specially
      # for the 'SYS_RESOURCE'.
      # In >= 5.8 there's already BPF and PERMON capabilities
      - SYS_ADMIN
      # Could be an alternative for the SYS_ADMIN for the RLIMIT_NPROC
      - SYS_RESOURCE
      # Both PERFMON and BPF requires kernel 5.8, container runtime
      # cri-o >= v1.22.0 or containerd >= v1.5.0.
      # If available, SYS_ADMIN can be removed.
      - PERFMON
      - BPF
```

### Cilium Version

1.15.rc1 - 5c768a4eddbb71662dc8573c0e63f910a64477df

### Kernel Version

5.15.0-202.135.2.el9uek.x86_64

### Kubernetes Version

v1.28.5+rke2r1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ekarlso** [comment]
Also tried setting
```yaml
bpf:
  masquerade: true
  hostLegacyRouting: true
```

with combinations of
```yaml
installNoConntrackIptablesRules: true
```

```
hubble observe --ip 192.168.1.43 -f
Handling connection for 4245
Jan 29 19:45:05.835: 192.168.1.43:60450 (world) <> 172.16.53.200 (host) pre-xlate-rev TRACED (TCP)
Jan 29 19:45:10.836: 192.168.1.43:60450 (ingress) -> cilium-gw-system/cilium-gateway-default:30603 (world) http-request FORWARDED (HTTP/1.1 GET http://demo.foo.com/)
Jan 29 19:45:10.837: 192.168.1.43:60450 (ingress) <- cilium-gw-system/cilium-gateway-default:30603 (world) http-response FORWARDED (HTTP/1.1 503 4999ms (GET http://demo.foo.com
```

**Comment by ekarlso** [comment]
I tested image ac42dc9c3899d5bcc21fda3e72f6687e5b5c128f now on RKE2 and it's still the same

**Comment by acelinkio** [comment]
I have been tracking a couple different tickets for connection errors using Cilium ingress/gateway controllers.  Going to post some of the steps I took when investigating.

* Manually load kernel modules to prevent `upstream reset: reset reason: connection failure`.  https://github.com/cilium/cilium/issues/25021#issuecomment-1699969830 
```sh
modprobe iptable_raw
modprobe xt_socket
cat << 'EOF' > /etc/modules-load.d/cilium.conf
xt_socket
iptable_raw
EOF
```

* Set gateway allowedRoutes namespaces All (until 1.15.1) to prevent `HTTPRoute is not allowed to attach to this Gateway due to namespace restrictions` https://github.com/cilium/cilium/issues/30085
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      kinds:
        - kind: HTTPRoute
      namespaces:
        from: All
  - protocol: HTTPS
    port: 443
    name: https
    tls:
      certificateRefs:
      - kind: Secret
        name: wildcard-production
        namespace: cilium-secrets
    allowedRoutes:
      namespaces:
        from: All
```

I am actively troubleshooting `upstream connect error or disconnect/reset before headers. reset reason: connection timeout` errors inside of my cluster.  So far what I have discovered is that this only impacts one node at a time.  Any connection coming into that Cilium gateway is unable to deliver traffic to a pod hosted on that node.  I am able to identify the impacted Cilium pod from logs like `level=info msg="[cilium.bpf_metadata: IPv4 conntrack map global lookup failed: Success" subsys=envoy-filter threadID=255` messages.`  I found a workaround by having this 'bad cilium daemonset pod' end up on a Kubernetes controller node that is not responsible for hosting a website.

Useful issues I found in the same ballpark:
* https://github.com/cilium/cilium/issues/30510 (this issue)
* https://github.com/cilium/cilium/issues/30581
* https://github.com/cilium/cilium/issues/29967
* https://github.com/cilium/cilium/issues/29928
* https://github.com/cilium/cilium/issues/20942
* https://github.com/cilium/cilium/issues/28979



Hey @ekarlso.  Could you try seeing if this problem is similar?  Try connecting to websites inside of your gateway.  See if all of the connection errors are limited to one node inside of your cluster.

**Comment by TECHNOFAB11** [comment]
There is also my follow up issue from #28979: #29406

Tried to debug the stuff there a bit, but I had the same thought that it just happens when both are on the same node

**Comment by acelinkio** [comment]
Following up on this,

Updated to use newer CI images and not seeing anymore `upstream connect error or disconnect/reset before headers. reset reason: connection timeout` errors like I was before.   Appears that https://github.com/cilium/cilium/pull/30816 may have been the solution.

This was tested with images from https://github.com/cilium/cilium/actions/runs/7941152929/job/21683197687 using the following helm values.
```yaml
image:
  override: "quay.io/cilium/cilium-ci:48bd2ac9eeabbbde42a35a1552952d72b6108cf0"
operator:
  image:
    override: "quay.io/cilium/operator-generic-ci:48bd2ac9eeabbbde42a35a1552952d72b6108cf0"
```

The fix appears to happen between these two commits https://github.com/cilium/cilium/compare/d1834ba2cf8d33861e077a1226143c3f7a71c2d0...48bd2ac9eeabbbde42a35a1552952d72b6108cf0

**Comment by RyanMnM** [comment]
I just managed to fix a similar issue that was giving me results akin to these by disabling Masquerade on my firewall/firewalld setup on the nodes. I imagine some sort of conflict / double Masquerade with BPF Masquerade.

**Comment by maxpain** [comment]
Any update?

**Comment by acelinkio** [comment]
Upgraded to 1.15.2 and started facing issues again.

> So far what I have discovered is that this only impacts one node at a time. Any connection coming into that Cilium gateway is unable to deliver traffic to a pod hosted on that node. I am able to identify the impacted Cilium pod from logs like level=info msg="[cilium.bpf_metadata: IPv4 conntrack map global lookup failed: Success" subsys=envoy-filter threadID=255 messages.` I found a workaround by having this 'bad cilium daemonset pod' end up on a Kubernetes controller node that is not responsible for hosting a website.

Not quite sure what to say at this point.  Looks like there might be other changes from the CI image from main I was using.  https://github.com/cilium/cilium/compare/v1.15.2...48bd2ac9eeabbbde42a35a1552952d72b6108cf0.  I assume 1.16.0 will catch all of the commits from main when it eventually releases.

**Comment by larivierec** [comment]
I confirm this issue is still present on 15.2 and 16.0-pre0

**Comment by DennisGlindhart** [comment]
I had the same issue and setting `enable-endpoint-routes: true` (helm-value: `endpointRoutes.enabled`) seem to have solved it for me.

I'm running a single node with IPv6 only, but maybe it is useful in other cases too.

**Comment by drawdy** [comment]
The problem is very serious. The network is very unstable. We have to restart cilium frequetly.

Cilim: v1.15.3

**Comment by a114383** [comment]
I'm also seeing something similar, I have one pod running through gateway API w/ a load balancer into EKS.  I had previously been trying to debug this one with v1.15.0 of cilium, then upgraded once I read this to `stable` (v1.15.5).  But still getting the error:

> upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason:

![Screenshot 2024-06-04 at 1 32 23 PM](https://github.com/cilium/cilium/assets/32073052/595f58e2-81d6-409c-b6aa-2ff2325b98a4)

It seems to happen when the load balancer routes to the host which has the pod.

Here are the closest to the problem i've been able to find:

#### Hubble Observe

```
Jun  4 17:20:19.892: [36m100.64.236.203:[33m43065[0m[0m [35m(ingress)[0m <- [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-stack [32mFORWARDED[0m (TCP Flags: SYN, ACK)
Jun  4 17:20:19.898: [36m100.64.73.48[0m [35m(host)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (ICMPv4 TimeExceeded(TTLExceeded))
Jun  4 17:20:22.562: [36m100.64.149.18:[33m45389[0m[0m [35m(remote-node)[0m <- [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-stack [32mFORWARDED[0m (TCP Flags: SYN, ACK)
Jun  4 17:20:23.192: [36m100.65.104.25:[33m39603[0m[0m [35m(remote-node)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (TCP Flags: ACK, FIN)
Jun  4 17:20:23.192: [36m100.65.104.25:[33m39603[0m[0m [35m(remote-node)[0m <- [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-stack [32mFORWARDED[0m (TCP Flags: ACK, FIN)
Jun  4 17:20:23.192: [36m100.65.104.25:[33m39603[0m[0m [35m(remote-node)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (TCP Flags: ACK)
Jun  4 17:20:25.122: [36m100.64.149.18:[33m34607[0m[0m [35m(remote-node)[0m <- [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-stack [32mFORWARDED[0m (TCP Flags: SYN, ACK)
Jun  4 17:20:25.746: [36m100.65.104.25:[33m37095[0m[0m [35m(remote-node)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (TCP Flags: ACK, FIN)
Jun  4 17:20:25.746: [36m100.65.104.25:[33m37095[0m[0m [35m(remote-node)[0m <- [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-stack [32mFORWARDED[0m (TCP Flags: ACK, FIN)
Jun  4 17:20:25.746: [36m100.65.104.25:[33m37095[0m[0m [35m(remote-node)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (TCP Flags: ACK)
Jun  4 17:20:26.155: [36m100.64.162.163:[33m36589[0m[0m [35m(remote-node)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (TCP Flags: ACK, PSH)
Jun  4 17:20:26.156: [36m100.64.162.163:[33m36589[0m[0m [35m(remote-node)[0m <- [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-stack [32mFORWARDED[0m (TCP Flags: ACK, PSH)
Jun  4 17:20:27.120: [36m100.64.2.211:[33m38155[0m[0m [35m(remote-node)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (TCP Flags: ACK, FIN)
Jun  4 17:20:27.120: [36m100.64.2.211:[33m38155[0m[0m [35m(remote-node)[0m <- [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-stack [32mFORWARDED[0m (TCP Flags: ACK, FIN)
Jun  4 17:20:27.120: [36m100.64.2.211:[33m38155[0m[0m [35m(remote-node)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (TCP Flags: ACK)
Jun  4 17:20:27.427: [36m100.64.236.203:[33m38249[0m[0m [35m(ingress)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (TCP Flags: SYN)
Jun  4 17:20:27.427: [36m100.64.236.203:[33m38249[0m[0m [35m(ingress)[0m <- [36mqwerty-ns/qwerty-d8c958996-d2jb4:[33m80[0m[0m [35m(ID:52077)[0m to-stack [32mFORWARDED[0m (TCP Flags: SYN, ACK)
Jun  4 17:20:27.435: [36m100.64.73.48[0m [35m(host)[0m -> [36mqwerty-ns/qwerty-d8c958996-d2jb4[0m [35m(ID:52077)[0m to-endpoint [32mFORWARDED[0m (ICMPv4 TimeExceeded(TTLExceeded))
```

#### stern pod logs

```
cilium-kszqp cilium-agent time="2024-06-04T17:13:04Z" level=debug msg="Greeting failed" error="Get \"http://100.64.202.133:4240/hello\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" host="http://100.64.202.133:4240" ipAddr=100.64.202.133 nodeName=l10e1/ip-100-64-2-211.ec2.internal path="Via L3" subsys=health-server
cilium-kszqp cilium-agent time="2024-06-04T17:13:04Z" level=debug msg="Failed to probe: Get \"http://100.64.202.133:4240/hello\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" ipAddr=100.64.202.133 nodeName=l10e1/ip-100-64-2-211.ec2.internal port=4240 subsys=health-server
cilium-kszqp cilium-agent time="2024-06-04T17:13:04Z" level=debug msg="Greeting host" host="http://100.64.162.163:4240" ipAddr=100.64.162.163 nodeName=l10e1/ip-100-64-162-163.ec2.internal path="Via L3" subsys=health-server
cilium-kszqp cilium-agent time="2024-06-04T17:13:04Z" level=debug msg="Pod metadata: {Name:cilium-kszqp Namespace:cilium IPs:[100.64.73.48]}" container-cgroup-id=30743 subsys=cgroup-manager
cilium-kszqp cilium-agent time="2024-06-04T17:13:04Z" level=debug msg="Greeting successful" host="http://100.64.162.163:4240" ipAddr=100.64.162.163 nodeName=l10e1/ip-100-64-162-163.ec2.internal path="Via L3" rtt=1.091698ms subsys=health-server
cilium-kszqp cilium-agent time="2024-06-04T17:13:04Z" level=debug msg="Greeting host" host="http://100.64.132.2:4240" ipAddr=100.64.132.2 nodeName=l10e1/ip-100-64-162-163.ec2.internal path="Via L3" subsys=health-server


### upstream connect reset?

cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] upstream reset: reset reason: connection timeout, transport failure reason: " subsys=envoy-router threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[item added to deferred deletion list (size=1)" subsys=envoy-main threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[item added to deferred deletion list (size=2)" subsys=envoy-main threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] Sending local reply with details upstream_reset_before_response_started{connection_timeout}" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[enableTimer called on 0x143cff545260 for 300000ms, min is 300000ms" subsys=envoy-misc threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] encode headers called: filter=cilium.l7policy status=0" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] encode headers called: filter=envoy.filters.http.grpc_stats status=0" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] encode headers called: filter=envoy.filters.http.grpc_web status=0" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] encoding headers via codec (end_stream=false):" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="':status', '503'" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="'content-length', '91'" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="'content-type', 'text/plain'" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="'date', 'Tue, 04 Jun 2024 17:21:08 GMT'" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="'server', 'envoy'" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] writing 134 bytes, end_stream false" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[enableTimer called on 0x143cff545260 for 300000ms, min is 300000ms" subsys=envoy-misc threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] encode data called: filter=cilium.l7policy status=0" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] encode data called: filter=envoy.filters.http.grpc_stats status=0" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] encode data called: filter=envoy.filters.http.grpc_web status=0" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="Proxy stats not found when updating" PolicyID.L4="2087:egress:TCP:30686" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=2087 identity=8 ipv4=100.64.236.203 ipv6= k8sPodName=/ subsys=endpoint
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="Proxy stats not found when updating" PolicyID.L4="2087:egress:TCP:30686" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=2087 identity=8 ipv4=100.64.236.203 ipv6= k8sPodName=/ subsys=endpoint
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] encoding data via codec (size=91 end_stream=true)" subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] writing 91 bytes, end_stream false" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\",\"StreamId\":\"5759274548406636973\"] Codec completed encoding stream." subsys=envoy-http threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[item added to deferred deletion list (size=3)" subsys=envoy-main threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[item added to deferred deletion list (size=4)" subsys=envoy-main threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[enableTimer called on 0x143cff544d20 for 3600000ms, min is 3600000ms" subsys=envoy-misc threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[not creating a new connection, shouldCreateNewConnection returned false." subsys=envoy-pool threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[item added to deferred deletion list (size=5)" subsys=envoy-main threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[invoking idle callbacks - is_draining_for_deletion_=false" subsys=envoy-pool threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[Erasing idle pool for host 100.64.113.165:80" subsys=envoy-upstream threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[item added to deferred deletion list (size=6)" subsys=envoy-main threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[Pool container empty for host 100.64.113.165:80, erasing host entry" subsys=envoy-upstream threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[clearing deferred deletion list (size=6)" subsys=envoy-main threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] socket event: 2" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] write ready" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] write returns: 225" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="Skipping CiliumEndpoint update because it has not changed" ciliumEndpointName=eds-dss-dyn-test28/eds-dss-product-site-dyn-test28-helm-l10e1-pgr-hugo-7f6475m8chs containerID=8943c24014 containerInterface=eth0 controller="sync-to-k8s-ciliumendpoint (2406)" datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=2406 identity=18825 ipv4=100.64.236.197 ipv6= k8sPodName=eds-dss-dyn-test28/eds-dss-product-site-dyn-test28-helm-l10e1-pgr-hugo-7f6475m8chs subsys=endpointsynchronizer
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="Controller func execution time: 125.712µs" name="sync-to-k8s-ciliumendpoint (2406)" subsys=controller uuid=d57032c6-0b36-4f45-88f6-7ce3703b2d84
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] socket event: 3" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] write ready" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] read ready. dispatch_buffered_data=0" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] read returns: 0" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] remote close" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] closing socket: 0" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="Skipping CiliumEndpoint update because it has not changed" ciliumEndpointName=eds-dss-stratos-dyn-namespace-api/dyn-namespace-api-helm-l10e1-fastapi-dep-b8795d6f6-bjx7v containerID=c44bed907e containerInterface=eth0 controller="sync-to-k8s-ciliumendpoint (1828)" datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=1828 identity=4221 ipv4=100.64.78.177 ipv6= k8sPodName=eds-dss-stratos-dyn-namespace-api/dyn-namespace-api-helm-l10e1-fastapi-dep-b8795d6f6-bjx7v subsys=endpointsynchronizer
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="Controller func execution time: 127.443µs" name="sync-to-k8s-ciliumendpoint (1828)" subsys=controller uuid=b93a8acd-b491-471b-8389-1fd921806b22
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="Processed new health status" status="Status{ModuleID: , Level: OK, Since: 2.056µs ago, Message: }" subsys=hive
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="Controller func execution time: 1.355553ms" name=link-cache subsys=controller uuid=ff54fb00-ff88-4014-be0d-fed39f6e43c1
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] raising connection event 0" subsys=envoy-connection threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] tcp connection on event 0" subsys=envoy-conn_handler threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[[Tags: \"ConnectionId\":\"33\"] adding to cleanup list" subsys=envoy-conn_handler threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[item added to deferred deletion list (size=1)" subsys=envoy-main threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[item added to deferred deletion list (size=2)" subsys=envoy-main threadID=76
cilium-kszqp cilium-agent time="2024-06-04T17:21:08Z" level=debug msg="[clearing deferred deletion list (size=2)" subsys=envoy-main threadID=76
```

**Comment by larssb** [comment]
I was hoping that https://github.com/cilium/cilium/pull/32367 released in v1.15.6 would solve this. Didn't. So what we do to currently solve it is to use `hostLegacyRouting`. This is annoying as that is less performant. But, we can live with it on the clusters whereon we use the Gateway API through Cilium.

**Comment by balous** [comment]
I experience similar problem with ingress controller. I have one replica of nginx and am testing connections to `cilium-ingress` service's nodeports, I found that the node that hosts the nginx pod can't connect.

- cilium version is 1.15.5
- `routingMode` is set to `native` (in `tunnel` mode I don't experience the problem)
- `cilium monitor` on that node logs just nodeport connections, not the connections to the nginx pod
- if I exec into the `cilum-envoy` pod, install `curl` and try to connect to the pod, it always works. Looking at connections inside the pod, I see that envoy is connecting from different source address than curl:

```
root@test2-w1-row-j-s2tfj-g8n9j:/# ss -atnepo 2>/dev/null | grep 90.220
SYN-SENT  0      1                       10.89.90.221:33943                  10.89.90.220:80    users:(("cilium-envoy",pid=7,fd=54)) timer:(on,960ms,3) ino:2276184 sk:127737 fwmark:0x90b00 cgroup:/ <->         
TIME-WAIT 0      0                      10.244.32.158:59394                  10.89.90.220:80    timer:(timewait,14sec,0) ino:0 sk:126a24                                     
```

**Comment by xaviergrandmougin** [comment]
I've also had a similar issue for a while now:
- cilium 1.15.7 and below
- l2 announcements
- gateway-api 1.0.0 standard or experimental crd
- native routing with `bpf.hostLegacyRouting: false`, `bpf.masquerade: true`, and `autoDirectNodeRoutes: true`

I have several gateways, one for each service i want to expose outside the cluster, with a load balancer request for a specific IP. The cilium status is clean.

I experience random connectivity issues with some service behind a gateway (and only those behind a gateway, port forwarding the service is working), sometimes everything is running fine for hours.

The only solution I have right now to to go back to tunnel mode instead of native.

**Comment by balous** [comment]
I set `hostLegacyRouting: true` and it helped. No other change was needed.

**Comment by xaviergrandmougin** [comment]
I'll test again when cilium 1.17 will be released.

**Comment by Jip-Hop** [comment]
Seems like `bpf.hostLegacyRouting: true` is no longer required in 1.17 when using `bpf.masquerade: true`. Just tried with k0s:v1.31.2+k0s, gateway-api v1.2.0 and upcoming cilium version 1.17.0-pre.2 and did not run in to `upstream connect error or disconnect/reset before headers. reset reason: connection timeout` errors any more.

**Comment by xaviergrandmougin** [comment]
Still waiting for cilium 1.17 official release to confirm that the problem is solved.

**Comment by joelMuehlena** [comment]
Still seeing `upstream connect error or disconnect/reset before headers. reset reason: connection timeout` with 1.17.0-rc.2

**Comment by qasmi** [comment]
I have a similar issue :`upstream connect error or disconnect/reset before headers. reset reason: connection timeout`

I m using cilium 1.16.5 with rke2 v1.31.3+rke2r1

My cilium config:

```
    kubeProxyReplacement: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6443

    routingMode: "native" 
    bpf:
      hostLegacyRouting: true 
      masquerade: true 
    autoDirectNodeRoutes: true 

    gatewayAPI:
      enabled: true
    l2announcements:
      enabled: true

    operator:
      enabled: true
      replicas: 3
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          labels:
            release: monitoring
      dashboards: 
        enabled: true
    prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          trustCRDsExist: true
          labels:
            release: monitoring
    dashboards:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      tls:
        server:
          enabled: true
      ui:
        enabled: true
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      metrics:
        serviceMonitor:
          enabled: true
          labels:
            release: monitoring
        enabled: 
          - dns:query;ignoreAAAA 
          - drop 
          - tcp 
          - flow 
          - icmp 
          - http
        dashboards:
          enabled: true
```

This 503 error is happening only with hubble-ui the reste of my httproutes are working.

**Comment by xaviergrandmougin** [comment]
No issue so far with 1.17.0, it seems ok for me now.

**Comment by Joao-1** [comment]
I having the error `upstream connect error or disconnect/reset before headers. reset reason: connection timeout` with 1.17.4. 

```
        bpf:
          masquerade: true
          hostLegacyRouting: true

        gatewayAPI:
          enabled: true
```

**Comment by qasmi** [comment]
> I having the error `upstream connect error or disconnect/reset before headers. reset reason: connection timeout` with 1.17.4.
> 
> ```
>         bpf:
>           masquerade: true
>           hostLegacyRouting: true
> 
>         gatewayAPI:
>           enabled: true
> ```

Same here

**Comment by Joao-1** [comment]
> > I having the error `upstream connect error or disconnect/reset before headers. reset reason: connection timeout` with 1.17.4.
> > ```
> >         bpf:
> >           masquerade: true
> >           hostLegacyRouting: true
> > 
> >         gatewayAPI:
> >           enabled: true
> > ```
> 
> Same here

I was using CNI Chaining with AWS CNI, and after I tried everything, the solution was just to migrate to use only Cilium.
