### ISSUE TITLE
BGP control plane missing PodCIDR advertisements on some nodes.

### ISSUE THREAD

**Issue by YakhontovYaroslav** [cilium/cilium#32886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium missing PodCIRD subnets BGP announcements on dual-stack cluster with ClusterPool IPAM.

Threre are no relevant log output from bgp-control-plane and `cilium bgp routes advertised ipv4\ipv6` outputs cidrs as advertised. Despite this tcpdump and ToR shows no routes being advertised from node. This can happen at random with both IPv4 and IPv6 cidrs in any combination.

This is my first experience with Cilium and this issue persists on all 9 nodes of demo cluster with 100% reproducibility (there are always > 1 node in cluster with this problem with no stable workaround, but sometimes node restart helps).  

### Cilium Version

cilium-cli: v0.16.9 compiled with go1.22.3 on linux/amd64
cilium image (default): v1.15.5
cilium image (stable): v1.15.5
cilium image (running): 1.15.5

### Kernel Version

6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### Kubernetes Version

v1.29.5

### Relevant log output

```shell
root@NodeName:~# tcpdump -v tcp port 179
tcpdump: listening on ens13f0np0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
17:30:53.456519 IP (tos 0xc0, ttl 1, id 25236, offset 0, flags [none], proto TCP (6), length 60)
    LeafIPv4.38154 > NodeName.bgp: Flags [S], cksum 0xf484 (correct), seq 1252849700, win 32768, options [mss 8968,nop,wscale 3,sackOK,TS val 195205383 ecr 0], length 0
17:30:53.456567 IP (tos 0xc0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    NodeName.bgp > LeafIPv4.38154: Flags [R.], cksum 0x9e4e (correct), seq 0, ack 1252849701, win 0, length 0
17:30:55.456481 IP6 (class 0xc0, hlim 1, next-header TCP (6) payload length: 40) LeafIPv6.14338 > NodeIPv6.bgp: Flags [S], cksum 0xd147 (correct), seq 1015681263, win 32768, options [mss 8948,nop,wscale 3,sackOK,TS val 195207383 ecr 0], length 0
17:30:55.456544 IP6 (class 0xc0, flowlabel 0x5d40d, hlim 64, next-header TCP (6) payload length: 20) NodeIPv6.bgp > LeafIPv6.14338: Flags [R.], cksum 0xa6ee (incorrect -> 0x82cd), seq 0, ack 1015681264, win 0, length 0
17:31:02.568840 IP6 (flowlabel 0xb564c, hlim 1, next-header TCP (6) payload length: 40) NodeIPv6.40295 > LeafIPv6.bgp: Flags [S], cksum 0xa702 (incorrect -> 0xe552), seq 3369598059, win 64800, options [mss 1440,sackOK,TS val 1725297816 ecr 0,nop,wscale 7], length 0
17:31:02.569187 IP6 (class 0xc0, hlim 1, next-header TCP (6) payload length: 40) LeafIPv6.bgp > NodeIPv6.40295: Flags [S.], cksum 0xa71a (correct), seq 2112714011, ack 3369598060, win 32768, options [mss 1440,nop,wscale 3,sackOK,TS val 195214496 ecr 1725297816], length 0
17:31:02.569274 IP6 (flowlabel 0xb564c, hlim 1, next-header TCP (6) payload length: 32) NodeIPv6.40295 > LeafIPv6.bgp: Flags [.], cksum 0xa6fa (incorrect -> 0x53d4), ack 1, win 507, options [nop,nop,TS val 1725297816 ecr 195214496], length 0
17:31:02.569640 IP6 (flowlabel 0xb564c, hlim 1, next-header TCP (6) payload length: 125) NodeIPv6.40295 > LeafIPv6.bgp: Flags [P.], cksum 0xa757 (incorrect -> 0x90bb), seq 1:94, ack 1, win 507, options [nop,nop,TS val 1725297816 ecr 195214496], length 93: BGP
	Open Message (1), length: 93
	  Version 4, my AS 23456, Holdtime 40s, ID NodeName
	  Optional parameters, length: 64
	    Option Capabilities Advertisement (2), length: 62
	      Route Refresh (2), length: 0
	      Unknown (73), length: 38
		no decoder for Capability 73
		0x0000:  2473 656c 6c65 722d 6c6f 616e 732d 6b38
		0x0010:  732d 776f 726b 6572 2d30 332e 6465 762e
		0x0020:  7762 2e72 7500
	      Multiprotocol Extensions (1), length: 4
		AFI IPv6 (2), SAFI Unicast (1)
	      32-Bit AS Number (65), length: 4
		 4 Byte AS LocalASN
	      Graceful Restart (64), length: 6
		Restart Flags: [R], Restart Time 120s
		  AFI IPv6 (2), SAFI Unicast (1), Forwarding state preserved: yes
17:31:02.569757 IP6 (class 0xc0, hlim 1, next-header TCP (6) payload length: 81) LeafIPv6.bgp > NodeIPv6.40295: Flags [P.], cksum 0xc3f9 (correct), seq 1:50, ack 1, win 4105, options [nop,nop,TS val 195214497 ecr 1725297816], length 49: BGP
	Open Message (1), length: 49
	  Version 4, my AS 23456, Holdtime 180s, ID 10.255.16.110
	  Optional parameters, length: 20
	    Option Capabilities Advertisement (2), length: 6
	      Multiprotocol Extensions (1), length: 4
		AFI IPv6 (2), SAFI Unicast (1)
	    Option Capabilities Advertisement (2), length: 2
	      Route Refresh (2), length: 0
	    Option Capabilities Advertisement (2), length: 6
	      32-Bit AS Number (65), length: 4
		 4 Byte AS LeafASN
17:31:02.569781 IP6 (flowlabel 0xb564c, hlim 1, next-header TCP (6) payload length: 32) NodeIPv6.40295 > LeafIPv6.bgp: Flags [.], cksum 0xa6fa (incorrect -> 0x5344), ack 50, win 507, options [nop,nop,TS val 1725297817 ecr 195214497], length 0
17:31:02.569873 IP6 (class 0xc0, hlim 1, next-header TCP (6) payload length: 32) LeafIPv6.bgp > NodeIPv6.40295: Flags [.], cksum 0x4543 (correct), ack 94, win 4093, options [nop,nop,TS val 195214497 ecr 1725297816], length 0
17:31:02.569880 IP6 (flowlabel 0xb564c, hlim 1, next-header TCP (6) payload length: 51) NodeIPv6.40295 > LeafIPv6.bgp: Flags [P.], cksum 0xa70d (incorrect -> 0x4f16), seq 94:113, ack 50, win 507, options [nop,nop,TS val 1725297817 ecr 195214497], length 19: BGP
	Keepalive Message (4), length: 19
17:31:02.570057 IP6 (class 0xc0, hlim 1, next-header TCP (6) payload length: 51) LeafIPv6.bgp > NodeIPv6.40295: Flags [P.], cksum 0x4108 (correct), seq 50:69, ack 94, win 4105, options [nop,nop,TS val 195214497 ecr 1725297817], length 19: BGP
	Keepalive Message (4), length: 19
17:31:02.570174 IP6 (class 0xc0, hlim 1, next-header TCP (6) payload length: 32) LeafIPv6.bgp > NodeIPv6.40295: Flags [.], cksum 0x4512 (correct), ack 113, win 4103, options [nop,nop,TS val 195214497 ecr 1725297817], length 0
17:31:02.616748 IP6 (flowlabel 0xb564c, hlim 1, next-header TCP (6) payload length: 32) NodeIPv6.40295 > LeafIPv6.bgp: Flags [.], cksum 0xa6fa (incorrect -> 0x52ef), ack 69, win 507, options [nop,nop,TS val 1725297864 ecr 195214497], length 0
17:31:03.422816 IP6 (class 0xc0, hlim 1, next-header TCP (6) payload length: 62) LeafIPv6.bgp > NodeIPv6.40295: Flags [P.], cksum 0x23b7 (correct), seq 69:99, ack 113, win 4105, options [nop,nop,TS val 195215350 ecr 1725297864], length 30: BGP
	Update Message (2), length: 30
	  Multi-Protocol Unreach NLRI (15), length: 3, Flags [OE]:
	    AFI: IPv6 (2), SAFI: Unicast (1)
	      End-of-Rib Marker (empty NLRI)
17:31:03.422903 IP6 (flowlabel 0xb564c, hlim 1, next-header TCP (6) payload length: 32) NodeIPv6.40295 > LeafIPv6.bgp: Flags [.], cksum 0xa6fa (incorrect -> 0x4c56), ack 99, win 507, options [nop,nop,TS val 1725298670 ecr 195215350], length 0
17:31:06.568795 IP (tos 0x0, ttl 1, id 64446, offset 0, flags [DF], proto TCP (6), length 60)
    NodeName.39667 > LeafIPv4.bgp: Flags [S], cksum 0x3921 (incorrect -> 0x539e), seq 655130720, win 64240, options [mss 1460,sackOK,TS val 3843987532 ecr 0,nop,wscale 7], length 0
17:31:06.569110 IP (tos 0xc0, ttl 1, id 25339, offset 0, flags [none], proto TCP (6), length 60)
    LeafIPv4.bgp > NodeName.39667: Flags [S.], cksum 0x9605 (correct), seq 2150359149, ack 655130721, win 32768, options [mss 1460,nop,wscale 3,sackOK,TS val 195218496 ecr 3843987532], length 0
17:31:06.569202 IP (tos 0x0, ttl 1, id 64447, offset 0, flags [DF], proto TCP (6), length 52)
    NodeName.39667 > LeafIPv4.bgp: Flags [.], cksum 0x3919 (incorrect -> 0x42d8), ack 1, win 502, options [nop,nop,TS val 3843987532 ecr 195218496], length 0
17:31:06.569527 IP (tos 0x0, ttl 1, id 64448, offset 0, flags [DF], proto TCP (6), length 153)
    NodeName.39667 > LeafIPv4.bgp: Flags [P.], cksum 0x397e (incorrect -> 0xe82a), seq 1:102, ack 1, win 502, options [nop,nop,TS val 3843987532 ecr 195218496], length 101: BGP
	Open Message (1), length: 101
	  Version 4, my AS 23456, Holdtime 40s, ID NodeName
	  Optional parameters, length: 72
	    Option Capabilities Advertisement (2), length: 70
	      Route Refresh (2), length: 0
	      Unknown (73), length: 38
		no decoder for Capability 73
		0x0000:  2473 656c 6c65 722d 6c6f 616e 732d 6b38
		0x0010:  732d 776f 726b 6572 2d30 332e 6465 762e
		0x0020:  7762 2e72 7500
	      Multiprotocol Extensions (1), length: 4
		AFI IPv4 (1), SAFI Unicast (1)
	      32-Bit AS Number (65), length: 4
		 4 Byte AS LocalASN
	      Graceful Restart (64), length: 6
		Restart Flags: [none], Restart Time 120s
		  AFI IPv4 (1), SAFI Unicast (1), Forwarding state preserved: no
	      Extended Next Hop Encoding (5), length: 6
		no decoder for Capability 5
		0x0000:  0001 0001 0002
17:31:06.569660 IP (tos 0xc0, ttl 1, id 25340, offset 0, flags [none], proto TCP (6), length 101)
    LeafIPv4.bgp > NodeName.39667: Flags [P.], cksum 0xb3bf (correct), seq 1:50, ack 1, win 4163, options [nop,nop,TS val 195218496 ecr 3843987532], length 49: BGP
	Open Message (1), length: 49
	  Version 4, my AS 23456, Holdtime 180s, ID 10.255.16.110
	  Optional parameters, length: 20
	    Option Capabilities Advertisement (2), length: 6
	      Multiprotocol Extensions (1), length: 4
		AFI IPv4 (1), SAFI Unicast (1)
	    Option Capabilities Advertisement (2), length: 2
	      Route Refresh (2), length: 0
	    Option Capabilities Advertisement (2), length: 6
	      32-Bit AS Number (65), length: 4
		 4 Byte AS LeafASN
17:31:06.569685 IP (tos 0x0, ttl 1, id 64449, offset 0, flags [DF], proto TCP (6), length 52)
    NodeName.39667 > LeafIPv4.bgp: Flags [.], cksum 0x3919 (incorrect -> 0x4242), ack 50, win 502, options [nop,nop,TS val 3843987532 ecr 195218496], length 0
17:31:06.569790 IP (tos 0x0, ttl 1, id 64450, offset 0, flags [DF], proto TCP (6), length 71)
    NodeName.39667 > LeafIPv4.bgp: Flags [P.], cksum 0x392c (incorrect -> 0x3e13), seq 102:121, ack 50, win 502, options [nop,nop,TS val 3843987533 ecr 195218496], length 19: BGP
	Keepalive Message (4), length: 19
17:31:06.569794 IP (tos 0xc0, ttl 1, id 25341, offset 0, flags [none], proto TCP (6), length 52)
    LeafIPv4.bgp > NodeName.39667: Flags [.], cksum 0x3401 (correct), ack 102, win 4150, options [nop,nop,TS val 195218497 ecr 3843987532], length 0
17:31:06.570017 IP (tos 0xc0, ttl 1, id 25342, offset 0, flags [none], proto TCP (6), length 71)
    LeafIPv4.bgp > NodeName.39667: Flags [P.], cksum 0x2fc6 (correct), seq 50:69, ack 102, win 4163, options [nop,nop,TS val 195218497 ecr 3843987532], length 19: BGP
	Keepalive Message (4), length: 19
17:31:06.570131 IP (tos 0xc0, ttl 1, id 25343, offset 0, flags [none], proto TCP (6), length 52)
    LeafIPv4.bgp > NodeName.39667: Flags [.], cksum 0x33d0 (correct), ack 121, win 4160, options [nop,nop,TS val 195218497 ecr 3843987533], length 0
17:31:06.570470 IP (tos 0x0, ttl 1, id 64451, offset 0, flags [DF], proto TCP (6), length 99)
    NodeName.39667 > LeafIPv4.bgp: Flags [P.], cksum 0x3948 (incorrect -> 0x6843), seq 121:168, ack 69, win 502, options [nop,nop,TS val 3843987533 ecr 195218497], length 47: BGP
	Update Message (2), length: 47
	  Origin (1), length: 1, Flags [T]: IGP
	  AS Path (2), length: 6, Flags [T]: LocalASN
	  Next Hop (3), length: 4, Flags [T]: NodeName
	  Updated routes:
	    172.16.2.0/24
17:31:06.570725 IP (tos 0xc0, ttl 1, id 25344, offset 0, flags [none], proto TCP (6), length 52)
    LeafIPv4.bgp > NodeName.39667: Flags [.], cksum 0x33a3 (correct), ack 168, win 4157, options [nop,nop,TS val 195218498 ecr 3843987533], length 0
17:31:07.422520 IP (tos 0xc0, ttl 1, id 25351, offset 0, flags [none], proto TCP (6), length 75)
    LeafIPv4.bgp > NodeName.39667: Flags [P.], cksum 0x2e14 (correct), seq 69:92, ack 168, win 4163, options [nop,nop,TS val 195219349 ecr 3843987533], length 23: BGP
	Update Message (2), length: 23
	  End-of-Rib Marker (empty NLRI)
17:31:07.464746 IP (tos 0x0, ttl 1, id 64452, offset 0, flags [DF], proto TCP (6), length 52)
    NodeName.39667 > LeafIPv4.bgp: Flags [.], cksum 0x3919 (incorrect -> 0x3b01), ack 92, win 502, options [nop,nop,TS val 3843988428 ecr 195219349], length 0
17:31:13.456353 IP6 (class 0xc0, hlim 1, next-header TCP (6) payload length: 51) LeafIPv6.bgp > NodeIPv6.40295: Flags [P.], cksum 0x12e9 (correct), seq 99:118, ack 113, win 4105, options [nop,nop,TS val 195225383 ecr 1725298670], length 19: BGP
	Keepalive Message (4), length: 19
17:31:13.456425 IP6 (flowlabel 0xb564c, hlim 1, next-header TCP (6) payload length: 32) NodeIPv6.40295 > LeafIPv6.bgp: Flags [.], cksum 0xa6fa (incorrect -> 0xfde0), ack 118, win 507, options [nop,nop,TS val 1725308703 ecr 195225383], length 0
17:31:17.456459 IP (tos 0xc0, ttl 1, id 25441, offset 0, flags [none], proto TCP (6), length 71)
    LeafIPv4.bgp > NodeName.39667: Flags [P.], cksum 0x0154 (correct), seq 92:111, ack 168, win 4163, options [nop,nop,TS val 195229383 ecr 3843988428], length 19: BGP
	Keepalive Message (4), length: 19
17:31:17.456525 IP (tos 0x0, ttl 1, id 64453, offset 0, flags [DF], proto TCP (6), length 52)
    NodeName.39667 > LeafIPv4.bgp: Flags [.], cksum 0x3919 (incorrect -> 0xecb4), ack 111, win 502, options [nop,nop,TS val 3843998419 ecr 195229383], length 0
```

### Anything else?

Cilium is installed as following:
```
cilium install --wait --version v1.15.5 \
  --set cluster.name=demo \
  --set cluster.id=1 \
  --set tunnelProtocol=geneve \
  --set routingMode=tunnel \
  --set ipv4.enabled=true \
  --set ipv6.enabled=true \
  --set enableIPv4Masquerade=true \
  --set enableIPv6Masquerade=false \
  --set ipv6NativeRoutingCIDR="IPv6SubnetForPodsClusterIPsLBs/112" \
  --set ipam.mode=cluster-pool \
  --set ipam.operator.clusterPoolIPv4PodCIDRList={172.16.0.0/16} \
  --set ipam.operator.clusterPoolIPv4MaskSize=24 \
  --set ipam.operator.clusterPoolIPv6PodCIDRList={PodCIDRIPv6/114} \
  --set ipam.operator.clusterPoolIPv6MaskSize=120 \
  --set hostPort.enabled=false \
  --set externalIPs.enabled=true \
  --set externalWorkloads.enabled=true \
  --set wellKnownIdentities.enabled=true \
  --set bpf.masquerade=true \
  --set bpf.lbExternalClusterIP=true \
  --set kubeProxyReplacement=true \
  --set k8sServiceHost=127.0.0.1 \
  --set k8sServicePort=6443 \
  --set l7Proxy=false \
  --set egressGateway.enabled=false \
  --set localRedirectPolicy=true \
  --set loadBalancer.mode=dsr \
  --set loadBalancer.dsrDispatch=geneve \
  --set loadBalancer.algorithm=maglev \
  --set loadBalancer.acceleration=best-effort \
  --set loadBalancer.serviceTopology=true \
  --set loadBalancer.l7.backend=disabled \
  --set bgpControlPlane.enabled=true \
  --set enableCiliumEndpointSlice=true \
  --set socketLB.hostNamespaceOnly=true \
  --set envoy.enabled=false \
  --set envoyConfig.enabled=false \
  --set ingressController.enabled=false \
  --set ingressController.default=false \
  --set gatewayAPI.enabled=false \
  --set tls.secretsBackend=k8s \
  --set encryption.enabled=false \
  --set endpointRoutes.enabled=true \
  --set hubble.relay.enabled=true \
  --set hubble.ui.enabled=true \
  --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http}" \
  --set hubble.redact.enabled=true \
  --set hubble.redact.http.userInfo=true \
  --set hubble.tls.auto.enabled=true              \
  --set hubble.tls.auto.method=cronJob            \
  --set hubble.tls.auto.certValidityDuration=1095 \
  --set hubble.tls.auto.schedule="0 0 1 */4 *"
```

Relevant CiliumBGPPeeringPolicy (there are multiple policies for each rack)
```
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: demo-rackX
spec:
 nodeSelector:
   matchLabels:
     bgp-policy: rackX
 virtualRouters:
 - localASN: localASN
   exportPodCIDR: true
   neighbors:
    - peerAddress: 'LeafIPv4/32'
      peerASN: LeafASN
      eBGPMultihopTTL: 1
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 40
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
      families:
      - afi: ipv4
        safi: unicast
    - peerAddress: 'LeafIPv6/128'
      peerASN: LeafASN
      eBGPMultihopTTL: 1
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 40
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120
      families:
      - afi: ipv6
        safi: unicast
```

Node(s) in question also annotated with
`cilium.io/bgp-virtual-router.localASN: router-id=nodeIPv4` 

Filtered cilium bgp routes advertised ipv6 output (NodePodCIDRRangeIPv6 matching ipam section of CiliumNode):
```
...
NodeName   ASN   LeafIPv6   NodePodCIDRRangeIPv6/120   NodeIPv6                    1m19s       [{Origin: i} {AsPath: ASN} {MpReach(ipv6-unicast): {Nexthop: NodeIPv6, NLRIs: [NodePodCIDRRangeIPv6/120]}}]
...
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YutaroHayakawa** [comment]
I couldn't reproduce it in the dev environment.
https://docs.cilium.io/en/latest/contributing/development/bgp_cplane/

One possibility is the IPv6 PodCIDR is not assigned to the node. Could you show me the `CiliumNode` resource corresponding to the node in question? `kubectl -n kube-system get ciliumnodes <node name>`.

**Comment by YakhontovYaroslav** [comment]
All nodes are correctly assigned both IPv4 and IPv6 CIDRs. 
```
kubectl -n kube-system get ciliumnodes  -o json | jq ".items[].spec.ipam"
{
  "podCIDRs": [
    "172.16.6.0/24",
    "...::139:8600/120"
  ],
  "pools": {}
}
{
  "podCIDRs": [
    "172.16.0.0/24",
    "...::139:8000/120"
  ],
  "pools": {}
}
{
  "podCIDRs": [
    "172.16.1.0/24",
    "...::139:8100/120"
  ],
  "pools": {}
}
{
  "podCIDRs": [
    "172.16.8.0/24",
    "...::139:8800/120"
  ],
  "pools": {}
}
{
  "podCIDRs": [
    "172.16.2.0/24",
    "...0::139:8200/120"
  ],
  "pools": {}
}
{
  "podCIDRs": [
    "172.16.3.0/24",
    "...::139:8300/120"
  ],
  "pools": {}
}
{
  "podCIDRs": [
    "172.16.4.0/24",
    "...::139:8400/120"
  ],
  "pools": {}
}
{
  "podCIDRs": [
    "172.16.5.0/24",
    "...::139:8500/120"
  ],
  "pools": {}
}
{
  "podCIDRs": [
    "172.16.7.0/24",
    "...::139:8700/120"
  ],
  "pools": {}
}
```

**Comment by YutaroHayakawa** [comment]
Hmm, can you take a sysdump or provide a step to reproduce it? I don't have any idea what's happening there without further information.

**Comment by YakhontovYaroslav** [comment]
Well, spent whole weekend debugging this, here are the results:

1. Reconcilers are working correctly - all peers and routes getting into Router impl without problems
2. GoBGP`s ListPath reporting exactly the same routes as `cilium bgp routes adverised ipv4\6`
3. Sometimes there is simply no "sent update" message from GoBGP debug logs, regardless of ListPath result, which correlates with tcpdump output
4. Disabling graceful restart seems like resolved this issue.  I`ve tried to remove BGP CRs for longer than GR period with no success, while GR is enabled.  
Then i`ve noticed that ToRs in "bad dc" replying with no GR capability, so i`ve found this issues: https://github.com/osrg/gobgp/issues/2596 https://github.com/cloudnativelabs/kube-router/issues/1389

As i can understand, there is nothing Cilium can do regardless this behaviour, but maybe some big red warning in the docs will be helpful.

**Comment by YutaroHayakawa** [comment]
Alright, thanks for spotting it! As I mentioned [here](https://github.com/osrg/gobgp/issues/2596#issuecomment-2157315697), I think that issue is solved by the PR merged very recently. I'll make a PR to upgrade GoBGP version in the v1.15 branch.

**Comment by YakhontovYaroslav** [comment]
Meanwhile i have tried v1.16.0-pre3 tag which uses 3.26.0 gobgp library and the issue persists with routers that did not advertise GR option on Open Message.

**Comment by YakhontovYaroslav** [comment]
Well, there is a chance that sessions will be initialized correctly, so i think there is some race condition involved and i think your setup is good if You can observe this behavior. There must be test suite that runs at least N times to confirm bug presence.

Unfortunately, I'm temporary out of time to investigate this case further, hope i can return to this problem in next few sprints.
For now, we decided to unconditionally disable GR on all of our peers.

**Comment by harsimran-pabla** [comment]
Hi @YakhontovYaroslav Thanks for looking into this issue. 

I looked at [v1.16.0-pre3 vendor code](https://github.com/cilium/cilium/blob/v1.16.0-pre.3/vendor/github.com/osrg/gobgp/v3/pkg/server/server.go#L1655), it does not contain this [GR fix](https://github.com/osrg/gobgp/pull/2803/files). 

The latest main does have this fix included.  I am not sure if next cilium release is official 1.16 or a pre release, but it should contain fix for this problem. I could reproduce this problem on versions before this fix, but I haven't been able to repro it with latest main branch.

**Comment by YakhontovYaroslav** [comment]
@harsimran-pabla Great catch, i`ll look into this again on next 1.16 preview. 
Should i open new PR with GoBGP version bumped?

**Comment by harsimran-pabla** [comment]
> Should i open new PR with GoBGP version bumped?

I don't think it is necessary, latest main already has updated GoBGP release. Renovate updates the dependencies automatically. This is the [PR](https://github.com/cilium/cilium/pull/32987) for gobgp update.

To update the version in 1.15 release, we will have to do it manually. This [PR](https://github.com/cilium/cilium/pull/32993) need to be merged.

**Comment by YakhontovYaroslav** [comment]
@YutaroHayakawa @harsimran-pabla 
I've made several tests using [1.16.0-rc.0](https://github.com/cilium/cilium/releases/tag/v1.16.0-rc.0) and I can no longer reproduce this issue.

@YutaroHayakawa can You confirm this please and undraft https://github.com/cilium/cilium/pull/32993, this pull indeed contains fixed GoBGP version.

And thanks all for figuring this out.

**Comment by YutaroHayakawa** [comment]
> I looked at [v1.16.0-pre3 vendor code](https://github.com/cilium/cilium/blob/v1.16.0-pre.3/vendor/github.com/osrg/gobgp/v3/pkg/server/server.go#L1655), it does not contain this [GR fix](https://github.com/osrg/gobgp/pull/2803/files).

Hmm, this is weird. v1.16.0-pre.3 indeed has GoBGP 3.26.0 (https://github.com/cilium/cilium/blob/v1.16.0-pre.3/go.mod#L75). That means the vendor code was out of sync with go.mod? Why we couldn't catch it in CI 🤔

**Comment by YakhontovYaroslav** [comment]
Shall we close this as completed, as this is no longer reproduceable since 1.16-rc0?

**Comment by YutaroHayakawa** [comment]
Yep, thanks for your report!
