### ISSUE TITLE
Multipool pre-allocation option missing in Helm chart

### ISSUE THREAD

**Issue by CallMeFoxie** [cilium/cilium#35811]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

It is not possible to set `ipam-multi-pool-pre-allocation` in Helm chart at all. I searched through and through and it is not even in current master branch.

Not sure if this is a bug or CFP but for me it is quite a critical problem as with 8 running pods and /28 pools it is already requesting second pool (8 allocated IPs for pods, 9th for the Proxy, +8 default pre-alloc gives 17 requested -> rounded up to 24 -> second /28 allocated even though only 8 pods are actually running).

I will be sending PR to add this option to `cilium-config` configmap in a few minutes.

### How can we reproduce the issue?

1. git clone
2. try to set value for `ipam-multi-pool-pre-allocation`

### Cilium Version

master branch, but not available even in 1.15.x branch we currently use

### Kernel Version

not relevant

### Kubernetes Version

not relevant, but 1.30 and 1.31 branches

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
> It is not possible to set ipam-multi-pool-pre-allocation in Helm chart at all. I searched through and through and it is not even in current master branch.

Note that you can use `extraConfig` for this purpose, e.g. `--set-string extraConfig.ipam-multi-pool-pre-allocation=default=16,blue=8`

**Comment by nicl-dev** [comment]
The implemented solution causes a constant diff between the Live and Desired Manifests in ArgoCD. I think this would be a better approach:

```
{{- if not (eq .Values.ipam.multiPoolPreAllocation nil) }}
  ipam-multi-pool-pre-allocation: {{ .Values.ipam.multiPoolPreAllocation }}
{{- end }}
```

Thoughts?

**Comment by Skaronator** [comment]
Run into the same issue as @nicl-dev (and the 6 other upvotes). The issue is that the helm chart template check if the value is set, which is always true since its default set to an empty string. Instead, it should just check if the string is non-empty like other helm charts do it:
```
{{- if .Values.ipam.multiPoolPreAllocation }}
  ipam-multi-pool-pre-allocation: {{ .Values.ipam.multiPoolPreAllocation }}
{{- end }}
```

I found a good workaround to avoid sync issues in ArgoCD. Just set `ipam.multiPoolPreAllocation` to `null`.

**Comment by dnrce** [comment]
@Skaronator that looks right. Do you plan to submit a PR? If not, I can.

**Comment by nicl-dev** [comment]
I have a PR ready to push. Will do so tomorrow.

**Comment by nicl-dev** [comment]
PR ready here: https://github.com/cilium/cilium/pull/37536

**Comment by pmcgrath-mck** [comment]
Seeing the very same issue on ArgoCD, so this change would help

Wondering if the value should be quoted, like others, see https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-configmap.yaml#L1048

All the others seem to be quoted ?

**Comment by nicl-dev** [comment]
@pmcgrath-mck No, your line has a quoted `include`. Also there are plenty of values that are not quoted, for example: https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/cilium-configmap.yaml#L1147-L1164

**Comment by gandro** [comment]
The ArgoCD issues should be fixed in 1.17.2 to be released in March.

Related PRs:
https://github.com/cilium/cilium/pull/37536
https://github.com/cilium/cilium/pull/37585

**Comment by Daniel-Vaz** [comment]
> The ArgoCD issues should be fixed in 1.17.2 to be released in March.
> 
> Related PRs:
> 
> * [fix(helm): avoid ArgoCD out-of-sync by simplifying hasKey check #37536](https://github.com/cilium/cilium/pull/37536)
> * [fix(helm): multiPoolPreAllocation fix conditional avoid null #37585](https://github.com/cilium/cilium/pull/37585)

From my understanding both of these PRs were [backported](https://github.com/cilium/cilium/pull/37648).
Tried both 1.17.0 and 1.17.1, and I still face this problem in ArgoCD.
