### ISSUE TITLE
CI: `cilium.io/v2alpha1 CiliumNodeConfig` is still used in CI tests

### ISSUE THREAD

**Issue by antonipp** [cilium/cilium#37249]
I noticed this warning when working on https://github.com/cilium/cilium/pull/36802:
```
time="2025-01-23T12:34:45.571049428Z" level=warning msg="cilium.io/v2alpha1 CiliumNodeConfig will be deprecated in cilium v1.16; use cilium.io/v2 CiliumNodeConfig" subsys=klog
```

Example CI job: https://github.com/cilium/cilium/actions/runs/12929142101/job/36057972754 (this ran with Cilium 1.17)

As a workaround to merge my PR, I will add this warning to [warningLogExceptions](https://github.com/cilium/cilium/blob/b60f9bf2d30c21ccc294eb7ece9d7cead5c09b70/cilium-cli/connectivity/tests/errors.go#L57).

`v2alpha1` has been deprecated for a while: https://github.com/cilium/cilium/issues/31982 / https://github.com/cilium/cilium/pull/31721 but something probably hasn't been updated in the CI resources.

**Comment by sayboras** [comment]
This is fixed by https://github.com/cilium/cilium/pull/37272

**Comment by julianwiedmann** [comment]
@sayboras the link to the failed CI job is for an `e2e-upgrade` run ... so I think besides the ginkgo part you covered, we also have usage of the deprecated CRD in the cilium CLI.

**Comment by sayboras** [comment]
> the link to the failed CI job is for an `e2e-upgrade` run ... so I think besides the ginkgo part you covered, we also have usage of the deprecated CRD in the cilium CLI.

This should be fixed by https://github.com/cilium/cilium/pull/37003

**Comment by joestringer** [comment]
Looks like this is now resolved? Closing.

**Comment by pchaigno** [comment]
Reopening this because (1) the warning exception wasn't removed from `cilium-cli/connectivity/tests/errors.go` and (2) I'm still seeing the warning in the E2E Upgrade workflow.

**Comment by xi4n** [comment]
On AKS BYOCNI with current `cilium install --chart-directory ./install/kubernetes/cilium` (v1.18.0), I'm failing this test in `cilium connectivity test`
```
❌ Found 1 logs in <myClusterName>/kube-system/cilium-kh7kv (config) matching list of errors that must be investigated:
time="2025-04-14T17:35:12.094828722Z" level=warning msg="cilium.io/v2alpha1 CiliumNodeConfig will be deprecated in cilium v1.16; use cilium.io/v2 CiliumNodeConfig" subsys=klog (1 occurrences)
```
I think it's related to the present issue.

**Comment by w1ndhunter** [comment]
Any update on this? We're still facing this issue on AKS BYOCNI. This requires to force update AKS which is an workaround and needs to be fixed.

**Comment by pchaigno** [comment]
I'm not aware of anyone working on it at the moment. Feel free to send a fix.
