### ISSUE TITLE
connectivity test test fails with packet drops + possible controller issues with Maglev after update to 1.17

### ISSUE THREAD

**Issue by bernardgut** [cilium/cilium#38622]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

The full test output is here :
<details>
<summary>cilium connection-test</summary>

```
ℹ️  Monitor aggregation detected, will skip some flow validation steps
✨ [prod-cluster] Deploying echo-same-node service...
✨ [prod-cluster] Deploying DNS test server configmap...
✨ [prod-cluster] Deploying same-node deployment...
✨ [prod-cluster] Deploying client deployment...
✨ [prod-cluster] Deploying client2 deployment...
✨ [prod-cluster] Deploying client3 deployment...
✨ [prod-cluster] Deploying echo-other-node service...
✨ [prod-cluster] Deploying other-node deployment...
✨ [host-netns] Deploying prod-cluster daemonset...
✨ [host-netns-non-cilium] Deploying prod-cluster daemonset...
ℹ️  Skipping tests that require a node Without Cilium
✨ [prod-cluster] Deploying Ingress resource...
✨ [prod-cluster] Deploying Ingress resource...
⌛ [prod-cluster] Waiting for deployment cilium-test-1/client to become ready...
⌛ [prod-cluster] Waiting for deployment cilium-test-1/client2 to become ready...
⌛ [prod-cluster] Waiting for deployment cilium-test-1/echo-same-node to become ready...
⌛ [prod-cluster] Waiting for deployment cilium-test-1/client3 to become ready...
⌛ [prod-cluster] Waiting for deployment cilium-test-1/echo-other-node to become ready...
⌛ [prod-cluster] Waiting for pod cilium-test-1/client-645b68dcf7-j2h4x to reach DNS server on cilium-test-1/echo-same-node-6c545975c6-rtqj5 pod...
⌛ [prod-cluster] Waiting for pod cilium-test-1/client2-66475877c6-6qzdg to reach DNS server on cilium-test-1/echo-same-node-6c545975c6-rtqj5 pod...
⌛ [prod-cluster] Waiting for pod cilium-test-1/client3-795488bf5-7c8fk to reach DNS server on cilium-test-1/echo-same-node-6c545975c6-rtqj5 pod...
⌛ [prod-cluster] Waiting for pod cilium-test-1/client3-795488bf5-7c8fk to reach DNS server on cilium-test-1/echo-other-node-7f546db4f4-c76pc pod...
⌛ [prod-cluster] Waiting for pod cilium-test-1/client-645b68dcf7-j2h4x to reach DNS server on cilium-test-1/echo-other-node-7f546db4f4-c76pc pod...
⌛ [prod-cluster] Waiting for pod cilium-test-1/client2-66475877c6-6qzdg to reach DNS server on cilium-test-1/echo-other-node-7f546db4f4-c76pc pod...
⌛ [prod-cluster] Waiting for pod cilium-test-1/client2-66475877c6-6qzdg to reach default/kubernetes service...
⌛ [prod-cluster] Waiting for pod cilium-test-1/client3-795488bf5-7c8fk to reach default/kubernetes service...
⌛ [prod-cluster] Waiting for pod cilium-test-1/client-645b68dcf7-j2h4x to reach default/kubernetes service...
⌛ [prod-cluster] Waiting for Service cilium-test-1/echo-same-node to become ready...
⌛ [prod-cluster] Waiting for Service cilium-test-1/echo-same-node to be synchronized by Cilium pod cni/cilium-x8l28
⌛ [prod-cluster] Waiting for Service cilium-test-1/echo-same-node to be synchronized by Cilium pod cni/cilium-27bgd
⌛ [prod-cluster] Waiting for Service cilium-test-1/echo-other-node to become ready...
⌛ [prod-cluster] Waiting for Service cilium-test-1/echo-other-node to be synchronized by Cilium pod cni/cilium-27bgd
⌛ [prod-cluster] Waiting for Service cilium-test-1/echo-other-node to be synchronized by Cilium pod cni/cilium-x8l28
⌛ [prod-cluster] Retrieving service cilium-test-1/cilium-ingress-other-node ...
⌛ [prod-cluster] Retrieving service cilium-test-1/cilium-ingress-same-node ...
⌛ [prod-cluster] Waiting for NodePort 2a02:REDACTED:0:aa42:a1ff:fe4b:48a4:31330 (cilium-test-1/echo-other-node) to become ready...
⌛ [prod-cluster] Waiting for NodePort 2a02:REDACTED:0:aa42:a1ff:fe4b:48a4:30397 (cilium-test-1/echo-same-node) to become ready...
⌛ [prod-cluster] Waiting for NodePort 2a02:REDACTED:0:eee7:a7ff:fe10:bbb8:31330 (cilium-test-1/echo-other-node) to become ready...
⌛ [prod-cluster] Waiting for NodePort 2a02:REDACTED:0:eee7:a7ff:fe10:bbb8:30397 (cilium-test-1/echo-same-node) to become ready...
⌛ [prod-cluster] Waiting for NodePort 2a02:REDACTED:0:ae1f:6bff:fe1e:8a4e:31330 (cilium-test-1/echo-other-node) to become ready...
⌛ [prod-cluster] Waiting for NodePort 2a02:REDACTED:0:ae1f:6bff:fe1e:8a4e:30397 (cilium-test-1/echo-same-node) to become ready...
⌛ [prod-cluster] Waiting for DaemonSet cilium-test-1/host-netns-non-cilium to become ready...
⌛ [prod-cluster] Waiting for DaemonSet cilium-test-1/host-netns to become ready...
ℹ️  Skipping IPCache check
🔭 Enabling Hubble telescope...
⚠️  Unable to contact Hubble Relay, disabling Hubble telescope and flow validation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4245: connect: connection refused"
ℹ️  Expose Relay locally with:
   cilium hubble enable
   cilium hubble port-forward&
ℹ️  Cilium version: 1.17.2
🏃[cilium-test-1] Running 112 tests ...
[=] [cilium-test-1] Test [no-unexpected-packet-drops] [1/112]
..
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/prod-cluster/n1]
  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/prod-cluster/n2]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops/prod-cluster/n3]
  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "CT: Unknown L4 protocol"
  },
  "name": "cilium_drop_count_total",
  "value": 8
}
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 1188962
}
{
  "labels": {
    "direction": "EGRESS",
    "reason": "TTL exceeded"
  },
  "name": "cilium_drop_count_total",
  "value": 135049
}
{
  "labels": {
    "direction": "INGRESS",
    "reason": "Error while correcting L4 checksum"
  },
  "name": "cilium_drop_count_total",
  "value": 78205
}
{
  "labels": {
    "direction": "INGRESS",
    "reason": "IP fragmentation not supported"
  },
  "name": "cilium_drop_count_total",
  "value": 11433
}
.[=] [cilium-test-1] Test [no-policies] [2/112]
.......................................................................................
[=] [cilium-test-1] Skipping test [no-policies-from-outside] [3/112] (skipped by condition)
[=] [cilium-test-1] Test [no-policies-extra] [4/112]
....................................
[=] [cilium-test-1] Test [allow-all-except-world] [5/112]
......................................................
[=] [cilium-test-1] Test [client-ingress] [6/112]
............
[=] [cilium-test-1] Test [client-ingress-knp] [7/112]
............
[=] [cilium-test-1] Test [allow-all-with-metrics-check] [8/112]
............
[=] [cilium-test-1] Test [all-ingress-deny] [9/112]
..................
[=] [cilium-test-1] Skipping test [all-ingress-deny-from-outside] [10/112] (skipped by condition)
[=] [cilium-test-1] Test [all-ingress-deny-knp] [11/112]
..................
[=] [cilium-test-1] Test [all-egress-deny] [12/112]
................................................
[=] [cilium-test-1] Test [all-egress-deny-knp] [13/112]
................................................
[=] [cilium-test-1] Test [all-entities-deny] [14/112]
..................
[=] [cilium-test-1] Test [cluster-entity] [15/112]
......
[=] [cilium-test-1] Skipping test [cluster-entity-multi-cluster] [16/112] (skipped by condition)
[=] [cilium-test-1] Test [host-entity-egress] [17/112]
..................
[=] [cilium-test-1] Test [host-entity-ingress] [18/112]
............
[=] [cilium-test-1] Test [echo-ingress] [19/112]
............
[=] [cilium-test-1] Skipping test [echo-ingress-from-outside] [20/112] (skipped by condition)
[=] [cilium-test-1] Test [echo-ingress-knp] [21/112]
............
[=] [cilium-test-1] Test [client-ingress-icmp] [22/112]
............
[=] [cilium-test-1] Test [client-egress] [23/112]
............
[=] [cilium-test-1] Test [client-egress-knp] [24/112]
............
[=] [cilium-test-1] Test [client-egress-expression] [25/112]
............
[=] [cilium-test-1] Test [client-egress-expression-port-range] [26/112]
............
[=] [cilium-test-1] Test [client-egress-expression-knp] [27/112]
............
[=] [cilium-test-1] Test [client-egress-expression-knp-port-range] [28/112]
............
[=] [cilium-test-1] Test [client-with-service-account-egress-to-echo] [29/112]
............
[=] [cilium-test-1] Test [client-with-service-account-egress-to-echo-port-range] [30/112]
............
[=] [cilium-test-1] Test [client-egress-to-echo-service-account] [31/112]
............
[=] [cilium-test-1] Test [client-egress-to-echo-service-account-port-range] [32/112]
............
[=] [cilium-test-1] Test [to-entities-world] [33/112]
.E0331 10:07:41.806889  711703 websocket.go:296] Unknown stream id 1, discarding message
........
[=] [cilium-test-1] Test [to-entities-world-port-range] [34/112]
.........
[=] [cilium-test-1] Test [to-cidr-external] [35/112]
......
[=] [cilium-test-1] Test [to-cidr-external-knp] [36/112]
......
[=] [cilium-test-1] Skipping test [seq-from-cidr-host-netns] [37/112] (skipped by condition)
[=] [cilium-test-1] Test [echo-ingress-from-other-client-deny] [38/112]
....................
[=] [cilium-test-1] Test [client-ingress-from-other-client-icmp-deny] [39/112]
........................
[=] [cilium-test-1] Test [client-egress-to-echo-deny] [40/112]
........................
[=] [cilium-test-1] Test [client-egress-to-echo-deny-port-range] [41/112]
........................
[=] [cilium-test-1] Test [client-ingress-to-echo-named-port-deny] [42/112]
........
[=] [cilium-test-1] Test [client-egress-to-echo-expression-deny] [43/112]
........
[=] [cilium-test-1] Test [client-egress-to-echo-expression-deny-port-range] [44/112]
........
[=] [cilium-test-1] Test [client-with-service-account-egress-to-echo-deny] [45/112]
........
[=] [cilium-test-1] Test [client-with-service-account-egress-to-echo-deny-port-range] [46/112]
........
[=] [cilium-test-1] Test [client-egress-to-echo-service-account-deny] [47/112]
....
[=] [cilium-test-1] Test [client-egress-to-echo-service-account-deny-port-range] [48/112]
....
[=] [cilium-test-1] Test [client-egress-to-cidr-deny] [49/112]
......
[=] [cilium-test-1] Test [client-egress-to-cidrgroup-deny] [50/112]
......
[=] [cilium-test-1] Test [client-egress-to-cidrgroup-deny-by-label] [51/112]
......
[=] [cilium-test-1] Test [client-egress-to-cidr-deny-default] [52/112]
......
[=] [cilium-test-1] Skipping test [clustermesh-endpointslice-sync] [53/112] (skipped by condition)
[=] [cilium-test-1] Test [health] [54/112]
...
[=] [cilium-test-1] Skipping test [north-south-loadbalancing] [55/112] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Test [pod-to-pod-encryption] [56/112]
..
[=] [cilium-test-1] Skipping test [pod-to-pod-with-l7-policy-encryption] [57/112] (Feature encryption-pod is disabled)
[=] [cilium-test-1] Skipping test [pod-to-pod-encryption-v2] [58/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-pod-with-l7-policy-encryption-v2] [59/112] (skipped by condition)
[=] [cilium-test-1] Test [node-to-node-encryption] [60/112]
......
[=] [cilium-test-1] Skipping test [seq-egress-gateway] [61/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [egress-gateway-excluded-cidrs] [62/112] (Feature enable-ipv4-egress-gateway is disabled)
[=] [cilium-test-1] Skipping test [seq-egress-gateway-with-l7-policy] [63/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-node-cidrpolicy] [64/112] (Feature cidr-match-nodes is disabled)
[=] [cilium-test-1] Skipping test [north-south-loadbalancing-with-l7-policy] [65/112] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [north-south-loadbalancing-with-l7-policy-port-range] [66/112] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Test [echo-ingress-l7] [67/112]
....................................
[=] [cilium-test-1] Test [echo-ingress-l7-via-hostport] [68/112]
......
[=] [cilium-test-1] Test [echo-ingress-l7-named-port] [69/112]
....................................
[=] [cilium-test-1] Test [client-egress-l7-method] [70/112]
....................................
[=] [cilium-test-1] Test [client-egress-l7-method-port-range] [71/112]
....................................
[=] [cilium-test-1] Test [client-egress-l7] [72/112]
.....................
[=] [cilium-test-1] Test [client-egress-l7-port-range] [73/112]
.....................
[=] [cilium-test-1] Test [client-egress-l7-named-port] [74/112]
.....................
[=] [cilium-test-1] Test [client-egress-tls-sni] [75/112]
.........
[=] [cilium-test-1] Test [client-egress-tls-sni-denied] [76/112]
.........
[=] [cilium-test-1] Test [client-egress-l7-tls-headers-sni] [77/112]
...
[=] [cilium-test-1] Test [client-egress-l7-set-header] [78/112]
............
[=] [cilium-test-1] Test [client-egress-l7-set-header-port-range] [79/112]
............
[=] [cilium-test-1] Skipping test [echo-ingress-auth-always-fail] [80/112] (Feature mutual-auth-spiffe is disabled)
[=] [cilium-test-1] Skipping test [echo-ingress-auth-always-fail-port-range] [81/112] (Feature mutual-auth-spiffe is disabled)
[=] [cilium-test-1] Skipping test [echo-ingress-mutual-auth-spiffe] [82/112] (Feature mutual-auth-spiffe is disabled)
[=] [cilium-test-1] Skipping test [echo-ingress-mutual-auth-spiffe-port-range] [83/112] (Feature mutual-auth-spiffe is disabled)
[=] [cilium-test-1] Test [pod-to-ingress-service] [84/112]
......
[=] [cilium-test-1] Test [pod-to-ingress-service-deny-all] [85/112]
......
[=] [cilium-test-1] Test [pod-to-ingress-service-deny-ingress-identity] [86/112]
......
[=] [cilium-test-1] Test [pod-to-ingress-service-deny-backend-service] [87/112]
.
  ℹ️  curl stdout:
  fd00:0:a:1000:1::e1c8:53684 -> fd00:0:a:2000::46d4:80 = 200
  ℹ️  curl stderr:
  
  
  [.] Action [pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-1: cilium-test-1/client3-795488bf5-7c8fk (fd00:0:a:1000:1::e1c8) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)]
  ℹ️  📜 Applying CiliumNetworkPolicy 'ingress-backend-deny' to namespace 'cilium-test-1' on cluster prod-cluster..
  [-] Scenario [pod-to-ingress-service-deny-backend-service/pod-to-ingress-service]
  [.] Action [pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-0: cilium-test-1/client3-795488bf5-7c8fk (fd00:0:a:1000:1::e1c8) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)]
  ❌ command "curl --silent --fail --show-error --connect-timeout 2 --max-time 10 -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code}\n --output /dev/null http://cilium-ingress-other-node.cilium-test-1:80" succeeded while it should have failed: fd00:0:a:1000:1::e1c8:53684 -> fd00:0:a:2000::46d4:80 = 200

.  ❌ command "curl --silent --fail --show-error --connect-timeout 2 --max-time 10 -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code}\n --output /dev/null http://cilium-ingress-same-node.cilium-test-1:80" succeeded while it should have failed: fd00:0:a:1000:1::e1c8:37836 -> fd00:0:a:2000::3bd3:80 = 200

  ℹ️  curl stdout:
  fd00:0:a:1000:1::e1c8:37836 -> fd00:0:a:2000::3bd3:80 = 200
  ℹ️  curl stderr:
  
  
  [.] Action [pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-2: cilium-test-1/client-645b68dcf7-j2h4x (fd00:0:a:1000:2::11fd) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)]
.  ❌ command "curl --silent --fail --show-error --connect-timeout 2 --max-time 10 -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code}\n --output /dev/null http://cilium-ingress-other-node.cilium-test-1:80" succeeded while it should have failed: fd00:0:a:1000:2::11fd:57696 -> fd00:0:a:2000::46d4:80 = 200

  ℹ️  curl stdout:
  fd00:0:a:1000:2::11fd:57696 -> fd00:0:a:2000::46d4:80 = 200
  ℹ️  curl stderr:
  
  
  [.] Action [pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-3: cilium-test-1/client-645b68dcf7-j2h4x (fd00:0:a:1000:2::11fd) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)]
.  ❌ command "curl --silent --fail --show-error --connect-timeout 2 --max-time 10 -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code}\n --output /dev/null http://cilium-ingress-same-node.cilium-test-1:80" succeeded while it should have failed: fd00:0:a:1000:2::11fd:58622 -> fd00:0:a:2000::3bd3:80 = 200

  ℹ️  curl stdout:
  fd00:0:a:1000:2::11fd:58622 -> fd00:0:a:2000::3bd3:80 = 200
  ℹ️  curl stderr:
  
  
  [.] Action [pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-4: cilium-test-1/client2-66475877c6-6qzdg (fd00:0:a:1000:2::db92) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)]
.  ❌ command "curl --silent --fail --show-error --connect-timeout 2 --max-time 10 -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code}\n --output /dev/null http://cilium-ingress-other-node.cilium-test-1:80" succeeded while it should have failed: fd00:0:a:1000:2::db92:56330 -> fd00:0:a:2000::46d4:80 = 200

  ℹ️  curl stdout:
  fd00:0:a:1000:2::db92:56330 -> fd00:0:a:2000::46d4:80 = 200
  ℹ️  curl stderr:
  
  
  [.] Action [pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-5: cilium-test-1/client2-66475877c6-6qzdg (fd00:0:a:1000:2::db92) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)]
.  ❌ command "curl --silent --fail --show-error --connect-timeout 2 --max-time 10 -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code}\n --output /dev/null http://cilium-ingress-same-node.cilium-test-1:80" succeeded while it should have failed: fd00:0:a:1000:2::db92:44664 -> fd00:0:a:2000::3bd3:80 = 200

  ℹ️  curl stdout:
  fd00:0:a:1000:2::db92:44664 -> fd00:0:a:2000::3bd3:80 = 200
  ℹ️  curl stderr:
  
  
  ℹ️  📜 Deleting CiliumNetworkPolicy 'ingress-backend-deny' in namespace 'cilium-test-1' on cluster prod-cluster..
[=] [cilium-test-1] Test [pod-to-ingress-service-allow-ingress-identity] [88/112]
......
[=] [cilium-test-1] Skipping test [outside-to-ingress-service] [89/112] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [outside-to-ingress-service-deny-world-identity] [90/112] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [outside-to-ingress-service-deny-cidr] [91/112] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Skipping test [outside-to-ingress-service-deny-all-ingress] [92/112] (Feature node-without-cilium is disabled)
[=] [cilium-test-1] Test [dns-only] [93/112]
.....................
[=] [cilium-test-1] Test [to-fqdns] [94/112]
............
[=] [cilium-test-1] Skipping test [pod-to-controlplane-host] [95/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-k8s-on-controlplane] [96/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-controlplane-host-cidr] [97/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [pod-to-k8s-on-controlplane-cidr] [98/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [local-redirect-policy] [99/112] (Feature enable-local-redirect-policy is disabled)
[=] [cilium-test-1] Skipping test [local-redirect-policy-with-node-dns] [100/112] (skipped by condition)
[=] [cilium-test-1] Test [pod-to-pod-no-frag] [101/112]
..
[=] [cilium-test-1] Skipping test [seq-bgp-control-plane-v1] [102/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [seq-bgp-control-plane-v2] [103/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [multicast] [104/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [host-firewall-ingress] [106/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [strict-mode-encryption] [105/112] (skipped by condition)
[=] [cilium-test-1] Skipping test [host-firewall-egress] [107/112] (skipped by condition)
[=] [cilium-test-1] Test [seq-client-egress-l7-tls-deny-without-headers] [108/112]
...
[=] [cilium-test-1] Test [seq-client-egress-l7-tls-headers] [109/112]
...
[=] [cilium-test-1] Test [seq-client-egress-l7-extra-tls-headers] [110/112]
......
[=] [cilium-test-1] Test [seq-client-egress-l7-tls-headers-port-range] [111/112]
...
[=] [cilium-test-1] Test [check-log-errors] [112/112]
.........
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/hubble-ui-76d4965bb6-llhqh (frontend)]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/hubble-ui-76d4965bb6-llhqh (backend)]
  [-] Scenario [check-log-errors/no-errors-in-logs]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/hubble-relay-59cc4d545b-hxs2h (hubble-relay)]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-envoy-l9g2q (cilium-envoy)]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-operator-5556855979-bs9sv (cilium-operator)]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-x8l28 (config)]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-x8l28 (apply-sysctl-overwrites)]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-x8l28 (mount-bpf-fs)]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-x8l28 (clean-cilium-state)]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-x8l28 (install-cni-binaries)]
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-x8l28 (cilium-agent)]
  ❌ Found 10 logs in prod-cluster/cni/cilium-x8l28 (cilium-agent) matching list of errors that must be investigated:
time="2025-03-31T07:57:43.338856589Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 390: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[fdae:41e4:649b:9303:e5da:739a:de48:d037]:31746/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.337543898Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 394: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[2a02:REDACTED:0:ae1f:6bff:fe1e:8a4e]:31732/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.337663013Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 395: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[fdae:41e4:649b:9303:e5da:739a:de48:d037]:31732/TCP" subsys=k8s-watcher (1 occurrences)
time=2025-03-31T07:56:12Z level=warn msg="Could not modify IPv6 gro_max_size and gso_max_size, disabling BIG TCP" module=agent.datapath.bigtcp device=eno3 error="invalid argument" (1 occurrences)
time="2025-03-31T07:56:18.228733002Z" level=warning msg="Error getting CEP" ciliumEndpointName=argocd/argocd-repo-server-b9bf8c6f4-x2gb2 containerID=56776e326e containerInterface=eth0 controller="sync-to-k8s-ciliumendpoint (1890)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1890 error="client rate limiter Wait returned an error: context canceled" identity=2333 ipv4=10.229.1.37 ipv6="fd00:0:a:1000:1::6cfc" k8sPodName=argocd/argocd-repo-server-b9bf8c6f4-x2gb2 subsys=endpointsynchronizer (1 occurrences)
time="2025-03-31T07:57:43.337825456Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 398: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[2a02:REDACTED:0:ae1f:6bff:fe1e:8a4e]:30456/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.337922215Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 399: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[fdae:41e4:649b:9303:e5da:739a:de48:d037]:30456/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.338591831Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 386: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[2a02:REDACTED:0:ae1f:6bff:fe1e:8a4e]:30529/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.338659937Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 387: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[fdae:41e4:649b:9303:e5da:739a:de48:d037]:30529/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.338814069Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 389: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[2a02:REDACTED:0:ae1f:6bff:fe1e:8a4e]:31746/TCP" subsys=k8s-watcher (1 occurrences)
..  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-27bgd (install-cni-binaries)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-27bgd (cilium-agent)]
.  ❌ Found 10 logs in prod-cluster/cni/cilium-27bgd (cilium-agent) matching list of errors that must be investigated:
time=2025-03-31T07:56:19Z level=warn msg="Could not modify IPv6 gro_max_size and gso_max_size, disabling BIG TCP" module=agent.datapath.bigtcp device=enp8s0 error="invalid argument" (1 occurrences)
time="2025-03-31T07:56:24.752641574Z" level=warning msg="Error getting CEP" ciliumEndpointName=kube-system/descheduler-29056796-gdgf9 containerID=ac02bef6d4 containerInterface=eth0 controller="sync-to-k8s-ciliumendpoint (863)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=863 error="client rate limiter Wait returned an error: context canceled" identity=13638 ipv4=10.229.2.103 ipv6="fd00:0:a:1000:2::a177" k8sPodName=kube-system/descheduler-29056796-gdgf9 subsys=endpointsynchronizer (1 occurrences)
time="2025-03-31T07:57:43.337508767Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 395: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[fdae:41e4:649b:9303:a85c:9d8f:37eb:ba2f]:30456/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.338962918Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 389: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[2a02:REDACTED:0:aa42:a1ff:fe4b:48a4]:31746/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.337433896Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 397: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[2a02:REDACTED:0:aa42:a1ff:fe4b:48a4]:31732/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.337468371Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 398: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[fdae:41e4:649b:9303:a85c:9d8f:37eb:ba2f]:31732/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.337538773Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 394: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[2a02:REDACTED:0:aa42:a1ff:fe4b:48a4]:30456/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.338908195Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 390: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[fdae:41e4:649b:9303:a85c:9d8f:37eb:ba2f]:31746/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.339007783Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 387: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[2a02:REDACTED:0:aa42:a1ff:fe4b:48a4]:30529/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.339033701Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 388: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[fdae:41e4:649b:9303:a85c:9d8f:37eb:ba2f]:30529/TCP" subsys=k8s-watcher (1 occurrences)
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-27bgd (config)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-27bgd (apply-sysctl-overwrites)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-27bgd (mount-bpf-fs)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-27bgd (clean-cilium-state)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-envoy-9qwwm (cilium-envoy)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-envoy-n49cn (cilium-envoy)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-mm2ph (cilium-agent)]
.  ❌ Found 11 logs in prod-cluster/cni/cilium-mm2ph (cilium-agent) matching list of errors that must be investigated:
time="2025-03-31T07:56:03.352440705Z" level=warning msg="Error getting CEP" ciliumEndpointName=velero/repo-maintain-job-1743407743717-z2zst containerID=e500158469 containerInterface=eth0 controller="sync-to-k8s-ciliumendpoint (1666)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1666 error="client rate limiter Wait returned an error: context canceled" identity=60763 ipv4=10.229.0.118 ipv6="fd00:0:a:1000::41d7" k8sPodName=velero/repo-maintain-job-1743407743717-z2zst subsys=endpointsynchronizer (1 occurrences)
time="2025-03-31T07:57:43.338616683Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 386: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[2a02:REDACTED:0:eee7:a7ff:fe10:bbb8]:31746/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.338686764Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 387: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[fdae:41e4:649b:9303:386b:25c7:7aef:7e10]:31746/TCP" subsys=k8s-watcher (1 occurrences)
time=2025-03-31T07:55:58Z level=warn msg="Could not modify IPv6 gro_max_size and gso_max_size, disabling BIG TCP" module=agent.datapath.bigtcp device=enp8s0f0 error="invalid argument" (1 occurrences)
time="2025-03-31T07:56:03.352480149Z" level=warning msg="Error getting CEP" ciliumEndpointName=cilium-test-1/client3-795488bf5-t2kfq containerID=c663e405a9 containerInterface=eth0 controller="sync-to-k8s-ciliumendpoint (7)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=7 error="client rate limiter Wait returned an error: context canceled" identity=17466 ipv4=10.229.0.232 ipv6="fd00:0:a:1000::59fa" k8sPodName=cilium-test-1/client3-795488bf5-t2kfq subsys=endpointsynchronizer (1 occurrences)
time="2025-03-31T07:57:43.337327083Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 394: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[2a02:REDACTED:0:eee7:a7ff:fe10:bbb8]:31732/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.337377568Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 395: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[fdae:41e4:649b:9303:386b:25c7:7aef:7e10]:31732/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.337418785Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 397: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[2a02:REDACTED:0:eee7:a7ff:fe10:bbb8]:30456/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.33743196Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 398: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-other-node obj="[fdae:41e4:649b:9303:386b:25c7:7aef:7e10]:30456/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.338542373Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 389: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[2a02:REDACTED:0:eee7:a7ff:fe10:bbb8]:30529/TCP" subsys=k8s-watcher (1 occurrences)
time="2025-03-31T07:57:43.338571959Z" level=warning msg="Error deleting service by frontend" error="Unable to delete maglev lookup table 390: delete: key does not exist" k8sNamespace=cilium-test-1 k8sSvcName=cilium-ingress-same-node obj="[fdae:41e4:649b:9303:386b:25c7:7aef:7e10]:30529/TCP" subsys=k8s-watcher (1 occurrences)
  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-mm2ph (config)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-mm2ph (apply-sysctl-overwrites)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-mm2ph (mount-bpf-fs)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-mm2ph (clean-cilium-state)]
.  [.] Action [check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-mm2ph (install-cni-binaries)]
.
📋 Test Report [cilium-test-1]
❌ 3/76 tests failed (10/1126 actions), 36 tests skipped, 0 scenarios skipped:
Test [no-unexpected-packet-drops]:
  ❌ no-unexpected-packet-drops/no-unexpected-packet-drops/prod-cluster/n3
Test [pod-to-ingress-service-deny-backend-service]:
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-0: cilium-test-1/client3-795488bf5-7c8fk (fd00:0:a:1000:1::e1c8) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-1: cilium-test-1/client3-795488bf5-7c8fk (fd00:0:a:1000:1::e1c8) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-2: cilium-test-1/client-645b68dcf7-j2h4x (fd00:0:a:1000:2::11fd) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-3: cilium-test-1/client-645b68dcf7-j2h4x (fd00:0:a:1000:2::11fd) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-4: cilium-test-1/client2-66475877c6-6qzdg (fd00:0:a:1000:2::db92) -> cilium-test-1/cilium-ingress-other-node (cilium-ingress-other-node.cilium-test-1:80)
  ❌ pod-to-ingress-service-deny-backend-service/pod-to-ingress-service/curl-5: cilium-test-1/client2-66475877c6-6qzdg (fd00:0:a:1000:2::db92) -> cilium-test-1/cilium-ingress-same-node (cilium-ingress-same-node.cilium-test-1:80)
Test [check-log-errors]:
  ❌ check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-x8l28 (cilium-agent)
  ❌ check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-27bgd (cilium-agent)
  ❌ check-log-errors/no-errors-in-logs/prod-cluster/cni/cilium-mm2ph (cilium-agent)
```

</details>

TLDR: After updating to 1.17.2 from 1.16 I started having the issues above. No config change on upgrade.  For the packet  drop issue I had #30754 a while ago but then it got fixed with 1.16. Now it is back but with a different "reason". Not sure it is related. For the Maglev issue, I am unsure its a real issue (might just be the pod doesn't exist anymore ?) -- not sure how it works, but I never saw this error before.

Aditionally, after the test `cilium status` started showing errors that you can see below, and I was not able to port-forward hubble like I usually do. Upon access I get a weird hash value in the browser, then
```
cilium hubble -n cni port-forward&
Hubble Relay is available at 127.0.0.1:4245
E0330 22:45:39.234478  665558 portforward.go:424] "Unhandled Error" err="an error occurred forwarding 4245 -> 4245: error forwarding port 4245 to pod fcd8d2152ac03a63c1f2be3cc382b406bfaf8c582f9090ab5e62b5e40727a3ec, uid : failed to execute portforward in network namespace \"/var/run/netns/cni-a92bcddb-58d6-31c5-e26f-5c70dd39b072\": writeto tcp4 127.0.0.1:58922->127.0.0.1:4245: read tcp4 127.0.0.1:58922->127.0.0.1:4245: read: connection reset by peer" logger="UnhandledError"
```

### How can we reproduce the issue?

Cilium 1.17.2 on bare-metal (no Cloud) 3-node beefy Talos cluster.

<details>
<summary>values.helm.yaml</summary>

```
# disable the kube-proxy
kubeProxyReplacement: true
# stacks settings
routingMode: native
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 10.229.0.0/16 # podSubnet
enableIPv4BIGTCP: true
#enableIPv4Masquerade: false
autoDirectNodeRoutes: true
ipv6:
  enabled: true
enableIPv6BIGTCP: true
#enableIPv6Masquerade: false
ipv6NativeRoutingCIDR: fd00:0:a:1000::/64 # podSubnet
# optimizations
bpf:
  # TODO: requires kernel 6.8+ Enable when available
  # datapathMode: netkit  # TODO enable on new nodes and rotate old ones
  masquerade: true
  disableExternalIPMitigation: true
bandwidthManager:
  enabled: true
  bbr: true
ipam:
  mode: kubernetes
loadBalancer:
  algorithm: maglev
  #mode: hybrid # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#direct-server-return-dsr
  mode: dsr
  dsrDispatch: opt
  # acceleration: best-effort # only enables XDP on devices that support it. Should work on HW devices. not on Wireguard
# if maglev is enabled:
maglev:
  tableSize: 4093 # default is 16381 but we have a small cluster. here we support up to 40 backends for 1 service
  hashSeed: REDACTED
# BGP
bgpControlPlane:
  enabled: true
# Ports Allowed
externalIPs:
  enabled: true
# Cilium
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  hostRoot: /sys/fs/cgroup
  autoMount:
    enabled: false
# Enable Cilium Ingress Controller
ingressController:
  enabled: true
  default: true
  #loadbalancerMode: shared #TODO disable this when you go to IPv6-only
# Use KubePrism to access cluster API
k8sServiceHost: localhost
k8sServicePort: 7445
# OR
# Use IPv6 to access cluster API (for IPv6 only clusters)
#k8sServiceHost: ::1 # virtual IP
#k8sServicePort: 6443
# Enable Cilium Operator
operator:
  replicas: 1
# enable gatewayAPI
gatewayAPI:
  enabled: true
# Security
# disabled as it messes with drpd quorum
# encryption:
#   enabled: true
#   type: wireguard
#   strictMode:
#     enabled: true
#     cidr: 10.229.0.0/16 # podSubnet
    # TODO: enable IPv6 as well when Available for wireguard

# Enable Hubble
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - REDACTED
      tls:
        - secretName: REDACTED
          hosts:
            - REDACTED
```

</details>

### Cilium Version

```
cilium status -n cni                                                                                                                       
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             3 errors
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

DaemonSet              cilium                   Desired: 3, Ready: 3/3, Available: 3/3
DaemonSet              cilium-envoy             Desired: 3, Ready: 3/3, Available: 3/3
Deployment             cilium-operator          Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-relay             Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-ui                Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium                   Running: 3
                       cilium-envoy             Running: 3
                       cilium-operator          Running: 1
                       clustermesh-apiserver    
                       hubble-relay             Running: 1
                       hubble-ui                Running: 1
Cluster Pods:          104/104 managed by Cilium
Helm chart version:    
Image versions         cilium             quay.io/cilium/cilium:v1.17.2@sha256:3c4c9932b5d8368619cb922a497ff2ebc8def5f41c18e410bcc84025fcd385b1: 3
                       cilium-envoy       quay.io/cilium/cilium-envoy:v1.31.5-1741765102-efed3defcc70ab5b263a0fc44c93d316b846a211@sha256:377c78c13d2731f3720f931721ee309159e782d882251709cb0fac3b42c03f4b: 3
                       cilium-operator    quay.io/cilium/operator-generic:v1.17.2@sha256:81f2d7198366e8dec2903a3a8361e4c68d47d19c68a0d42f0b7b6e3f0523f249: 1
                       hubble-relay       quay.io/cilium/hubble-relay:v1.17.2@sha256:42a8db5c256c516cacb5b8937c321b2373ad7a6b0a1e5a5120d5028433d586cc: 1
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.13.2@sha256:a034b7e98e6ea796ed26df8f4e71f83fc16465a19d166eff67a03b822c0bfa15: 1
                       hubble-ui          quay.io/cilium/hubble-ui:v0.13.2@sha256:9e37c1296b802830834cc87342a9182ccbb71ffebb711971e849221bd9d59392: 1
Errors:                cilium             cilium-27bgd    controller sync-lb-maps-with-k8s-services is failing since 48s (137x): Unable to remove service &{hash:��A�d���\��7��/}$ frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:18279620386739688195 lo:12131744734673353263} z:{value:0xc000011ef0}} clusterID:0} L4Addr:{Protocol:TCP Port:32036} Scope:0} ID:14} backends:[] backendByHash:map[] svcType:NodePort svcForwardingMode: svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 healthcheckFrontendHash: svcName:{Namespace: Name: Cluster:} loadBalancerAlgorithm:0 svcSourceRangesPolicy: loadBalancerSourceRanges:[] l7LBProxyPort:0 LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[] annotations:map[]}: Unable to delete maglev lookup table 14: delete: key does not exist
                       cilium             cilium-mm2ph    controller sync-lb-maps-with-k8s-services is failing since 1m11s (137x): Unable to remove service &{hash:*i%��������} frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:3026983450664501248 lo:17214912818568018872} z:{value:0xc000239ea8}} clusterID:0} L4Addr:{Protocol:TCP Port:32002} Scope:0} ID:349} backends:[] backendByHash:map[] svcType:NodePort svcForwardingMode: svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 healthcheckFrontendHash: svcName:{Namespace: Name: Cluster:} loadBalancerAlgorithm:0 svcSourceRangesPolicy: loadBalancerSourceRanges:[] l7LBProxyPort:0 LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[] annotations:map[]}: Unable to delete maglev lookup table 349: delete: key does not exist
                       cilium             cilium-x8l28    controller sync-lb-maps-with-k8s-services is failing since 56s (137x): Unable to remove service &{hash:*i%��k���N}$ frontend:{L3n4Addr:{AddrCluster:{addr:{addr:{hi:3026983450664501248 lo:12546865834101738062} z:{value:0xc000011ec0}} clusterID:0} L4Addr:{Protocol:TCP Port:32036} Scope:0} ID:13} backends:[] backendByHash:map[] svcType:NodePort svcForwardingMode: svcExtTrafficPolicy:Cluster svcIntTrafficPolicy:Cluster svcNatPolicy:NONE sessionAffinity:false sessionAffinityTimeoutSec:0 svcHealthCheckNodePort:0 healthcheckFrontendHash: svcName:{Namespace: Name: Cluster:} loadBalancerAlgorithm:0 svcSourceRangesPolicy: loadBalancerSourceRanges:[] l7LBProxyPort:0 LoopbackHostport:false restoredFromDatapath:true restoredBackendHashes:map[] annotations:map[]}: Unable to delete maglev lookup table 13: delete: key does not exist
```

### Kernel Version

```
k get nodes -o yaml | grep kernel                                                                                                
      kernelVersion: 6.12.18-talos
      kernelVersion: 6.12.18-talos
      kernelVersion: 6.12.18-talos
```

### Kubernetes Version

```
k version                                                                                                                        
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.3
```

### Regression

1.16.4

### Sysdump

File was too big (53Mb). You can find it here : https://filebin.net/1vqgympnuwn6phok/cilium-sysdump-20250331-123954.zip

### Relevant log output

```shell
Ask if you need anything in particular
```

### Anything else?

Ask if you need anything in particular

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bernardgut** [comment]
For the maglev part this might be a duplicate of https://github.com/cilium/cilium/issues/38516

For the rest of the tests failing not sure

**Comment by joamaki** [comment]
https://github.com/cilium/cilium/commit/4c0be88e65ec99d866d6744b76ca2e52742b59af should fix this issue and it has been backported to v1.17 and will be part of the next release.

**Comment by bernardgut** [comment]
will test this soon and update/close this accordingly.

**Comment by bernardgut** [comment]
Ok I was gone with the summer but the issue persists :

```
[=] [cilium-test-1] Test [no-unexpected-packet-drops] [120/121]
.
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops:sekops-omni-p0/n2]
  [-] Scenario [no-unexpected-packet-drops/no-unexpected-packet-drops]
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops:sekops-omni-p0/n3]
  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "CT: Unknown L4 protocol"
  },
  "name": "cilium_drop_count_total",
  "value": 4
}
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 101367
}
{
  "labels": {
    "direction": "EGRESS",
    "reason": "TTL exceeded"
  },
  "name": "cilium_drop_count_total",
  "value": 5170
}
{
  "labels": {
    "direction": "INGRESS",
    "reason": "Error while correcting L4 checksum"
  },
  "name": "cilium_drop_count_total",
  "value": 4727
}
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "Unknown L4 protocol"
  },
  "name": "cilium_drop_count_total",
  "value": 2
}
{
  "labels": {
    "direction": "INGRESS",
    "reason": "Missed tail call"
  },
  "name": "cilium_drop_count_total",
  "value": 15
}
  [.] Action [no-unexpected-packet-drops/no-unexpected-packet-drops:sekops-omni-p0/n1]
.  ❌ Found unexpected packet drops:
{
  "labels": {
    "direction": "EGRESS",
    "reason": "FIB lookup failed"
  },
  "name": "cilium_drop_count_total",
  "value": 55
}
{
  "labels": {
    "direction": "EGRESS",
    "reason": "First logical datagram fragment not found"
  },
  "name": "cilium_drop_count_total",
  "value": 1
}
```

on 1.18.1.

Anyone has any idea what is going on ?

Thanks
