### ISSUE TITLE
bpf-lb-sock-terminate-pod-connections does not correctly terminate long-lived udp ipv6 connections

### ISSUE THREAD

**Issue by m0untains** [cilium/cilium#39470]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.16 and lower than v1.16.0

### What happened?

We have the following setup:

- A server (statsd) that binds an ipv4 udp socket on `0.0.0.0:8126`
- A `SingleStack` service created in k8s for this server
- A client that talks to the service using the v4-mapped-on-v6 address type. I.e. the client creates an `AF_INET6` socket, and then uses the `::ffff:` prefix to talk to the service, e.g. `::ffff:10.2.3.4`.

This all works fine until the statsd server restarts. Once restarted, the client continues to send udp packets to the _old_ statsd pod ip address.

This seems very similar to other issues around socket closure that have been reported, e.g.:

- https://github.com/cilium/cilium/issues/35773
- https://github.com/cilium/cilium/issues/37577

We have the following relevant cilium options set (using cilium version `v1.16.0`):
```
  bpf-lb-sock: "true"
  bpf-lb-sock-hostns-only: "false"
  bpf-lb-sock-terminate-pod-connections: "true"
```

Some interesting things we've observed:
- With `bpf-lb-sock` and `bpf-lb-sock-terminate-pod-connections` set, if the client uses an ipv4 `AF_INET` socket instead, sockets get forcibly closed / terminated as expected.
- If both the server, service, and client use ipv6, they are not closed as expected.

Essentially it seems like the stale-socket-finding-and-destruction business is working correctly for ipv4, but not ipv6.

### How can we reproduce the issue?

1. Bind a `SOCK_DGRAM` `AF_INET` socket in a server.
2. Create a corresponding kubernetes `Service` for this server.
3. In a client, create a `SOCK_DGRAM` `AF_INET6` socket. Configure the address to use a v4-mapped-on-v6 address type. E.g. if the kubernetes service address is `10.2.3.4`, configure the address the client will connect to as `::ffff:10.2.3.4`.
4. Use the `connect() + send()` syscalls to create a long-lived udp socket, and send packets at some interval (e.g. every 10 seconds) from the client to the server. Note: using `sendto()`, i.e. a short-lived socket effectively works around the issue, and does not produce the undesired behavior.
5. Restart the server
6. Notice how the packets from the client are still sent to the old server ip address.

### Cilium Version

`v1.16.0`

### Kernel Version

`Linux 5.4.0-204-generic #224-Ubuntu SMP Thu Dec 5 13:38:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.30.6`

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
Hi! This should be fixed by - https://github.com/cilium/cilium/pull/38509. Can you try installing the Cilium version with the fix?

**Comment by m0untains** [comment]
Hi,

Had a chance to upgrade to `v1.17.3` today (which contains the above mentioned fix). Unfortunately it did not produce a difference in observed behavior (i.e. the bug is still present in this version).

**Comment by fvichot** [comment]
I'm a colleague of @m0untains. I had a look at the code, and I wonder if this [line](https://github.com/foyerunix/cilium/blob/main/pkg/service/connections.go#L38) could be the issue here:
```
	if be.L3n4Addr.IsIPv6() {
		family = syscall.AF_INET6
	} else {
		family = syscall.AF_INET
	}
```
if I'm not mistaken, this would cause Cilium to decide whether a socket is `AF_INET6` or `AF_INET` based on the backend IP, which could lead to incorrect result in our case: we have a client using an `AF_INET6` socket to establish an IPv4 connection. So the backend is v4 but the socket family for the client is `AF_INET6`.

I think the socket filter [here](https://github.com/foyerunix/cilium/blob/main/pkg/service/connections.go#L55) probably doesn't need `family`, as filtering on destination IP and port is all you need.

**Comment by fvichot** [comment]
Hi @borkmann, did you get a chance to make progress on this issue ?

**Comment by borkmann** [comment]
> Hi [@borkmann](https://github.com/borkmann), did you get a chance to make progress on this issue ?

Hey 👋 still on it, will update you when there is a draft PR for testing.

**Comment by borkmann** [comment]
Fyi, I tested my fix against main branch in https://github.com/cilium/cilium/pull/39994 with IPv4-in-IPv6 connected UDP clients and it works for me.

```
# ./a.out "::ffff:10.96.203.223"
connected ::ffff:10.96.203.223
<------ UDP socket terminated in between ----->
trying send
 Error : send failed Destination address required
```

**Comment by fvichot** [comment]
Thanks @borkmann for the fix!

Looks like this is currently not included in the [v1.17 backport branch](https://github.com/cilium/cilium/pull/40094) due to conflicts, should we expect that it will only land as part of the v1.18 release ?

**Comment by borkmann** [comment]
> Looks like this is currently not included in the [v1.17 backport branch](https://github.com/cilium/cilium/pull/40094) due to conflicts, should we expect that it will only land as part of the v1.18 release ?

Right, it needs manual backport. Do you want to give this a try, otherwise I can look into it after the upcoming OSSNA conf.

**Comment by borkmann** [comment]
(v1.17 manual backport: https://github.com/cilium/cilium/pull/40295)
