### ISSUE TITLE
Incorrectly dropped traffic until Cilium DaemonSet is restarted

### ISSUE THREAD

**Issue by ldunkum** [cilium/cilium#41873]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.2 and lower than v1.19.0

### What happened?

Some requests from an application to S3 were dropped. We deploy a global egress deny-all rule and added an exception for this service (see below). Usually this works fine, but shortly after the update to v1.18.0 requests were sometimes dropped (Reason: PolicyDenied) until we restart the cilium DaemonSet, then the problem disappears.

CNP containing exception for this service:

```yaml
spec:
  egress:
  - toFQDNs:
    - matchName: sts.eu-central-1.amazonaws.com
    - matchName: ec2.eu-central-1.amazonaws.com
    - matchPattern: '*.s3.eu-central-1.amazonaws.com'
```

Configuration: we use cilium in cni-chaining mode with the aws-cni

### How can we reproduce the issue?

Unfortunately this is not readily reproducible, as it seemingly happens at random every couple of days.

In general, we're running v1.18.2, the issue has appeared since v1.18.0.

Here are our Helm Values:

```yaml
cni:
  chainingMode: aws-cni
  exclusive: false
eni:
  awsEnablePrefixDelegation: true
enableIPv4Masquerade: false
routingMode: native
endpointRoutes:
  enabled: true
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  tolerations:
  - key: arch
    operator: Equal
    value: arm64
    effect: NoSchedule
hubble:
  enabled: true
  metrics:
    serviceMonitor:
      enabled: true
    enableOpenMetrics: true
    enabled:
    - dns
    - drop
    - tcp
    - icmp
    - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
    - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
  relay:
    enabled: true
    tolerations:
    - key: arch
      operator: Equal
      value: arm64
      effect: NoSchedule

```

### Cilium Version

v1.18.2

### Kernel Version

6.1.134-152.225.amzn2023.aarch64

### Kubernetes Version

v1.33.3-eks-b707fbb

### Regression

v1.17.6

### Relevant log output

```shell

```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by krokofant** [comment]
I think I experience this too, I notice that most of the dropped packages are using `matchPattern` while the `matchName` doesn't seem affected.

**Comment by squeed** [comment]
We just fixed a [bug](https://github.com/cilium/cilium/pull/42815) in `main` where overlapping matchPattern selectors could cause packet loss. I see that your policy above does overlap.

If you have a staging cluster, would you be able to see if running the latest builds from `main` fix this?

**Comment by ldunkum** [comment]
Nice, thanks for the update. Unfortunately, we can't confirm whether our issue is fixed as it occurs sporadically and we're not able to reliably reproduce it. 

If you like, I can close this issue and reopen it, if it happens again?

**Comment by riuvshyn** [comment]
Hello, I think exactly same issue is still happening on 1.18.6

**Comment by vchepkov** [comment]
This reproduces on **v1.19.6 (latest stable)** — and across the entire 1.18 line — so the fixes referenced when this was closed (#42815 in v1.18.5, #44731/#44754 in v1.18.9) do **not** cover this case. Could this be reopened? If you'd rather me to open a new case, I will

Unlike #44714/#42573, **restarting cilium-agent does not clear it**, and it reproduces with a plain `toFQDNs`-only policy (wildcard `matchPattern` *and* exact `matchName`), with or without a competing `toCIDR` rule.

### Environment
- Cilium **v1.19.6** (also v1.18.12, v1.18.0)
- EKS v1.35, Bottlerocket OS (kernel 6.12)
- `ipam.mode: eni`, `routingMode: native` (pods get real VPC IPs), `kubeProxyReplacement: true`, `enableL7Proxy/l7Proxy: true`, `dnsproxy-enable-transparent-mode: true`, `enable-policy: default`, `enable-ipv4-masquerade: false`

### Symptom
A `toFQDNs` egress rule never allows the traffic. DNS is proxied and cached, the FQDN identity is allocated in the control plane, but the resolved IP is **never injected into the BPF datapath ipcache** — it stays `reserved:world` (identity 2) — so the connection is `Policy denied`. Default-deny and `toCIDR` allows both work correctly; only `toFQDNs` fails.

### Evidence (single correlated capture, same resolved IP)

FQDN identity is allocated:
```
$ cilium-dbg identity get 16777222
ID         LABELS
16777222   fqdn:*.amazonaws.com
           reserved:world
```

Pod resolves and connects to the same IP; that IP is in the FQDN cache:
```
# pod: nslookup sts.us-east-1.amazonaws.com -> 13.217.79.113
# pod: wget https://sts.us-east-1.amazonaws.com
Connecting to sts.us-east-1.amazonaws.com (13.217.79.113:443)   # times out / denied

$ cilium-dbg fqdn cache list | grep sts.us-east-1
...  sts.us-east-1.amazonaws.com.  3600  ...  13.217.79.113
```

Selector is realized with the FQDN identity:
```
$ cilium-dbg policy selectors
SELECTOR                                     LABELS                  USERS  IDENTITIES
MatchName: , MatchPattern: *.amazonaws.com   default/default-egress  2      16777222
```

But the datapath ipcache maps that exact IP to world (2), and the FQDN identity is absent from the map:
```
$ cilium-dbg bpf ipcache get 13.217.79.113
13.217.79.113 maps to identity identity=2 encryptkey=0 tunnelendpoint=0.0.0.0 flags=<none>

$ cilium-dbg bpf ipcache list | grep -c 16777222
0
```

### Root-cause mechanism
The FQDN `/32` write is rejected by source priority:
```
$ cilium-dbg metrics list | grep ipcache_errors
cilium_ipcache_errors_total  error=cannot_overwrite_by_source type=upsert  7
```
FQDN IPs are upserted with `Source: Generated` (near-lowest priority). A higher-priority source already owns the covering prefix for the resolved AWS IP, so `upsertLocked` rejects the `Generated` write (`cannot_overwrite_by_source`) and the `/32` FQDN identity never lands — the IP keeps `world` and is denied.

ipcache contents (broad prefixes + `0.0.0.0/0 → world`, no FQDN `/32`):
```
$ cilium-dbg bpf ipcache list
0.0.0.0/0        identity=2         # reserved:world
10.0.0.0/8       identity=16777217
172.16.0.0/12    identity=16777220
169.254.0.0/16   identity=16777221
```

### Question for maintainers
Under `routingMode=native` + ENI IPAM, should `toFQDNs` be able to overwrite the covering prefix with a per-IP `/32` `Generated`-source entry? The `cannot_overwrite_by_source` rejection suggests the FQDN write loses to a higher-priority source that owns the prefix — is this a source-priority bug in native-routing mode, or an unsupported combination? Cilium's EKS conformance CI does not appear to exercise `ipam.mode=eni` + `routingMode=native`, which may be why this persists undetected.

**Comment by vchepkov** [comment]
Correction to my earlier comment: this was a policy error on my side, not a Cilium bug.

`*` in a `matchPattern` matches a **single** DNS label, so `*.amazonaws.com` never matches `sts.us-east-1.amazonaws.com` — there are two labels before `amazonaws.com`. Verified against v1.19.6 by calling `FQDNSelector.ToRegex()` directly:

```
*.amazonaws.com   → ^[-a-zA-Z0-9_]*[.]amazonaws[.]com[.]$
   sts.us-east-1.amazonaws.com.  → false
   sts.amazonaws.com.            → true

**.amazonaws.com  → ^([-a-zA-Z0-9_]+([.][-a-zA-Z0-9_]+){0,})[.]amazonaws[.]com[.]$
   sts.us-east-1.amazonaws.com.  → true
```

With no matching selector, `deriveLabelsForName` returns empty labels and `updateDNSIPs` takes the early return at `pkg/fqdn/namemanager/manager.go:284`, so the `/32` is never upserted into the ipcache and the IP stays `reserved:world` (identity 2). Switching the policy to `**.amazonaws.com` fixed it — datapath identity went from 2 to the FQDN identity, `bpf ipcache list` gained the entries, and the connection succeeded.

The `cannot_overwrite_by_source` metric I cited was unrelated: that check is keyed on an exact prefix in `ipToIdentityCache`, so a covering `/8` cannot reject a `/32` write. It was a coincidental non-zero counter, not the mechanism.

This is also consistent with @krokofant's observation above that `matchName` works while `matchPattern` drops packets — exact names always match, single-label wildcards silently don't.

One suggestion while I'm here: the `len(nameLabels) == 0` early return at `manager.go:284-287` has no log line, unlike the two branches immediately above it (`"FQDN: IPs didn't change for DNS name"` and `"FQDN: No selectors registered for updates"`). A selector that fails to match is therefore invisible even with `debug: true` — the DNS response is logged as cached, the identity is allocated, `cilium-dbg policy selectors` shows the selector as realized, and yet nothing explains why no ipcache entry appears. A debug line there would have made this self-diagnosing.
