### ISSUE TITLE
cilium-etcd doesn't run after K8S restart

### ISSUE THREAD

**Issue by jek-a** [cilium/cilium#5941]
### Title

The 'cilium-etcd' resource created by etcd-operator doesn't run after K8S restart

### General Information

- **Cilium version**: Cilium 1.2.3 4a41ef3 2018-09-17T17:56:54-07:00 
- **Kernel version**: 4.18.13-200.fc28.x86_64
- **Orchestration system version in use**: K8S v1.12.1
- **etcd Version**: 3.2.22 

### How to reproduce the issue

1. sudo mount bpffs /sys/fs/bpf -t bpf
2. kubeadm init --pod-network-cidr 172.31.0.0/16
3. wget https://github.com/cilium/cilium/archive/v1.2.3.tar.gz
4. tar -xvf v1.2.3.tar.gz
5. cd cilium-1.2.3/examples/kubernetes/addons/etcd-operator/
6. export CLUSTER_DOMAIN=$(kubectl get ConfigMap --namespace kube-system coredns -o yaml | awk '/kubernetes/ {print $2}')
7. tls/certs/gen-cert.sh $CLUSTER_DOMAIN
8. tls/deploy-certs.sh
9. kubectl label -n kube-system pod $(kubectl -n kube-system get pods -l k8s-app=kube-dns -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{end}') io.cilium.fixed-identity=kube-dns
10. kubectl create -f ./
11. Join 2 workers and wait several minutes for Cilium, coredns and etcd pods to converge to a working state
```
kubectl get po -n kube-system
NAME                                                READY   STATUS    RESTARTS   AGE
cilium-89bk4                                        1/1     Running   1          14m
cilium-etcd-bvtgqv5n5n                              1/1     Running   0          11m
cilium-etcd-hwjpgl6m7t                              1/1     Running   0          10m
cilium-etcd-lcjbhg8hr4                              1/1     Running   0          13m
cilium-np5ww                                        1/1     Running   0          28s
cilium-p4hgp                                        1/1     Running   2          17m
coredns-576cbf47c7-mwrln                            1/1     Running   0          18m
coredns-576cbf47c7-zvktn                            1/1     Running   0          18m
etcd-operator-7cb79cdf99-4t8kw                      1/1     Running   0          17m
etcd-master-1                                       1/1     Running   0          17m
kube-apiserver-master-1                             1/1     Running   0          17m
kube-controller-manager-master-1                    1/1     Running   0          18m
kube-proxy-6sh45                                    1/1     Running   0          28s
kube-proxy-7dnh8                                    1/1     Running   0          18m
kube-proxy-9vfms                                    1/1     Running   0          14m
kube-scheduler-master-1                             1/1     Running   0          17m
```
```
kubectl get nodes
NAME                        STATUS   ROLES    AGE   VERSION
master-1                    Ready    master   19m   v1.12.1
worker-1                    Ready    <none>   14m   v1.12.1
worker-2                    Ready    <none>   64s   v1.12.1
```
12. Restart Kubelet and Docker on all VMs:
```
for i in $(kubectl get nodes | awk '!/NAME/ {print $1}'); do
    ssh $i 'sudo systemctl stop kubelet; sudo systemctl stop docker; sudo systemctl start docker; sudo systemctl start kubelet'
done
```
13. After restart 'cilium-etcd' PODs have 'Completed' status:
```
kubectl get po -n kube-system
NAME                                                READY   STATUS      RESTARTS   AGE
cilium-89bk4                                        1/1     Running     4          23m
cilium-etcd-bvtgqv5n5n                              0/1     Completed   0          20m
cilium-etcd-hwjpgl6m7t                              0/1     Completed   0          19m
cilium-etcd-lcjbhg8hr4                              0/1     Completed   0          23m
cilium-np5ww                                        0/1     Running     3          9m46s
cilium-p4hgp                                        0/1     Running     5          26m
coredns-576cbf47c7-mwrln                            1/1     Running     1          27m
coredns-576cbf47c7-zvktn                            1/1     Running     1          27m
etcd-operator-7cb79cdf99-4t8kw                      1/1     Running     2          26m
etcd-master-1                                       1/1     Running     1          27m
kube-apiserver-master-1                             1/1     Running     1          27m
kube-controller-manager-master-1                    1/1     Running     1          27m
kube-proxy-6sh45                                    1/1     Running     1          9m46s
kube-proxy-7dnh8                                    1/1     Running     1          27m
kube-proxy-9vfms                                    1/1     Running     1          23m
kube-scheduler-master-1                             1/1     Running     1          27m
```
Partial logs from 'etcd-operator-7cb79cdf99-4t8kw':
```
kubectl logs -f etcd-operator-7cb79cdf99-4t8kw -n kube-system
time="2018-10-18T17:59:08Z" level=info msg="etcd-operator Version: 0.9.2"
time="2018-10-18T17:59:08Z" level=info msg="Git SHA: a0032c1f"
time="2018-10-18T17:59:08Z" level=info msg="Go Version: go1.10"
time="2018-10-18T17:59:08Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-10-18T17:59:08Z" level=info msg="Event(v1.ObjectReference{Kind:\"Endpoints\", Namespace:\"kube-system\", Name:\"etcd-operator\", UID:\"1f10b48e-d2fd-11e8-856d-000d3a02980a\", APIVersion:\"v1\", ResourceVersion:\"3729\", FieldPath:\"\"}): type: 'Normal' reason: 'LeaderElection' etcd-operator-7cb79cdf99-4t8kw became leader"
time="2018-10-18T17:59:08Z" level=info msg="start running..." cluster-name=cilium-etcd pkg=cluster
time="2018-10-18T17:59:16Z" level=warning msg="all etcd pods are dead." cluster-name=cilium-etcd pkg=cluster
time="2018-10-18T17:59:24Z" level=warning msg="all etcd pods are dead." cluster-name=cilium-etcd pkg=cluster
```
Partial logs from 'cilium-etcd-bvtgqv5n5n':
```
kubectl logs -f cilium-etcd-bvtgqv5n5n -n kube-system
2018-10-18 17:45:14.415842 I | etcdserver/membership: added member 262e6357a02edfad [https://cilium-etcd-lcjbhg8hr4.cilium-etcd.kube-system.svc:2380] to cluster 3af7f4fa98d8f6e
2018-10-18 17:45:14.415934 N | etcdserver/membership: set the initial cluster version to 3.2
2018-10-18 17:45:14.415967 I | etcdserver/api: enabled capabilities for version 3.2
2018-10-18 17:45:14.416026 I | etcdserver/membership: added member 868050aa093b4abf [https://cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc:2380] to cluster 3af7f4fa98d8f6e
2018-10-18 17:45:14.425013 I | etcdserver: published {Name:cilium-etcd-bvtgqv5n5n ClientURLs:[https://cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc:2379]} to cluster 3af7f4fa98d8f6e
2018-10-18 17:45:14.425064 I | embed: ready to serve client requests
2018-10-18 17:45:14.425251 I | embed: serving client requests on [::]:2379
WARNING: 2018/10/18 17:45:14 Failed to dial 0.0.0.0:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.
2018-10-18 17:45:22.696785 I | etcdserver/membership: added member 2bd67aa87de05706 [https://cilium-etcd-hwjpgl6m7t.cilium-etcd.kube-system.svc:2380] to cluster 3af7f4fa98d8f6e
2018-10-18 17:45:22.696806 I | rafthttp: starting peer 2bd67aa87de05706...
2018-10-18 17:45:22.696819 I | rafthttp: started HTTP pipelining with peer 2bd67aa87de05706
2018-10-18 17:45:22.697633 I | rafthttp: started streaming with peer 2bd67aa87de05706 (writer)
2018-10-18 17:45:22.698297 I | rafthttp: started streaming with peer 2bd67aa87de05706 (writer)
2018-10-18 17:45:22.698611 I | rafthttp: started peer 2bd67aa87de05706
2018-10-18 17:45:22.698628 I | rafthttp: added peer 2bd67aa87de05706
2018-10-18 17:45:22.698658 I | rafthttp: started streaming with peer 2bd67aa87de05706 (stream MsgApp v2 reader)
2018-10-18 17:45:22.698755 I | rafthttp: started streaming with peer 2bd67aa87de05706 (stream Message reader)
2018-10-18 17:45:27.698746 W | rafthttp: health check for peer 2bd67aa87de05706 could not connect: dial tcp: lookup cilium-etcd-hwjpgl6m7t.cilium-etcd.kube-system.svc on 172.16.0.10:53: n
o such host
2018-10-18 17:45:32.698929 W | rafthttp: health check for peer 2bd67aa87de05706 could not connect: dial tcp: lookup cilium-etcd-hwjpgl6m7t.cilium-etcd.kube-system.svc on 172.16.0.10:53: n
o such host
2018-10-18 17:45:37.699049 W | rafthttp: health check for peer 2bd67aa87de05706 could not connect: dial tcp: lookup cilium-etcd-hwjpgl6m7t.cilium-etcd.kube-system.svc on 172.16.0.10:53: n
o such host
2018-10-18 17:45:42.699197 W | rafthttp: health check for peer 2bd67aa87de05706 could not connect: dial tcp: lookup cilium-etcd-hwjpgl6m7t.cilium-etcd.kube-system.svc on 172.16.0.10:53: n
o such host
2018-10-18 17:45:47.699320 W | rafthttp: health check for peer 2bd67aa87de05706 could not connect: dial tcp: lookup cilium-etcd-hwjpgl6m7t.cilium-etcd.kube-system.svc on 172.16.0.10:53: n
o such host
2018-10-18 17:45:52.699452 W | rafthttp: health check for peer 2bd67aa87de05706 could not connect: dial tcp: lookup cilium-etcd-hwjpgl6m7t.cilium-etcd.kube-system.svc on 172.16.0.10:53: n
o such host
2018-10-18 17:45:55.161424 I | rafthttp: peer 2bd67aa87de05706 became active
2018-10-18 17:45:55.161440 I | rafthttp: established a TCP streaming connection with peer 2bd67aa87de05706 (stream Message reader)
2018-10-18 17:45:55.161445 I | rafthttp: established a TCP streaming connection with peer 2bd67aa87de05706 (stream MsgApp v2 reader)
2018-10-18 17:45:55.172751 I | rafthttp: established a TCP streaming connection with peer 2bd67aa87de05706 (stream Message writer)
2018-10-18 17:45:55.173817 I | rafthttp: established a TCP streaming connection with peer 2bd67aa87de05706 (stream MsgApp v2 writer)
2018-10-18 17:45:57.699633 W | rafthttp: health check for peer 2bd67aa87de05706 could not connect: dial tcp 172.31.1.93:2380: getsockopt: connection refused
2018-10-18 17:58:40.685038 N | pkg/osutil: received terminated signal, shutting down...
2018-10-18 17:58:40.685113 I | etcdserver: skipped leadership transfer for stopping non-leader member
2018-10-18 17:58:40.685294 I | rafthttp: stopped HTTP pipelining with peer 262e6357a02edfad
2018-10-18 17:58:40.685312 I | rafthttp: stopping peer 262e6357a02edfad...
2018-10-18 17:58:40.685505 I | rafthttp: closed the TCP streaming connection with peer 262e6357a02edfad (stream MsgApp v2 writer)
2018-10-18 17:58:40.685517 I | rafthttp: stopped streaming with peer 262e6357a02edfad (writer)
2018-10-18 17:58:40.685656 I | rafthttp: closed the TCP streaming connection with peer 262e6357a02edfad (stream Message writer)
2018-10-18 17:58:40.685665 I | rafthttp: stopped streaming with peer 262e6357a02edfad (writer)
2018-10-18 17:58:40.685714 I | rafthttp: stopped HTTP pipelining with peer 262e6357a02edfad
```
Partial logs from 'cilium-etcd-hwjpgl6m7t':
```
kubectl logs -f cilium-etcd-hwjpgl6m7t -n kube-system
2018-10-18 17:45:55.159309 I | etcdserver: starting server... [version: 3.2.22, cluster version: to_be_decided]
2018-10-18 17:45:55.160204 I | rafthttp: started streaming with peer 868050aa093b4abf (stream Message reader)
2018-10-18 17:45:55.160296 I | rafthttp: started streaming with peer 868050aa093b4abf (stream MsgApp v2 reader)
2018-10-18 17:45:55.160947 I | embed: ClientTLS: cert = /etc/etcdtls/member/server-tls/server.crt, key = /etc/etcdtls/member/server-tls/server.key, ca = , trusted-ca = /etc/etcdtls/member
/server-tls/server-ca.crt, client-cert-auth = true
2018-10-18 17:45:55.161317 I | rafthttp: peer 262e6357a02edfad became active
2018-10-18 17:45:55.161348 I | rafthttp: established a TCP streaming connection with peer 262e6357a02edfad (stream Message writer)
2018-10-18 17:45:55.161354 I | rafthttp: peer 868050aa093b4abf became active
2018-10-18 17:45:55.161359 I | rafthttp: established a TCP streaming connection with peer 868050aa093b4abf (stream Message writer)
2018-10-18 17:45:55.161457 I | rafthttp: established a TCP streaming connection with peer 262e6357a02edfad (stream MsgApp v2 writer)
2018-10-18 17:45:55.161470 I | raft: 2bd67aa87de05706 [term: 1] received a MsgHeartbeat message with higher term from 262e6357a02edfad [term: 21]
2018-10-18 17:45:55.161487 I | raft: 2bd67aa87de05706 became follower at term 21
2018-10-18 17:45:55.161494 I | raft: raft.node: 2bd67aa87de05706 elected leader 262e6357a02edfad at term 21
2018-10-18 17:45:55.161519 I | rafthttp: established a TCP streaming connection with peer 868050aa093b4abf (stream MsgApp v2 writer)
2018-10-18 17:45:55.170142 I | rafthttp: established a TCP streaming connection with peer 262e6357a02edfad (stream Message reader)
2018-10-18 17:45:55.170499 I | rafthttp: established a TCP streaming connection with peer 262e6357a02edfad (stream MsgApp v2 reader)
2018-10-18 17:45:55.172071 I | etcdserver/membership: added member 262e6357a02edfad [https://cilium-etcd-lcjbhg8hr4.cilium-etcd.kube-system.svc:2380] to cluster 3af7f4fa98d8f6e
2018-10-18 17:45:55.172171 N | etcdserver/membership: set the initial cluster version to 3.2
2018-10-18 17:45:55.172208 I | etcdserver/api: enabled capabilities for version 3.2
2018-10-18 17:45:55.172277 I | etcdserver/membership: added member 868050aa093b4abf [https://cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc:2380] to cluster 3af7f4fa98d8f6e
2018-10-18 17:45:55.172611 I | etcdserver/membership: added member 2bd67aa87de05706 [https://cilium-etcd-hwjpgl6m7t.cilium-etcd.kube-system.svc:2380] to cluster 3af7f4fa98d8f6e
2018-10-18 17:45:55.172786 I | rafthttp: established a TCP streaming connection with peer 868050aa093b4abf (stream Message reader)
2018-10-18 17:45:55.173841 I | rafthttp: established a TCP streaming connection with peer 868050aa093b4abf (stream MsgApp v2 reader)
2018-10-18 17:45:55.183304 I | etcdserver: published {Name:cilium-etcd-hwjpgl6m7t ClientURLs:[https://cilium-etcd-hwjpgl6m7t.cilium-etcd.kube-system.svc:2379]} to cluster 3af7f4fa98d8f6e
2018-10-18 17:45:55.183319 I | embed: ready to serve client requests
2018-10-18 17:45:55.183547 I | embed: serving client requests on [::]:2379
WARNING: 2018/10/18 17:45:55 Failed to dial 0.0.0.0:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.
2018-10-18 17:45:55.210283 I | etcdserver: 2bd67aa87de05706 initialzed peer connection; fast-forwarding 8 ticks (election ticks 10) with 2 active peer(s)
2018-10-18 17:58:40.686282 W | rafthttp: lost the TCP streaming connection with peer 868050aa093b4abf (stream MsgApp v2 reader)
2018-10-18 17:58:40.686390 W | rafthttp: lost the TCP streaming connection with peer 868050aa093b4abf (stream Message reader)
2018-10-18 17:58:40.687593 N | pkg/osutil: received terminated signal, shutting down...
2018-10-18 17:58:41.187144 I | raft: 2bd67aa87de05706 [term 21] received MsgTimeoutNow from 262e6357a02edfad and starts an election to get leadership.
2018-10-18 17:58:41.187170 I | raft: 2bd67aa87de05706 became candidate at term 22
2018-10-18 17:58:41.187185 I | raft: 2bd67aa87de05706 received MsgVoteResp from 2bd67aa87de05706 at term 22
2018-10-18 17:58:41.187193 I | raft: 2bd67aa87de05706 [logterm: 21, index: 178] sent MsgVote request to 262e6357a02edfad at term 22
2018-10-18 17:58:41.187200 I | raft: 2bd67aa87de05706 [logterm: 21, index: 178] sent MsgVote request to 868050aa093b4abf at term 22
2018-10-18 17:58:41.187206 I | raft: raft.node: 2bd67aa87de05706 lost leader 262e6357a02edfad at term 22
2018-10-18 17:58:41.227869 I | raft: 2bd67aa87de05706 received MsgVoteResp from 262e6357a02edfad at term 22
2018-10-18 17:58:41.227889 I | raft: 2bd67aa87de05706 [quorum:2] has received 2 MsgVoteResp votes and 0 vote rejections
2018-10-18 17:58:41.227910 I | raft: 2bd67aa87de05706 became leader at term 22
2018-10-18 17:58:41.227921 I | raft: raft.node: 2bd67aa87de05706 elected leader 2bd67aa87de05706 at term 22
2018-10-18 17:58:41.289441 W | rafthttp: lost the TCP streaming connection with peer 262e6357a02edfad (stream MsgApp v2 reader)
2018-10-18 17:58:41.290024 W | rafthttp: lost the TCP streaming connection with peer 262e6357a02edfad (stream Message reader)
2018-10-18 17:58:41.490074 E | rafthttp: failed to write 868050aa093b4abf on stream Message (write tcp 172.31.1.93:2380->172.31.1.72:44072: write: broken pipe)
2018-10-18 17:58:41.490095 I | rafthttp: peer 868050aa093b4abf became inactive
2018-10-18 17:58:41.490230 W | rafthttp: lost the TCP streaming connection with peer 868050aa093b4abf (stream Message writer)
2018-10-18 17:58:41.690092 E | rafthttp: failed to write 262e6357a02edfad on stream Message (write tcp 172.31.1.93:2380->172.31.1.140:33576: write: broken pipe)
2018-10-18 17:58:41.690198 I | rafthttp: peer 262e6357a02edfad became inactive
2018-10-18 17:58:41.690305 W | rafthttp: lost the TCP streaming connection with peer 262e6357a02edfad (stream Message writer)
2018-10-18 17:58:42.436410 W | etcdserver: failed to reach the peerURL(https://cilium-etcd-lcjbhg8hr4.cilium-etcd.kube-system.svc:2380) of member 262e6357a02edfad (Get https://cilium-etcd
-lcjbhg8hr4.cilium-etcd.kube-system.svc:2380/version: dial tcp: i/o timeout)
2018-10-18 17:58:42.436451 W | etcdserver: cannot get the version of member 262e6357a02edfad (Get https://cilium-etcd-lcjbhg8hr4.cilium-etcd.kube-system.svc:2380/version: dial tcp: i/o ti
meout)
2018-10-18 17:58:43.190063 W | raft: 2bd67aa87de05706 stepped down to follower since quorum is not active
2018-10-18 17:58:43.190090 I | raft: 2bd67aa87de05706 became follower at term 22
2018-10-18 17:58:43.190097 I | raft: raft.node: 2bd67aa87de05706 lost leader 2bd67aa87de05706 at term 22
2018-10-18 17:58:43.190467 W | etcdserver: failed to reach the peerURL(https://cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc:2380) of member 868050aa093b4abf (Get https://cilium-etcd
-bvtgqv5n5n.cilium-etcd.kube-system.svc:2380/version: dial tcp: lookup cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc on 172.16.0.10:53: dial udp 172.16.0.10:53: i/o timeout)
2018-10-18 17:58:43.190483 W | etcdserver: cannot get the version of member 868050aa093b4abf (Get https://cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc:2380/version: dial tcp: lookup
 cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc on 172.16.0.10:53: dial udp 172.16.0.10:53: i/o timeout)
2018-10-18 17:58:45.090004 I | raft: 2bd67aa87de05706 is starting a new election at term 22
2018-10-18 17:58:45.090029 I | raft: 2bd67aa87de05706 became candidate at term 23
2018-10-18 17:58:45.090038 I | raft: 2bd67aa87de05706 received MsgVoteResp from 2bd67aa87de05706 at term 23
2018-10-18 17:58:45.090047 I | raft: 2bd67aa87de05706 [logterm: 22, index: 179] sent MsgVote request to 868050aa093b4abf at term 23
2018-10-18 17:58:45.090053 I | raft: 2bd67aa87de05706 [logterm: 22, index: 179] sent MsgVote request to 262e6357a02edfad at term 23
2018-10-18 17:58:45.158907 W | rafthttp: lost the TCP streaming connection with peer 868050aa093b4abf (stream MsgApp v2 writer)
2018-10-18 17:58:46.290051 I | raft: 2bd67aa87de05706 is starting a new election at term 23
2018-10-18 17:58:46.290098 I | raft: 2bd67aa87de05706 became candidate at term 24
2018-10-18 17:58:46.290117 I | raft: 2bd67aa87de05706 received MsgVoteResp from 2bd67aa87de05706 at term 24
2018-10-18 17:58:46.290133 I | raft: 2bd67aa87de05706 [logterm: 22, index: 179] sent MsgVote request to 868050aa093b4abf at term 24
2018-10-18 17:58:46.290147 I | raft: 2bd67aa87de05706 [logterm: 22, index: 179] sent MsgVote request to 262e6357a02edfad at term 24
2018-10-18 17:58:46.822509 W | rafthttp: lost the TCP streaming connection with peer 262e6357a02edfad (stream MsgApp v2 writer)
2018-10-18 17:58:47.687783 I | etcdserver: skipped leadership transfer for stopping non-leader member
2018-10-18 17:58:47.687863 W | etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = body closed by handler")
2018-10-18 17:58:47.687917 I | rafthttp: stopped HTTP pipelining with peer 262e6357a02edfad
2018-10-18 17:58:47.687955 I | rafthttp: stopped HTTP pipelining with peer 868050aa093b4abf
2018-10-18 17:58:47.687967 I | rafthttp: stopping peer 262e6357a02edfad...
2018-10-18 17:58:47.687979 I | rafthttp: stopped streaming with peer 262e6357a02edfad (writer)
2018-10-18 17:58:47.687999 I | rafthttp: stopped streaming with peer 262e6357a02edfad (writer)
```
Partial logs from 'cilium-etcd-lcjbhg8hr4':
```
kubectl logs -f cilium-etcd-lcjbhg8hr4  -n kube-system
2018-10-18 17:44:39.099300 I | etcdserver: setting up the initial cluster version to 3.2
2018-10-18 17:44:39.099441 I | etcdserver: published {Name:cilium-etcd-lcjbhg8hr4 ClientURLs:[https://cilium-etcd-lcjbhg8hr4.cilium-etcd.kube-system.svc:2379]} to cluster 3af7f4fa98d8f6e
2018-10-18 17:44:39.099546 I | embed: serving client requests on [::]:2379
WARNING: 2018/10/18 17:44:39 Failed to dial 0.0.0.0:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.
2018-10-18 17:44:39.129416 N | etcdserver/membership: set the initial cluster version to 3.2
2018-10-18 17:44:39.129472 I | etcdserver/api: enabled capabilities for version 3.2
2018-10-18 17:44:42.608132 I | etcdserver/membership: added member 868050aa093b4abf [https://cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc:2380] to cluster 3af7f4fa98d8f6e
2018-10-18 17:44:42.608157 I | rafthttp: starting peer 868050aa093b4abf...
2018-10-18 17:44:42.608191 I | rafthttp: started HTTP pipelining with peer 868050aa093b4abf
2018-10-18 17:44:42.609055 I | rafthttp: started streaming with peer 868050aa093b4abf (writer)
2018-10-18 17:44:42.609596 I | rafthttp: started streaming with peer 868050aa093b4abf (writer)
2018-10-18 17:44:42.610475 I | rafthttp: started peer 868050aa093b4abf
2018-10-18 17:44:42.610500 I | rafthttp: added peer 868050aa093b4abf
2018-10-18 17:44:42.610533 I | rafthttp: started streaming with peer 868050aa093b4abf (stream Message reader)
2018-10-18 17:44:42.610648 I | rafthttp: started streaming with peer 868050aa093b4abf (stream MsgApp v2 reader)
2018-10-18 17:44:43.102504 W | etcdserver: failed to reach the peerURL(https://cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc:2380) of member 868050aa093b4abf (Get https://cilium-etcd
-bvtgqv5n5n.cilium-etcd.kube-system.svc:2380/version: dial tcp: lookup cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc on 172.16.0.10:53: no such host)
2018-10-18 17:44:43.102525 W | etcdserver: cannot get the version of member 868050aa093b4abf (Get https://cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc:2380/version: dial tcp: lookup
 cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc on 172.16.0.10:53: no such host)
2018-10-18 17:44:44.098955 W | raft: 262e6357a02edfad stepped down to follower since quorum is not active
2018-10-18 17:44:44.098986 I | raft: 262e6357a02edfad became follower at term 2
2018-10-18 17:44:44.098992 I | raft: raft.node: 262e6357a02edfad lost leader 262e6357a02edfad at term 2
2018-10-18 17:44:44.833887 I | raft: 262e6357a02edfad no leader at term 2; dropping index reading msg
2018-10-18 17:44:45.498991 I | raft: 262e6357a02edfad is starting a new election at term 2
2018-10-18 17:44:45.499015 I | raft: 262e6357a02edfad became candidate at term 3
2018-10-18 17:44:45.499023 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 3
2018-10-18 17:44:45.499032 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 3
2018-10-18 17:44:46.799001 I | raft: 262e6357a02edfad is starting a new election at term 3
2018-10-18 17:44:46.799028 I | raft: 262e6357a02edfad became candidate at term 4
2018-10-18 17:44:46.799037 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 4
2018-10-18 17:44:46.799045 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 4
2018-10-18 17:44:47.610630 W | rafthttp: health check for peer 868050aa093b4abf could not connect: dial tcp: lookup cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc on 172.16.0.10:53: n
o such host
2018-10-18 17:44:48.398936 I | raft: 262e6357a02edfad is starting a new election at term 4
2018-10-18 17:44:48.398962 I | raft: 262e6357a02edfad became candidate at term 5
2018-10-18 17:44:48.398970 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 5
2018-10-18 17:44:48.398983 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 5
2018-10-18 17:44:49.798964 I | raft: 262e6357a02edfad is starting a new election at term 5
2018-10-18 17:44:49.798986 I | raft: 262e6357a02edfad became candidate at term 6
2018-10-18 17:44:49.798994 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 6
2018-10-18 17:44:49.799002 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 6
2018-10-18 17:44:51.298932 I | raft: 262e6357a02edfad is starting a new election at term 6
2018-10-18 17:44:51.298957 I | raft: 262e6357a02edfad became candidate at term 7
2018-10-18 17:44:51.298964 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 7
2018-10-18 17:44:51.298971 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 7
2018-10-18 17:44:51.833981 W | etcdserver: timed out waiting for read index response
2018-10-18 17:44:52.398970 I | raft: 262e6357a02edfad is starting a new election at term 7
2018-10-18 17:44:52.398995 I | raft: 262e6357a02edfad became candidate at term 8
2018-10-18 17:44:52.399003 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 8
2018-10-18 17:44:52.399011 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 8
2018-10-18 17:44:52.610762 W | rafthttp: health check for peer 868050aa093b4abf could not connect: dial tcp: lookup cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc on 172.16.0.10:53: n
o such host
2018-10-18 17:44:53.998999 I | raft: 262e6357a02edfad is starting a new election at term 8
2018-10-18 17:44:53.999031 I | raft: 262e6357a02edfad became candidate at term 9
2018-10-18 17:44:53.999040 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 9
2018-10-18 17:44:53.999049 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 9
2018-10-18 17:44:55.798929 I | raft: 262e6357a02edfad is starting a new election at term 9
2018-10-18 17:44:55.798961 I | raft: 262e6357a02edfad became candidate at term 10
2018-10-18 17:44:55.798972 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 10
2018-10-18 17:44:55.798981 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 10
2018-10-18 17:44:57.199051 I | raft: 262e6357a02edfad is starting a new election at term 10
2018-10-18 17:44:57.199080 I | raft: 262e6357a02edfad became candidate at term 11
2018-10-18 17:44:57.199103 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 11
2018-10-18 17:44:57.199112 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 11
2018-10-18 17:44:57.610931 W | rafthttp: health check for peer 868050aa093b4abf could not connect: dial tcp: lookup cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc on 172.16.0.10:53: d
ial udp 172.16.0.10:53: i/o timeout
2018-10-18 17:44:58.834195 W | etcdserver: timed out waiting for read index response
2018-10-18 17:44:58.999035 I | raft: 262e6357a02edfad is starting a new election at term 11
2018-10-18 17:44:58.999083 I | raft: 262e6357a02edfad became candidate at term 12
2018-10-18 17:44:58.999100 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 12
2018-10-18 17:44:58.999117 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 12
2018-10-18 17:45:00.598974 I | raft: 262e6357a02edfad is starting a new election at term 12
2018-10-18 17:45:00.599001 I | raft: 262e6357a02edfad became candidate at term 13
2018-10-18 17:45:00.599009 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 13
2018-10-18 17:45:00.599019 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 13
2018-10-18 17:45:02.498909 I | raft: 262e6357a02edfad is starting a new election at term 13
2018-10-18 17:45:02.498941 I | raft: 262e6357a02edfad became candidate at term 14
2018-10-18 17:45:02.498950 I | raft: 262e6357a02edfad received MsgVoteResp from 262e6357a02edfad at term 14
2018-10-18 17:45:02.498959 I | raft: 262e6357a02edfad [logterm: 2, index: 5] sent MsgVote request to 868050aa093b4abf at term 14
2018-10-18 17:45:02.611099 W | rafthttp: health check for peer 868050aa093b4abf could not connect: dial tcp: lookup cilium-etcd-bvtgqv5n5n.cilium-etcd.kube-system.svc on 172.16.0.10:53: n
o such host
```
All TLS certs in place:
```
kubectl get secret -n kube-system | grep cilium
cilium-etcd-client-tls                           Opaque                                3      129m
cilium-etcd-peer-tls                             Opaque                                3      129m
cilium-etcd-sa-token-d8v8g                       kubernetes.io/service-account-token   3      128m
cilium-etcd-server-tls                           Opaque                                3      129m
cilium-token-cfxhn                               kubernetes.io/service-account-token   3      128m
```
### Workaround
1. cd cilium-1.2.3/examples/kubernetes/addons/etcd-operator/
2. kubectl delete -f cilium-etcd-cluster.yaml
3. kubectl create -f cilium-etcd-cluster.yaml
Back to normal:
```
NAME                                                READY   STATUS    RESTARTS   AGE
cilium-89bk4                                        1/1     Running   34         3h
cilium-etcd-9mqbfzzr2c                              1/1     Running   0          92s
cilium-etcd-cv4b25nlfw                              1/1     Running   0          110s
cilium-etcd-p49z25r78r                              1/1     Running   0          44s
cilium-np5ww                                        1/1     Running   33         167m
cilium-p4hgp                                        1/1     Running   35         3h4m
coredns-576cbf47c7-mwrln                            1/1     Running   1          3h5m
coredns-576cbf47c7-zvktn                            1/1     Running   1          3h5m
etcd-operator-7cb79cdf99-4t8kw                      1/1     Running   2          3h4m
etcd-master-1                                       1/1     Running   1          3h4m
kube-apiserver-master-1                             1/1     Running   1          3h4m
kube-controller-manager-master-1                    1/1     Running   1          3h4m
kube-proxy-6sh45                                    1/1     Running   1          167m
kube-proxy-7dnh8                                    1/1     Running   1          3h5m
kube-proxy-9vfms                                    1/1     Running   1          3h
kube-scheduler-master-1                             1/1     Running   1          3h4m
```

**Comment by tgraf** [comment]
@jek-a This is a known issue of the etcd-operator. It will be addressed by the following new project: https://github.com/cilium/cilium-etcd-operator. Feel free to try it out, it only lacks docs before we can announce it.

**Comment by jek-a** [comment]
@tgraf Thanks! 
I checked this new project. It looks very straightforward, so the docs is not a problem. The cilium-etcd-operator deployment creates a permanent job to check if etcd cluster is running. I will try it out later. For now, I bootstrapped a standalone etcd cluster with k8s analogy and use it for Cilium.

**Comment by jek-a** [comment]
@tgraf Today, I tried to install k8s + Cilium using 'cilium-etcd-operator', but unfortunately it did not work. I have submitted a bug.

**Comment by tgraf** [comment]
@jek-a The issue has been fixed. The latest release also takes care of automatically creating the secrets if they don't exist.

**Comment by jek-a** [comment]
@tgraf I tried it one more time today and it still does not work properly. I submitted a new bug again. Don't know if you tried to test it. Unfortunately I don't have a time to play with it anymore, cause I need K8S with Cilium ASAP. So I created a working solution: https://github.com/jek-a/k8s-cilium-deployment
If you want you can check it out. So, this ticket can be closed.
